### ISSUE TITLE
how to run matrad into matlab-equivalent as matfree or octave?

### ISSUE THREAD

**Issue by EL-Bakkali-Jaafar** [e0404/matRad#100]

**Comment by markbangert** [comment]
Hi EL-Bakkali-Jaafar,

thank you for your interest in matRad! Using Octave you should be able to run all matRad scripts and functions _without_ the GUI (i.e. everything should work except matRadGUI.m) out of the box. Unfortunately there is no support in Octave of the matlab GUI features so we cannot provide this either.

We have never tried to run matRad with freemat so we cannot help you with this.

Cheers / Mark

**Comment by EL-Bakkali-Jaafar** [comment]
Thank you for your response Mark, now I have installed the matrad software on win64 via matrad installer, but I get the following message error when i try to run matrad.
Error using cd
Cannot CD to d:\git\matRad <Directory permission denied>

Error in startup <line 3>
Cannot CD to d:\git\matRad <Directory permission denied>

Jaafar,

**Comment by markbangert** [comment]
Did you download the installer from the dev branch? ... It has not been
updated yet in the master branch!

Am 16.10.2016 4:26 nachm. schrieb "Jaafar EL Bakkali" <
notifications@github.com>:

**Comment by EL-Bakkali-Jaafar** [comment]
No, I have downloaded it from master branch by clicking on '' clone or download'' button.

**Comment by markbangert** [comment]
please use this file. 

https://github.com/e0404/matRad/blob/dev/standalone/matRad_installerWin64.exe

We recently fixed this issue on the development branch (dev). We'll merge this into the main release within this week.

**Comment by EL-Bakkali-Jaafar** [comment]
OK, the latest file seems to work correctly. Thank you.
