### ISSUE TITLE
Isocenter buggy

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#104]
I think there might be a bug in the computation of the isocenter in https://github.com/e0404/matRad/blob/master/dicomImport/matRad_importDicomRTPlan.m#L97 that @aluisiocastro came across.

Unfortunately imagePositionPatient does not necessarily use the first slice of the CT  (compare CT DICOM import). @becker89 & @AlexS1992 do you think this could solve the problem for the single beam offset in the photon dose calculation?

**Comment by markbangert** [comment]
I think this might fix the issues...

function pln = matRad_importDicomRTPlan(ct, rtPlanFiles, dicomMetaBool)
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% matRad function to import dicom RTPLAN data
% 
% call
%   pln = matRad_importDicomRTPlan(ct, rtPlanFiles, dicomMetaBool)
%
% input
%   ct:             ct imported by the matRad_importDicomCt function
%   rtDoseFiles:   	list of RTDOSE Dicom files
%   dicomMetaBool:  import whole dicom information
%
% output
%   pln:            matRad pln struct with meta information. Note that
%                   bixelWidth is determined via the importSteering function.
%
% References
%   -
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Copyright 2015 the matRad development team. 
% 
% This file is part of the matRad project. It is subject to the license 
% terms in the LICENSE file found in the top-level directory of this 
% distribution and at https://github.com/e0404/matRad/LICENSES.txt. No part 
% of the matRad project, including this file, may be copied, modified, 
% propagated, or distributed except according to the terms contained in the 
% LICENSE file.
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% %% print current status of the import script
% fprintf('Please provide an appropriate machine file:\n');

%% load plan file
% check size of RT Plan
if size(rtPlanFiles,1) ~= 1
   errordlg('Too few or to many RTPlan files')
end

% read information out of the RT file
planInfo = dicominfo(rtPlanFiles{1});

% check which type of Radiation is used
if isfield(planInfo, 'BeamSequence')
    BeamParam = 'BeamSequence';
    ControlParam = 'ControlPointSequence';
elseif isfield(planInfo, 'IonBeamSequence')
    BeamParam = 'IonBeamSequence';
    ControlParam = 'IonControlPointSequence';
else
    errordlg('Not supported kind of DICOM RT plan file.');    
end

% use the treatment beams only
BeamSequence = planInfo.(BeamParam);
BeamSeqNames = fieldnames(BeamSequence);
for i = 1:length(BeamSeqNames)
    currBeamSeq = BeamSequence.(BeamSeqNames{i});
    try
        treatDelType = currBeamSeq.TreatmentDeliveryType;
        if ~strcmpi(treatDelType,'TREATMENT')
            BeamSequence = rmfield(BeamSequence,BeamSeqNames{i});
        end
    catch
        warning('Something went wrong while determining the type of the beam.');
    end
end
BeamSeqNames = fieldnames(BeamSequence);

%% get information may change between beams
% loop over beams
gantryAngles{length(BeamSeqNames)} = [];
PatientSupportAngle{length(BeamSeqNames)} = [];
isoCenter{length(BeamSeqNames)} = [];
for i = 1:length(BeamSeqNames)   
    currBeamSeq             = BeamSequence.(BeamSeqNames{i});
    % parameters not changing are stored in the first ControlPointSequence
    gantryAngles{i}         = currBeamSeq.(ControlParam).Item_1.GantryAngle;
    PatientSupportAngle{i}  = currBeamSeq.(ControlParam).Item_1.PatientSupportAngle;
    isoCenterDicom{i}       = currBeamSeq.(ControlParam).Item_1.IsocenterPosition;
end

% check wether isocenters are consistent
if numel(isoCenter) > 1
    if ~isequal(isoCenter{:})
       errordlg('Values for isocenter are not consistent.')
    end
end

% transform iso. At the moment just this way for HFS
if ct.dicomInfo.ImageOrientationPatient == [1;0;0;0;1;0]
    isoCenter = [interp1(ct.x,1:numel(ct.x),isoCenterDicom{1}(1)) * ct.resolution.x ...
                 interp1(ct.y,1:numel(ct.y),isoCenterDicom{1}(2)) * ct.resolution.y ...
                 interp1(ct.z,1:numel(ct.z),isoCenterDicom{1}(3)) * ct.resolution.z];
else
    error('This Orientation is not yet supported.');
end

%% read constant parameters
% readout charge and mass to set radiationMode to matRad specific name
radiationMode = planInfo.(BeamParam).Item_1.RadiationType;
if ~strncmpi(radiationMode,'photons',6)
    try
        radiationMass = planInfo.(BeamParam).Item_1.RadiationMassNumber;
        radiationAtomicNumber = planInfo.(BeamParam).Item_1.RadiationAtomicNumber;
    catch
        warning('Could not determine mass and atomic number of the particle');
    end
end

if strncmpi(radiationMode,'photons',6)
    radiationMode = 'photons';
elseif strncmpi(radiationMode,'proton',6)
    radiationMode = 'protons';
elseif (strncmpi(radiationMode,'ion',3) && radiationMass == 12 && radiationAtomicNumber == 6)
    radiationMode = 'carbon';
else
    warning('The given type of radiation is not yet supported');
end

%% write parameters found to pln variable
pln.isoCenter       = isoCenter;
pln.radiationMode   = radiationMode; % either photons / protons / carbon
pln.bixelWidth      = NaN; % [mm] / also corresponds to lateral spot spacing for particles
pln.gantryAngles    = [gantryAngles{1:length(BeamSeqNames)}];
pln.couchAngles     = [PatientSupportAngle{1:length(BeamSeqNames)}]; % [Â°]
pln.numOfBeams      = length(BeamSeqNames);
pln.numOfVoxels     = numel(ct.cube{1});
pln.voxelDimensions = ct.cubeDim;
pln.bioOptimization = NaN; % none: physical optimization; effect: effect-based optimization; RBExD: optimization of RBE-weighted dose
pln.numOfFractions  = planInfo.FractionGroupSequence.Item_1.NumberOfFractionsPlanned;
pln.runSequencing   = NaN; % 1/true: run sequencing, 0/false: don't / will be ignored for particles and also triggered by runDAO below
pln.runDAO          = NaN; % 1/true: run DAO, 0/false: don't / will be ignored for particles
pln.machine         = 'unknown';

% timestamp
pln.timeStamp = datestr(clock);

try
   pln.SOPClassUID = planInfo.SOPClassUID;
   pln.SOPInstanceUID = planInfo.SOPInstanceUID;
   pln.ReferencedDoseSequence = planInfo.ReferencedDoseSequence;
catch
end

% safe entire dicomInfo
if dicomMetaBool == true
    pln.dicomMeta = planInfo;
end
end

**Comment by AlexS1992** [comment]
Hi Mark,

mhm good question...
I still dont understand how a isocenter shift could affect only one of the
7 beams, so I personally would be very surprised if this would solve the
problem.

Looking at the definition of the DICOM tag it sounds to me as if
ImagePosition should usually be defined in the first slice (see
http://dicom.nema.org/medical/dicom/2014c/output/chtml/part03/sect_C.7.6.2.html
).
There it is stated that it should point to the first upper left voxel.

I could check if this change does actually change the isocenter for the
intra example, if I get the same result this will answer the question
directly.

How did aluisiocastro experience this bug? Do we have the DICOM RT plan and
maybe the CT which he used to have a look at it?
Would be interesting to see in combination with the CT tags.

I will definitely check this out tomorrow!

Best regards, Alex


Mark Bangert <notifications@github.com> schrieb am Mi., 26. Okt. 2016 um
23:23 Uhr:

**Comment by markbangert** [comment]
The problem is that ImagePositionPatient differs for different slices so if you happen to read e.g. the second or third slice first during ct import you consider this to be the edge of the entire cube!

**Comment by becker89** [comment]
Indeed ImagePositionPatient is different for each slice, but we are already reordering the ct slices according to their ImagePosition in [link1](https://github.com/e0404/matRad/blob/master/dicomImport/matRad_importDicomCt.m#L80). 
Using the proposed code for the iso center interpolation  didn't change the iso center (compared to the old version) for the single beam cases.

**Comment by markbangert** [comment]
Argh... OK. You are fully right. Nevertheless my suggestion fixes everything for Aluisio!

**Comment by markbangert** [comment]
Also I treid to reproduce the error from Aluisio with my code and I could not do it. Really strange!

**Comment by markbangert** [comment]
One idea: Does ImagePositionPatient code for the center of the CT slice or for the corner?

**Comment by markbangert** [comment]
Looking at the definition of ImagePositionPatient at http://dicom.nema.org/medical/dicom/2014c/output/chtml/part03/sect_C.7.6.2.html#sect_C.7.6.2.1.1 and considering that we sort everything I am somewhat flummoxed about Aluisio's bug now. Also, taking his input data and the current dev branch, I could not reproduce the bug he reported. I will ask him again about this and update you once more right here. Cheers!

**Comment by markbangert** [comment]
Talked to ALuisio agian today. He cannot reproduce the bug so we assume there never was one and instead he might have messed up something else...

So I am going to close this issue!
