### ISSUE TITLE
Independent dose and CT grid

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#113]
it would be a big step forward if we could decouple the dose grid resolution from the ct resolution. That way we could do the ray tracing on the original CT data and still work with small dose influence matrix sizes...

**Comment by markbangert** [comment]
This means a major change of interal matRad coordinate systems. Maybe it is a good idea to also work towards a better integration with world coordinates as originally stored within the DICOM images.

**Comment by markbangert** [comment]
And: Re-think dimension permuation to deal with matlab standard visualization of imagesc command.

**Comment by wahln** [comment]
i thought a little bit about this and I think we should do it right by also organizing dose cubes as objects with meta data (i.e. give them coordinaets, resolutions, etc..) similar to the ct struct... this would allow to also handle imported doses with completely different resolutions for comparisons, and allow easy aligning of the cubes by altering the meta-information. Might be a little bit tedious, but probably worth it. Maybe we should generally think of a more general way to handle and allow image cubes in matRad. This could also be a basis for more fancy stuff like displaying or working with MR or PET images along/above the CT.
