### ISSUE TITLE
Error in fetching field shapes from RTPLAN.dcm having open field plan exported from Eclipse 

### ISSUE THREAD

**Issue by starplanet18** [e0404/matRad#123]
Error in fetching field shapes in matRad_importFieldShapes.m at line no 85 - line no 93. Can anyone please clarify the concept.  Two unknown was called during fetching of the field shapes.

  for k = 1:length(DeviceSeqNames)
            currLeafPos = currFieldSeq.BeamLimitingDevicePositionSequence.(DeviceSeqNames{k}).LeafJawPositions;
%             currLeafPos = currBeamSeq.BeamLimitingDeviceSequence.(DeviceSeqNames{k}).LeafPositionBoundaries;
            
            Collimation.Fields(counter).LeafPos{k} = NaN*ones(Collimation.Devices(k).NumOfLeafs,2);
            Collimation.Fields(counter).LeafPos{k}(:,1) = currLeafPos(1:Collimation.Devices(k).NumOfLeafs);
            Collimation.Fields(counter).LeafPos{k}(:,2) = currLeafPos(Collimation.Devices(k).NumOfLeafs+1:end); 
        end

Can anyon please help me to solve this error

**Comment by markbangert** [comment]
Thanks for reporting this bug. Any chance you can share the files with us so we can reproduce this error? Or is that not possible for data privacy reasons etc? In case you can send the files feel free to use m.bangert@dkfz.de.

Cheers/Mark

**Comment by starplanet18** [comment]
Please check your email, Bangert. I have sent you the datafile

Gaganpreet Singh

**Comment by starplanet18** [comment]
Can you please update me regarding the status of the issue, if you allow I can also involve in upgradation process.

**Comment by AlexS1992** [comment]
Hi, 
I have a fix for this issue, but I still need to test it.
I will push the updates this evening and post a link for you to check it out, okay?
Greetings, Alex

**Comment by starplanet18** [comment]
Hi @AlexS1992 
Ok that is great , I will do the testing part and inform you about the status.
Thanks

Gaganpreet Singh

**Comment by AlexS1992** [comment]
@starplanet18 I just pushed the bugfix (https://github.com/e0404/matRad/pull/126), maybe you could have a look at it and see if everything works now as expected.
One important thing: At the moment we only support field sizes up to 200x200 mm^2. We are currently working on an update to include larger field sizes, but this in not yet ready, therefore you have to be careful if your field exceeds a lateral distance of 100mm in any direction.
In this case you could (as a temporary workaround) change the value of convLimits for the field import in [Line 117](https://github.com/e0404/matRad/blob/master/dicomImport/matRad_importFieldShapes.m#L117)  and for the dose calculation at [Line 114](https://github.com/e0404/matRad/blob/master/matRad_calcPhotonDose.m#L114).

**Comment by starplanet18** [comment]
@AlexS1992 I tried to import the same file what I have sent to the @becker89 . It is now working and showing the results without any error. Thanks for the updates,

**Comment by markbangert** [comment]
I just merged everything into the dev branch. I am sorry for the delay in reviewing your code, @AlexS1992 but it's been a couple of things piling up on my desk recently. Thanks for the good work. Looking forward to the pull request with variable adjustment of fluence matrix ;)
