### ISSUE TITLE
Issue ragarding visualization of colorwash 

### ISSUE THREAD

**Issue by starplanet18** [e0404/matRad#124]
Dear Sir,

I have faced an issue in color wash. when I try to change the lower threshold value from the colorbar, it updates the color bar but it shows the zeros value + values greater than lower threshold values. According to me, in any case, the blue color should not be spread over all the CT image if we increase the lower threshold. it should be limited to the only region which has dose greater than or equal to the minimum threshold.

Gaganpreet Singh

**Comment by markbangert** [comment]
I agree that the behaviour should be the way you describe. I just created a pull request at https://github.com/e0404/matRad/pull/125. Could you please have a look at the code and test if it works? Afterwards we can merge it.

Thanks / Mark

**Comment by starplanet18** [comment]
Hi Markbangert and becker,
I have checked the code it is now working properly for the lower threshold but fails for the upper limits.

It does not work like a band pass filter, it works only for the lower threshold value, but i reduce the upper limit to some lower level it is not working well it shows the same probelm as previous but in reverse manner.

It shows the red colour when i try to decrease the value of upper limit from the maximum dose to some certain value.

Suppose i take an arbitrary example which have dose matrix whose values lies between 0.1-3.5 Gy. when i try to visualize the color wash from 1-3.5 Gy it works fine and when i try to visualize the colorwash from 1-2.5 Gy it shows the red colour on the voxels which have values higher than 2.5 Gy.

Regards,
Gaganpreet Singh

**Comment by becker89** [comment]
I will have a look into it. Thanks for reporting Singh

**Comment by markbangert** [comment]
I see what you mean. However, I am somewhat reluctant to incorporate such functionality into the main release. If this behaviour is desirable for your very use case I suggest you make the according changes in plotting/matRad_plotDoseSlice. Looking at the modifications we made you can easily do that yourself. If we were to include the changes with regard to the max dose threshold into the main release, I see the possibility that accidently the high dose is cut off which might be more confusing for users. On top there is the possibility to specify the iso dose contour levels if you want to look at specific values. I think that does suffice.

If you do not have any additional points I would like to ask @becker89 to perform the merge if he does not see any additional problems with the code in pull request #125.

**Comment by becker89** [comment]
I had already implemented it but haven't responded yet 'cause I wanted to test the code before creating the pull request. Changes in the GUI take always longer than anticipated. First of all we need to distinguish between dose cutoff and setting limits for dose color wash. A relative dose cut off to disable dose color wash is desirable and has been implemented by Mark. Hence the dose cut off will only be applied when the lower dose color wash bound is set to 0. However when we want to visualize only a specific dose range we do not need a certain dose cut off as we just want to show dose in the specified range. This can be done in two ways. Considering your example Singh, if the dose range is set to 1-2.5Gy then values from 0-1 are mapped to dark blue and values beyond 2.5 to dark red when using jet colormap. The second option is to disable dose values for plotting below 1Gy and beyond 2.5Gy and just plotting the specified range. I have implemented the second option now. But it is easy to change it back. Can you have a look at it Singh ?
<img width="1028" alt="dose_cropping" src="https://cloud.githubusercontent.com/assets/1581106/22274762/ee98e0dc-e26d-11e6-97de-f03e1e746b54.png">

What do you think @markbangert ?

**Comment by markbangert** [comment]
Hm now that I see how it looks like I have second feelings ;) Infact it should be hard to misinterpret this. Let's include Hans-Peter's version of the code. Could you make a pull request and I review?

**Comment by starplanet18** [comment]
@becker89 I agree with the second option. what you say @markbangert, this would be more useful and better than the previous ones. 
Can you please upload or send me the code with the second option or update with the changes.

**Comment by becker89** [comment]
The code is available on my matRad fork: https://github.com/becker89/matRad/tree/devColorRange  
From that branch I have created a pull request to @markbangert to his dev branch https://github.com/markbangert/matRad/pulls. Once he accepts my pull request the changes should then be propagated to #125

**Comment by starplanet18** [comment]
hi @becker89  it is working fine now as you shown. Great Job done, Can I have your email id. Further, I would like to work in your team. You all are amazing and dynamic peoples.

regards,
Gaganpreet Singh,

**Comment by becker89** [comment]
Hi Singh, I am glad the code works. However it still needs some adjustments (getting rid of some redundancies) and another iteration of code review before we merge it into the public dev branch. Generally speaking, one of the main ideas behind making matRad public on GitHub was to have firstly a transparent code development and secondly to encourage contribution by means of "pull requests"  to the matRad toolkit from outside of our institution. As our time is limited we can not implement all feature requests on our own. Consequently, we are also counting on the community :-) 
You were mentioned improvements regarding the DVH. So If you want to contribute then you could add step by step new functionalities to the DVH on your own. What do you think ?
By the way - do you know the concepts of pull requests ?

**Comment by markbangert** [comment]
I just merged Hans-Peter's code into the dev branch. Will close this issue. Good work!
