### ISSUE TITLE
Colors and general appearance of Structure Visibility panel

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#134]
The colors displayed in the structure visibility panel within the GUI do not match the contours drawn on the CT. This applies for both data sets loaded from within the GUI and for data sets loaded via the command prompt, and for loading data into a blank GUI and when replacing patient data. If you toggle some structure on of then sometimes the colors are updated to be correct.

@Haydnspass could you take care of this?

**Comment by wahln** [comment]
I think when I did this color-choosing and plot modularization thing I missed setting up a variable that holds the the colormap for the VOIs, so they are always plotted by calling colorcube... this could lead to some inconsistency... sorry.

**Comment by Haydnspass** [comment]
Yep, working on it. I thought it's most convenient to store structure colors in cst{i,5}.color then it's always consistent and durable (e.g. after reopening).

**Comment by markbangert** [comment]
Sounds reasonable to me. Maybe make it visColor?!

**Comment by wahln** [comment]
Could you handle it in a way that plotting function still allows to assign a colormap optionally to temporary override the cst visColor then? I find this very useful if you need less "flashy" contour colors for plots and can just assign autumn or grey for example.

**Comment by Haydnspass** [comment]
Merged in dev branch --> Should be closed?

**Comment by markbangert** [comment]
Thanks for pointing this out. Issue closed!
