### ISSUE TITLE
Lateral cutoff for particles

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#143]
I have doubts that the compensation for integral dose works fine as we see substantial discrepancies if we reduce the cutoff to values around 0.99. Shouldn't that be a range where we still have somewhat acceptable agreement if we scale accordingly?!

**Comment by becker89** [comment]
I will have a look at it.

**Comment by markbangert** [comment]
is currently being addressed with https://github.com/e0404/matRad/pull/180
