### ISSUE TITLE
CERRHotKeys

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#145]
I keep getting a funny error from a key press function that I cannot explain.

Sometimes when I press some key during function execution (e.g. shift+tab to change window focus) I get the following error message

Undefined function or variable 'CERRHotKeys'.
 
Error while evaluating Figure KeyPressFcn

but I cannot find this KeyPressFcn nowhere! And CERR is not on my search path. Anybody seen the same thing?

**Comment by wahln** [comment]
also seen it a few times. did you launch CERR at any time in the session? because CERR sets default callbacks, e.g. via set(0,'DefaultFigureCreateFcn','set(gcbo,''KeyPressFcn'',''CERRHotKeys'')') which are probably kept even when it is removed from the search path.

**Comment by wahln** [comment]
I also searched all file contents within the matRad folder, to see if it snuck in somewhere in our files, but doesn't seem to by the case.

**Comment by markbangert** [comment]
Got it:

![image](https://cloud.githubusercontent.com/assets/10157181/23897053/034a509c-08ac-11e7-8946-c0c1b685d8bb.png)

Could you adjust the GUI propertes with your pull request? Otherwise we will get merge confilicts or I have to do it later...

**Comment by markbangert** [comment]
Has been fixed with https://github.com/e0404/matRad/commit/17642de
