### ISSUE TITLE
Bug in matRad_interp1

### ISSUE THREAD

**Issue by Haydnspass** [e0404/matRad#149]
There is seems to be a bug in matRad_interp1 (dev and master branch) which occurs when one wants to calculate a simple prostate case particle plan.
Line 51 was changed from (commit d7f216b)
`y = yi(ix1) + ( yi(ix2)-yi(ix1) ) * ( x - xi(ix1) ) / ( xi(ix2) - xi(ix1) );`
to
`  y = yi(ix1,:) + ( yi(ix2,:)-yi(ix1,:) ) * ( x - xi(ix1) ) / ( xi(ix2) - xi(ix1) );    `
. 
For example, executing `matRad_interp1([1 20], [5 6], 5)` fails. since data is no column vector.
@markbangert in commit d7f216b?

**Comment by wahln** [comment]
I filed a pull request. in generate_stf the points were given as row and not as column vectors

**Comment by markbangert** [comment]
The changes in https://github.com/e0404/matRad/commit/d7f216bc0f557e8817444d4477d70a92883e9fb5 are necessary to maintain compatibility for simultaneous interpolation on multiple 1D data sets _and_ interpolation of only a single data point. This is why it is now necessary to have vectors in column format.

I will merge the pull request by @wahln now!

Thanks for pointing this out.
