### ISSUE TITLE
Constraints defined on overlapped structures

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#156]
If we have a constraint defined on a VOI that is completely overlapped by another VOI the jacobian will be an empty matrix, however, ipopt expects a jacobian with the valid dimensions (1xB).

For objectives we issue a warning and everything is OK. This warning will also be shown for the 'overlapped' constraint, however, the optimization will not continue but crash.

What do you think we should do in these cases @Haydnspass @becker89? Check in setOverlapPriorities and throw and error and stop optimization for both objectives and constraints?

Thanks @waldwuffel for reporting!

**Comment by becker89** [comment]
Sorry for the late reply - I would prefer issuing an error cause then the user then really know what is going on. Otherwise, I often have the feeling that our warnings are overseen, especially when then optimization runs through successfully. No one scrolls back in the command line to look for warnings. What do you think ?

**Comment by markbangert** [comment]
I agree! If this is fine with @Haydnspass as well I would like to ask him
to prepare a small pull request...

Am 15.05.2017 2:26 nachm. schrieb "becker89" <notifications@github.com>:

Sorry for the late reply - I would prefer issuing an error cause then the
user then really know what is going on. Otherwise, I often have the feeling
that our warnings are overseen, especially when then optimization runs
through successfully. No one scrolls back in the command line to look for
warnings. What do you think ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/e0404/matRad/issues/156#issuecomment-301459737>, or mute
the thread

**Comment by Haydnspass** [comment]
Hm, I haven't worked with optimization so far, so maybe I am wrong: matRad does not distinguish between objectives and constraints in the cst var, does it? Since I figure both are in the struct cst{i,6}? 
If that's the case we just need to convert the warning in setOverlap to an error right?

**Comment by markbangert** [comment]
That is true. I will make the changes and close this issue!
