### ISSUE TITLE
Same HLUT for photons/particles if same CT

### ISSUE THREAD

**Issue by waldwuffel** [e0404/matRad#157]
For plans with photons or particles based on the same CT image, the same HLUT is called, since only machine and kernel name are requested, but not particle type. Could this be added to HLUT call?

**Comment by markbangert** [comment]
@waldwuffel is this issue sufficiently addressed by your pull request? Can we close this issue after the merge? BTW We will probably merge before Xmas! Wow...

**Comment by waldwuffel** [comment]
Yes, it is! Thanks!
