### ISSUE TITLE
Iso energy selection

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#166]
@burigolucas pointed out that we do the energy selection per ray which yields a lot of energies per beam orientations. This should be adjusted to an energy selection per field...

**Comment by markbangert** [comment]
@silkeulrich haven't you already solved this issue?

**Comment by silkeulrich** [comment]
yes, and maybe also Hans-Peter
My solution is independent of the target location

**Comment by becker89** [comment]
Can you do a pull request Silke, cause I don't have a solution for this ;-)

**Comment by markbangert** [comment]
@silkeulrich I think this functionality is still not included in our dev branch. can you make a pull request? or at least send me information on how to do it?

**Comment by markbangert** [comment]
apparently this has already been incorporated. Thanks @silkeulrich for haveing another look! However, there is also the suggestion to make the longitudinal spot spacing a parameter in the pln structure for easy customization along with the bixelwidth. @becker89 is there anything speaking against such an approach?!

**Comment by markbangert** [comment]
@ahmadnish this can also be something for you. make the longitudinal spot spacing an optional parameter for the generateStf function

**Comment by markbangert** [comment]
This has been solved in pull request https://github.com/e0404/matRad/pull/265.
