### ISSUE TITLE
DMLC leaf sequencer

### ISSUE THREAD

**Issue by pheasant75** [e0404/matRad#171]
Wondering when will this software support DMLC leaf sequencing.

**Comment by markbangert** [comment]
Hi Pheasant... thanks for getting in touch. At the moment we do not have this very high in our agenda. Do you know a well documented algorithm that we could implement?

**Comment by pheasant75** [comment]
No. I was just aware of the basic principle from S. Webb's book.

**Comment by markbangert** [comment]
Alright. As I said photon developments are not so high on the list at the
moment. I will keep this issue open so we do not forget about your
suggestion. In case you want to go ahead and implement things yourself let
us know if you need any help from the developer team...

Am 05.07.2017 5:46 nachm. schrieb "pheasant75" <notifications@github.com>:

**Comment by pheasant75** [comment]
I wrote a basic function to convert a fluence map to mlc control points.
The following plot shows the trajectory of one pair of leaf and the fluence
it try to reconstruct.  Not sure how to incorporate it into the matRad.
Looks like D_k in the engeLeafSequencing.m is the fluence map?
And sequencing.beam(i).numOfShapes will be the number of control points and
shapesWeight will be MU for that snap shot (rather than the cumulative MU
in treatment plan)?

**Comment by markbangert** [comment]
Yeah in principle you could use one of the existing MLC sequencing functions to extract the fluence maps. I figure for DMLC sequencing you do not want to work with stratified fluence matrices so you may want to use the variable "fluenceMx" as defined in https://github.com/e0404/matRad/blob/master/matRad_engelLeafSequencing.m#L94 as a basis. From there you might be able to do your magic with the computation of the leaf trajectories, at some point, however, you will need to translate things back into the fluenceMx space as also exercised with the other MLC seqeuncers in matRad as we go back to the dose influence matrices to calculate the final dose.

Cheers!

PS Didnt see a plot... ;)

**Comment by markbangert** [comment]
And btw: May I ask where you are working at? If you do not want to disclose your identity here on github you can always email us... For us it is always nice to know where people are using our software - also because it helps us make the case for continued funding of this project ;)
