### ISSUE TITLE
ipopt not supported with octave alone

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#178]
If you want to run ipopt mex files with octave, then you have the issue that it will direct to matlabs libraries to solve the linear problem because the mex files have been compiled with matlab. while this is fine if you have matlab installed on your system (it wont even require a license) it is a show stopper if you only have octave. consequently, we need to compile the entire mex file from octave in order to provide a true open source solution.

Thanks @burigolucas for pointing this out!

**Comment by wahln** [comment]
does it work with only the run-time installed?

**Comment by markbangert** [comment]
I dont think so but I have not checked... @burigolucas do you know?
