### ISSUE TITLE
could not find HLUT GE MEDICAL SYSTEM-Light speed

### ISSUE THREAD

**Issue by hamzaustc** [e0404/matRad#179]
![hlut issue](https://user-images.githubusercontent.com/28702398/30098412-6aece4ce-9314-11e7-8701-5f1524390e22.PNG)
How to overcome this issue?

**Comment by becker89** [comment]
Hi @hamzaustc, this warning pops up when the Dicom Import could not find the corresponding HLUT table. Instead a default HLUT table located in matRadRootDirectory/dicomImport/hlutLibrary was used. This warning disappears if you provide the correct HLUT table on your own. Just copy the the default HLUT table in matRadRootDirectory/dicomImport/hlutLibrary and rename it to GE MEDICAL SYSTEMS-LightSpeedRT16-ConvolutionKernel-STANDARD.hlut    and fill in the lookup table from your machine - the CT the images have been generated with - to correctly convert hounsfield units to electron density (photons) or stopping power relative to water (particles)

**Comment by markbangert** [comment]
Hi Adam, could you let us know if we can close this issue? Have you been able to resolve your problems with the Hounsfiled lookup table? cheers, Mark

**Comment by adam10514** [comment]
I had the same problem, but "click ok" you can save the ".mat file",and you can load this file to Calc. influence and Optimize.
I think this problem affects the outcome, but it does not affect the flow of execution.

Best Regards, Adam
**sorry my English it's not good QuQ

**Comment by hamzaustc** [comment]
Yes, please close this issue. Thank you very much
