### ISSUE TITLE
How to set the other beams in matRad

### ISSUE THREAD

**Issue by adam10514** [e0404/matRad#181]
![image](https://user-images.githubusercontent.com/31431366/30313270-53c85c78-97cf-11e7-9d08-c8cdf6750e55.png)
it just have one beam, i don't know how to set the other beams..

Best Regards, Adam

**Comment by becker89** [comment]
Just enter a white space followed by another angle. Keep in mind that the number of gantry angles must equal the number of couch angles. For example you could enter: 0 90 as gantry angles and 0 0 as couch angles. Moreover, are you familiar with the colon operator in Matlab ? 0:72:359   Would create 5 beam angles equally spaced in 72 degree steps from 0 to 360 degrees. An example is available in the https://github.com/e0404/matRad/blob/master/matRad.m   in Line 32 and 33

**Comment by adam10514** [comment]
thanks becker89
the matRad can input RTPlan.dicom, but the information of beam angle not in GUI
how can I do?

Best Regards, Adam

**Comment by becker89** [comment]
Hi Adam,
when performing the DICOM import have you also selected the RTplan file for the import. ?  During the import there is a dedicated box labeled RT plan. Make sure to select a plan file. If you did, then it might be good to check what went wrong during the import. I don't know how familiar you are with Matlab, but you can define a Breakpoint here : https://github.com/e0404/matRad/blob/c3705a2223c8dc7f1103cf36442a043f21f781c9/dicomImport/matRad_importDicomRTPlan.m#L131  and re-run the dicom import. You will find out if the plan import was capable of parsing the beam and gantry angles. Hope this helps. Finally, I also have to say that we did not test the matRad plan import for all vendors. So it would be helpful for us to see what went wrong.

**Comment by markbangert** [comment]
Hi @adam10514 can we close this issue?
