### ISSUE TITLE
VMAT/DMLC implementation

### ISSUE THREAD

**Issue by zizipha** [e0404/matRad#185]
Since I am unable to join in online. I was wondering if there can be a script for DAO implementation for VMAT, IMAT or dynamic MLC? Specifically, creating and distributing the Control points for dynamic MLCs.

**Comment by markbangert** [comment]
hi zizipha.... we are back online - if you still want to discuss in person. it was dinner time in germany ;) otherwise I am going to answer later right here!

**Comment by markbangert** [comment]
I am sorry it did not work out for you yesterday to join us online. Here is the answer....

A proper implementation for VMAT cannot simply be achieved by a script that would organize the arc sequencing step to initialize the DAO with one shape per control point. It is also necessary to accomodate machine constraints emerging e.g. from the limited leave speed. This requires more deep changes of the code.

I hope this answers your question. If not, please let me know!

Also, I would like to share with you that at the moment there are people around @eric11210 are working on a VMAT implementation based on matRad's DAO code. We plan to have a first implementation online within a development branch towards the end of the year. If you send me your email adress to matrad@dkfz.de I can include you in our newsletter so you do not miss this.

Cheers / Mark

**Comment by spitzbubchen** [comment]
Curious if there has been any progress on the VMAT front...?

**Comment by markbangert** [comment]
Yeah, we're on it. The current status is online at https://github.com/e0404/matRad/tree/dev_VMAT. At the moment everybody is busy with other stuff (grant deadline, ESTRO upcoming, thesis writing... the usual) so I am afraid there wont be much progress until mid April. However, you are invited to start beta-testing yourself; there should be a working example in the "examples" folder showing how to run a VMAT plan..

**Comment by spitzbubchen** [comment]
Thanks! I'll give it a go.

**Comment by robustedu** [comment]
Hello,

Learning a lots from Matrad's coding and its style. Thanks. I'm new to VMAT.

1. What algorithm is implemented in VMAT codes? Is it the following one?

Wild, E., Bangert, M., Nill, S., & Oelfke, U. (2015). Noncoplanar VMAT for nasopharyngeal tumors: Plan quality versus treatment time.

2. It seems to me that leaf speed constraint is not imposed in optimization of \matRad-dev_VMAT\matRad_directApertureOptimization.m. Am I right?

Thank you!
XM

**Comment by eric11210** [comment]
Hi robustedu, I can answer your questions.

1. We pulled from a number of sources for our VMAT implementation, but the primary one was the following: "Bzdusek K, Friberger H, Eriksson K, H°ardemark B, Robinson D & Kaus 456 M 2009 Medical Physics 457 36(6), 2328–2339."

2. Leaf speed is constrained.  In the function optimization/matRad_daoConstFunc.m, starting on line 62 there is code that is specific for VMAT, where we define the leaf speed and dose rate constraints.  The specific values of the constraints can be changed in photons_Generic.mat. Let me know if you need help finding where to change things.

Eric

**Comment by markbangert** [comment]
Thanks for your clarification, Eric. I am on annual leave currently and a little behind with attending to matrad's GitHub page...

@robustedu should we leave this issue open, or can I close it again? In case you have more questions we can always open it again or you file a new issue...

**Comment by robustedu** [comment]
Thank you very much both of your answers! Very help! I am now reading the algorithm and will have more questions to ask for help. Please leave this issue open.

Best,
XM

**Comment by spitzbubchen** [comment]
Looking at your code it seems that the method does not use aperture interpolation where one starts with a coarse sampling and then adds in new apertures until a fine gantry angle spacing is achieved (usually about 2deg). I believe Otto, Bzdusek, and most other methods of VMAT use interpolation. Your code instead starts with a fine 2 deg spacing from the very beginning. Is this approach valid for VMAT as I thought the point of interpolation was to help avoid local minima?

Curious as to what type of computer your running your example on? On my desktop I have to limit the number of gantry angles to about 20 otherwise I run into memory issues. Are you using a cluster?

**Comment by eric11210** [comment]
Our approach optimizes apertures at an angular resolution specified by pln.propOpt.VMAToptions.maxDAOGantryAngleSpacing. At every iteration of the DAO algorithm, apertures are interpolated to the resolution specified by pln.propOpt.VMAToptions.maxGantryAngleSpacing.  In the example, these are set to 4 degrees and 2 degrees, respectively.  This approach is closest to Bzdusek's, where they use 8 degrees and 4 degrees, respectively (from what I understand, they did not start out with a coarser angular spacing - that was done by Otto, as you said).

Our values of 4 and 2 degrees were determined by our internal testing - in particular, the 2 degree value for pln.propOpt.VMAToptions.maxGantryAngleSpacing was required to achieve a certain dose calculation accuracy in the HEAD_AND_NECK case.  You are certainly free to change those values.

I am running my examples on a workstation with 64 GB of RAM - you will need a similar amount of memory to use a maxGantryAngleSpacing of 2 degrees. @markbangert, maybe we should change these values to something more reasonable?

**Comment by zizipha** [comment]
Hi all,

To follow up with what '@spitzbubchen' mentioned, I also ran into memory
issues even running this on a cluster using the default 4 and 2 degrees
angular spacing and resolution.

I find Otto's VMAT approach of aperture interpolation from coarse to fine
control point sampling to be robust as it is quicker and requires less
memory. Wondering if similar technique could be used?

Now to my question, could one run multiple partial arcs as opposed to a
single full arc in matRad? Also, any ability to use variabledose rates
during the optimization?

Less I forget, Thank you guys for updating the code.


Regards,
