### ISSUE TITLE
ZP in cst-file included but no voxels assigned

### ISSUE THREAD

**Issue by johannawinter** [e0404/matRad#189]
During the dicom import, the target point (ZP) was included in the cst-file as a contour but there were no voxels assigned to it: cst(i,4) = [ ]. This resulted in an error in matRad_indicatorWrapper during assigning the quality indicators.

**Comment by markbangert** [comment]
@wahln should we resolve this in the import or the quality indicator calculation? what do you think?

**Comment by johannawinter** [comment]
Strangely no problems occur for 'CT-Referenzpunkt' which also has no voxels assigned to. This is located in the first row of the cst-file, 'ZP' in the last. Is it possible that the combination of last row and empty array results in the problem for calculating the quality indicator?

**Comment by markbangert** [comment]
@johannawinter can you send me the data to reproduce this errror? then I can have a look!

**Comment by johannawinter** [comment]
I think I could fix it.
It is addressed in https://github.com/e0404/matRad/pull/218

**Comment by markbangert** [comment]
I just saw your pull request! Thanks. I agree. It looks like you solved this issue. I will review and merge!
