### ISSUE TITLE
Inconsistencies in delineation of HEAD_AND_NECK data set

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#190]
The segmentations of the PTV63 and PTV56 have strange overlap, alsoPTV is poppoing up on one slice and disappearing on the next slice just to appear again in the next slice... And there is a ring structure for a PTV on one slice.

This issue can potentially be resolved in combination with providing HU values for the example cases?!

**Comment by becker89** [comment]
@markbangert this was solved right ?

**Comment by markbangert** [comment]
Yes. Thanks for the heads up!
