### ISSUE TITLE
DVH /QI computation & visualization sucks in current implementation

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#195]
Talking to @johannawinter I realized that the current implementation of the DVH computation is really highly inconvenient and this has (partly) to do with the fact that relevant information is stored in the cst. Given multiple dose cubes users would have to administrate this information additionally in the corresponding column in the cst - which does not make sense. I also think it is highly questionable that we have everything precomputed for visualization! Especially n the GUI this does not make sense as we do not know if the information in the cst is outdated or not. Why not calculate things on the fly based on a 3D cube and segmentation? Why not modularize/separate QI calculation and visualization from DVH calcualtion and visualization?!

**Comment by becker89** [comment]
I think this change was introduced by @Haydnspass and me and was intented to make things easier for the report generation when considering e.g. more than 100 scenarios. The original idea was to store the DVH and QIs for each individual scenario to create later on more sophistacited DVHs (e.g. confidence bounds). For instance, having 9 scenario doses available resultGUI.RBExD_1 ....resultGUI>RBExD_9 would result in in 9 dvhs and 9 QI sets. 
I think one of the main problem here is how we store multiple results and what exactly are "multiple results' - either multiple resultsGUI structs or in multiple subfields as part of one resultGUI. I think a resultGUI struct belongs to one set of weights. I can have different recalculation which are stored in multiple subfields. On the other hand I can have two different optimizations which should ideally be stored in two seperate resultGUI structs. 
I am also big fan of modularizing QI and DVH calculation from their visulation, which is partly already done. But the question is when we decouple calculation from visualization how do we pass on the calculated information? Right now we are using the eighth cst column, which is I have to admit not elegant. I agree with you Mark that it would be best if we modularize and nest functions to avoid any precomputaion, for instance plotDVH -> calcDVHmultiScen or calcDVHmultOpt -> calcDVH then we do not store anything in the cst.  plotDVH could distinguish if we want to plot multiple scenario or multiple optimizations.  In addition, we should take the visulation of the QI out of the DVH visualisation and build a similar calling pipeline showQI ->calcQImultiScen or calcQImultOpt -> calcQI.

**Comment by markbangert** [comment]
has been solved in https://github.com/e0404/matRad/pull/208
