### ISSUE TITLE
Iso center marker too small

### ISSUE THREAD

**Issue by johannawinter** [e0404/matRad#205]
It seems like the iso center marker depends on the CT resolution. This results in a too small marker if the resolution is 1 mm. You cannot distinguish if the arrow is pointing up or down.

**Comment by wahln** [comment]
yes, seems like I forgot to normalize the length of the marker lines in matRad_plotIsoCenterMarker.m with the ct resolution. Should be easy to fix.

**Comment by markbangert** [comment]
@johannawinter can you maybe fix this yourself and make a pull request... ?  ;)

**Comment by markbangert** [comment]
Fixed in https://github.com/e0404/matRad/pull/207
