### ISSUE TITLE
beam doses in resultGUI

### ISSUE THREAD

**Issue by silkeulrich** [e0404/matRad#237]
In resultGUI all beam doses are stored, e.g. resultGUI.physicalDose_beam3. If a new plan is calculated for less beams (e.g. only 2), the beam doses for beam 3,4, etc. are not deleted

**Comment by becker89** [comment]
Hi Silke, this issue affects matradGUI.m right ?

**Comment by becker89** [comment]
@silkeulrich did we solved this issue ?

**Comment by silkeulrich** [comment]
yes, it was solved

**Comment by markbangert** [comment]
Supergut.
