### ISSUE TITLE
current function description / comment layout is unfortunate for display with MATLAB's help command

### ISSUE THREAD

**Issue by wahln** [e0404/matRad#250]
This is a really small issue, but I wanted to state it anyway

In the current layout we chose for function descriptions, the first comment line is filled with "%" signs, i.e.,``% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%``
This is problematic if you run MATLAB's `help` command on a subfolder (just try to type `help optimization` from the matRad base folder, for example, and you will see the problem.

It's a really small issue, and maybe we should remove the first comment line and directly start with a short function description? 
While we may not use MATLAB's help often on a subfolder, people who are just getting started with matRad might.

**Comment by markbangert** [comment]
Has been addressed with https://github.com/e0404/matRad/commit/f1b9461c78f97ef7f700c3c52d8bc873f9c8bbfe
