### ISSUE TITLE
matRad parallelization

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#254]
Considering the increased use of matRad within our department we definetly need a solution to run matRad on dkfz's open stack archiecture the sooner the better.

**Comment by becker89** [comment]
What use case do you have in mind? Right now, we have an parallel implementation to sample dose based on optimized weights https://github.com/e0404/matRad/blob/dev_varRBErobOpt/matRad_sampling.m      But we do no have a parallel dose influence calc over multiple scenarios.

**Comment by markbangert** [comment]
I was not so much referring to making matRad run parallel but to set up an
infrastructure within our department that people can use based on the open
stack architecture!

On Tue, Mar 13, 2018 at 5:16 PM, Hans-Peter Wieser <notifications@github.com

**Comment by czhiling** [comment]
We are interested in running matRad on open stack. 
What's your purpose to run matRad on open stack? Just for providing matlab + matRad environment for colleagues or there are some performance benefits?

**Comment by markbangert** [comment]
originally we just wanted to provide matrad for coleagues but by now we are
also interested to run Monte Carlo dose calculations there with an
interface to matRad, i.e. matrad is runnning on your local machine and then
you deploy a dose calculation job using e.g. TOPAS to openstack...
