### ISSUE TITLE
dose influence matrix unit

### ISSUE THREAD

**Issue by pinardursun** [e0404/matRad#257]
Hi, what is unit of dose influence matrix? Gy per MU or Gy per 100 MU. 
Thanks

**Comment by markbangert** [comment]
There is no established normalization of photon fluence in matRad at the moment. However you can do so very fast yourself. Just simulate a rectangular field (e.g. 10x10cm²) and use some reference value e.g. in 10cm depth to renormalize your weight vector accordingly...

**Comment by pinardursun** [comment]
Thank you for quick reply. 
But, I am sorry, I could not get the idea. Do I need to do this simulation using phantom etc. Or, can I directly do using the d_ij matrices that matRad provide me and my ct scans? I am not from physics area, and I just want to extract data to use in an VMAT optimization algorithm..
Pınar

**Comment by markbangert** [comment]
Hi Pinar,

the normalization to MU is usually done by relating the dose at a point
within a water phantom to a specific fluence

E.g. you can say that you have 100MU when the dose at a point in 10cm depth
on the central ray equals 1Gy when irradiated with a 10x10cm² field.

If you now want to have some MU calibration you have to run such a
simulation (i.e. 10x10cm² field) and determine the fluence weight that will
give you 1Gy in 10cm depth. And then you have the linear conversion factor
that you need or in other words you can compute how many Gy you have at
what weight.

Cheers / Mark

**Comment by pinardursun** [comment]
Hi  Mark, 
Thank you so much for explanation. I am working on this simulation that you have advises to me.

I use "BOXPHANTOM" data set and obtained dij matrices for gantry angle 0. Then, I determine the voxel in 10 cm depth on the central ray. I sum all dij  values corresponding 10x10cm² field and the sum was about 0.92. Let me ask my first simple question: Can I assume that 92 MU radiation is delivered at gantry angle 0? Thus, can I divide my all dij matrice by 92 to obtain Gy/MU values?

My other question is that do I need to do this simulation for all gantry angles? Also, do I need to do this simulation for all other data sets? Or 1/92 is my only linear conversion factor for MatRad?

Kind regards, 
Pınar

**Comment by markbangert** [comment]
Hi Pinar,

if you use the Boxphantom and a beam at 0° then your reference conditions
relate to a 75mm x 75mm field. Note that your normalization relates to this
field size; if you would simulate a smaller(bigger) field you would have
less(more) scattering contributions on the central ray.

If you now have a dose of 0.92 in the very voxel you want to consider at
unit fluence then I would do the following:

At w = 1/0.92 you have one Gy in your very voxel under consideration, so I
would say that you introduce a normalization of 100MU corresponding to
1/0.92 in fluence weight.

Now you can recompute all weights to MU with this scaling! You do not have
to recompute everything for every gantry angle. Your normalization globally
corresponds to 100MU (i.e. 1/0.92) delivering 1 Gy in 10cm depth on the
central ray for a 75mm^2 field.

I hope this solves your problem. Let me know if we can close this issue.

**Comment by pinardursun** [comment]
Hi Mark, 

I have already changed the BODY structure from OAR to target in BOXPHANTOM and calculate dij matrice. Thus the size of the field was 275mm^2. But I only consider the 100mm^2 field around central ray and get the fluence which is around 0.92. 

Thank you again for your help. I think now I have reasonable values and the problem is solved. 

Kind regards,
Pınar
