### ISSUE TITLE
Possible bug in matRad_fluenceOptimization.m

### ISSUE THREAD

**Issue by dsparcerisa** [e0404/matRad#261]
In line 173 of matRad_fluenceOptimization.m (of current dev_varRBErobOpt branch), a parameter called maxCurrRBE is calculated using the following formula:

maxCurrRBE = max(-cst{ixTarget,5}.alphaX + sqrt(cst{ixTarget,5}.alphaX^2 + ...
                        4*cst{ixTarget,5}.betaX.*CurrEffectTarget)./(2*cst{ixTarget,5}.betaX*(dij.physicalDose{1}(V,:)*wOnes)));

When using variable optimization (McNamara model) with the HEAD_AND_NECK.mat phantom, this line produces a +Inf value, which in turn causes errors in the optimization with IPOPT.

Doing dimensional analysis of this formula, we believe that there might be a parenthesis missing. However, adding the parenthesis does not solve the -Inf problem, so these two things might or might not be related. Can you take a look at this please?

**Comment by dsparcerisa** [comment]
Unsure how related with this error, we find that when running matRad_fluenceOptimization with the HEAD_AND_NECK.mat example and McNamara model, matRad_gradFuncWrapper.m produces a gradient vector 'g' full of NaNs (L220 onwards).

**Comment by markbangert** [comment]
Do you know where the inf is coming in? basically there are three options...

1. Is betaX zero?
2. is the dose for one of the voxels V zero?
3. is CurrEffectTarget inf somewhere? --> this would point towards an error in the alpha and beta matrices

probably the most likely cause and also a potential explanation for the issue with the gradient!

**Comment by dsparcerisa** [comment]
Two comments. Regarding the parenthesis from L173, it's probably missing, dimensionally should be something like maxCurrRBE = max(**(**-cst{ixTarget,5}.alphaX + sqrt(cst{ixTarget,5}.alphaX^2 + ...
4cst{ixTarget,5}.betaX.CurrEffectTarget)**)**./(2cst{ixTarget,5}.betaX(dij.physicalDose{1}(V,:)*wOnes)));

And about the Inf, it is coming from CurrEffectTarget, in particular from dij.mAlphaDose and dij.mSqrtBetaDose, which have both 488 NaNs when multiplied by wOnes. I will look at the bioModel and make sure that no zeros/infs appear in alpha, beta, or ABratios.

**Comment by dsparcerisa** [comment]
Thanks Hans-Peter. We stopped updating dev_varRBErobOpt a couple months ago
because new versions would sometimes interfere with our code, so we decided
to update our matRad every few months rather than in every commit. We will
download the updated protons_Generic.mat and see if it solves the problem.
From what I could see yesterday, I believe it will.

2018-04-04 11:21 GMT+02:00 Hans-Peter Wieser <notifications@github.com>:

**Comment by becker89** [comment]
Alright - then as you said just download the current protons_Generic.mat from dev_varRBErobOpt and let me know if it works :-)

**Comment by MLopezAguirre** [comment]
Thanks for your time. We have updated to the latest version of dev_varRBErobOpt  and we still have the same problems. We have also tried to work with only the current version of dev_varRBErobOpt.
We are working with this setting: 
Phantom: Head and Neck
Radiation: Protons
Model: MCN (RBExD)

**Comment by becker89** [comment]
Ok thanks for the update - I will look into it

**Comment by becker89** [comment]
We have one or two Inf values in the LET of the base data set which is causing this issue. I will push an update soon.

**Comment by becker89** [comment]
Alright, there were actually two issues. The first one is, that there was a single Inf LET value in the second beam energy in the base data. Secondly, before dose calculation we initialise a alpha_x vector with zeros and fill it VOI-wise. This alpha_x vector holds then for each voxel the LQM alpha parameter for photons. The problem was that we only fill this vector with values if the voxel belongs to a VOI for which a objective function is defined. For the head and neck case we had voxels which belonged to VOIs for which no objective function was defined (some less important OARs). This resulted in alpha_x values of 0 in these voxels. Which caused in a further step nan values in the corresponding alpha_proton values when applying a variable RBE model. I have updated the code. Could you double check once again if it works now ?

**Comment by MLopezAguirre** [comment]
Everything works correctly.  Thank you very much !!!
If we find any other error we will contact you again

**Comment by becker89** [comment]
Thanks for the feedback and yes if you reveal\find another issue then it would be great for us if your share it 👍 I will close this issue now.

**Comment by markbangert** [comment]
@becker89 this might also be an issue in the conventional branch, right? could you make a pull request with the new base data file and the changes to the alphaX/betaX initialization to the dev branch so I can quickly review an merge?

**Comment by markbangert** [comment]
Or is this not necessary?

**Comment by becker89** [comment]
Yes this code change should also be included in the dev_branch. I will make a pull request later/tomorrow.

**Comment by becker89** [comment]
The updated proton base data set is already part of the dev branch. Regarding alphaX/betaX, we do not create and fill alpha_x and beta_x vectors in the dose calculation in the dev branch. They are created during calcCubes after the fluence optimization.  But in dev_varRBErobOpt we do resolve overlap priorities and then create a alphaX/betaX vectors, as we need to derive alpha_p and beta_p. This means that if a users changes the overlap priorities or the tissue type then a full dose recalculation is required.
