### ISSUE TITLE
Problems with DICOM import

### ISSUE THREAD

**Issue by anihol** [e0404/matRad#277]
Hi,
When importing a pt in dicom format (from eclipse) I have some problems. 

First when finding the right directory and selecting the CT, RT, dose and plan I get a warning, saying "no rt dose directly associated to the plan file. showing all rt dose files." 

I then choose the dose, I know it is the correct one, and start importing. It can import the CT and RT correctly. When it has finished generating the cst I get these errors:
--------------------------------------------------------------------------------------------------
Error using  * 
Inner matrix dimensions must agree.

Error in matRad_importDicomSteeringParticles (line 159)
        temporarySteering = [temporarySteering; c1_help c2_help ...

Error in matRad_importDicom (line 122)
            [stf, pln] = matRad_importDicomSteeringParticles(ct, pln, files.rtplan);

Error in matRad_importDicomGUI>import_button_Callback (line 330)
matRad_importDicom(files, dicomMetaBool);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRad_importDicomGUI (line 53)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)matRad_importDicomGUI('import_button_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating UIControl Callback
------------------------------------------------------------------------------------------------------------

I think you have seen this before, there is another issue on this, but I cannot see the answer.

I would like to use your program, and expand it, to calculate LET and RBE, using different models, thus it is not enough getting the dose I also need the correct proton spots.

Hope you an help me
Regards Anne Holm

Medical Phycisict
Aarhus University Hospital
Dk

**Comment by markbangert** [comment]
Hi Anne and thanks for getting on touch with your DICOM import issue.

The particle plan import for pencil beam scanning is pretty much tailored to our clinical setup. This is why you also need to choose the corresponding base data, as the pencil beam energies in your DICOM plan need to be part of the associated base data file - I assume you simply pick the generic base data provided be matRad? This will necessarily lead to some error as you are probably working with a different library of pencil beam energies in Eclipse than in matRad. I am somewhat surprised that you did not get an error earlier...

If you want to import the Plan including the entire beam steering, you will need to hack your own, consistent base data set in matRad. There is some information on how to do that in our Wiki at https://github.com/e0404/matRad/wiki/Particle-Base-Data-File.

Please let us know if you have any more questions or if you need additional directions to get particle plans into matrad.

Kind regards / Mark
