### ISSUE TITLE
Problem when using imported dicom data

### ISSUE THREAD

**Issue by klinge-th** [e0404/matRad#28]
when trying to load the imported data with the matRadGUI you will get an error in line 612 of _matRadGUI.m_ because  _slice_ is NaN.
```matlab
ct_rgb = ind2rgb(uint8(63*squeeze(ct.cube(:,:,slice))/max(ct.cube(:))),bone);
```
This is ultimately caused by the function _matRad_getIsoCenter.m_ (line 55-59).
```matlab
for i=1:size(cst,1)
    if isequal(cst{i,3},'TARGET') && ~isempty(cst{i,6})
        V = [V;cst{i,4}];
    end
end
```
 Here the target indices are stored in the variable _V_. One requirement for this is, that the field _cst{i,6}_ is not empty. (here the dose objectives and parameters are stored, see [cst](https://github.com/e0404/matRad/wiki/The-cst-cell)).
But after the import this field is by default empty, see last line (_matRad_createCst.m_):
```matlab
for i = 1:size(structures,2)
    cst{i,1} = i - 1; % first organ has number 0    
    cst{i,2} = structures(i).structName;
    
    if ~isempty(regexpi(cst{i,2},'tv')) || ...
       ~isempty(regexpi(cst{i,2},'target')) || ...
       ~isempty(regexpi(cst{i,2},'gtv')) || ...
       ~isempty(regexpi(cst{i,2},'ctv')) || ...
       ~isempty(regexpi(cst{i,2},'ptv')) || ...
       ~isempty(regexpi(cst{i,2},'boost')) || ...
       ~isempty(regexpi(cst{i,2},'tumor'))
        cst{i,3} = 'TARGET';
    else
        cst{i,3} = 'OAR';
    end
    
    cst{i,4} = structures(i).indices;
    cst{i,5}.Priority = 1; % set dummy priority but no biology parameters
    cst{i,6} = []; % define no dummy objcetives    
end
```

As the function _matRad_getIsoCenter.m_ simply returns _NaN_ for the isocenter, it is not directly clear why there is a problem with the data set...

maybe one should think about including dummy values in _cst{i,6}_ for the import or ask the user to specify at least one VOI that should be a target volume for which this field is filled.
Also maybe there should be an error message in case the isocenter values are _NaN_

I think for now the only way around this is to fill the field _cst{1,6}_ by hand...

**Comment by markbangert** [comment]
I think we should set the default slice in matRadGUI _not_ to the iso center which can only be calculated once important treatment planning decisions (definition of target volumes including objectives) have been made. It is better to set them to ceil(size(ct.cube,X)/2)...

**Comment by klinge-th** [comment]
I think that's a good idea.
However I think we also need to set the _Calculate Dij_-button inactive until the field _cst{i,6}_ is filled. Otherwise the recalculation of the isocenter will still yield _NaN_ and the calculation of the _stf_ will fail...

**Comment by becker89** [comment]
I'm on it and will integrate several other minor updates regarding the GUI in a commit tonight.
Yes - we could disable the calculate dij-button until one VOI is defined as target.

**Comment by markbangert** [comment]
Thanks Hans-Peter for taking care of this!

While you are making the changes could you alo include an error message in calcIsocenter in case no target voxels are found....

Thanks / Mark

**Comment by klinge-th** [comment]
Thanks!
 @becker89 : Just one more thing (not regarding this problem), will you also update the sequencing process in the GUI? i.e. to actually use the new weighting factors to recalculate the dose (as it is done in the script)?

**Comment by markbangert** [comment]
@becker89 has this issue been resolved completely and can be closed?

**Comment by becker89** [comment]
this issue can be closed - it is already integrated in the master branch
