### ISSUE TITLE
Binary NRRD export of DICOM imported data

### ISSUE THREAD

**Issue by sebastianuber** [e0404/matRad#281]
Hello,

when I imported the CT and structure set via DICOM and tried to export it with the binary NRRD export I got the following error;

Reference to non-existent field 'cube'.

Error in matRad_exportGUI>btn_export_Callback (line 413)

    matRad_writeCube(fullfile(exportDir,['CT_ED' extension]),ct.cube{1},'double',metadata);

Error in gui_mainfcn (line 95)

        feval(varargin{:});

Error in matRad_exportGUI (line 55)

    gui_mainfcn(gui_State, varargin{:});

Error in

matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRad_exportGUI('btn_export_Callback',hObject,eventdata,guidata(hObject))

Error while evaluating UIControl Callback

It seems that the DICOM import doesn’t set ct.cube{1}. I added  interpCt.cube{1} = interp3(Y,X,Z,double(origCt),Yq,Xq,Zq); to line 81 in matRad_interpDicomCtCube.m. This fixes the binary export but produces an error with the binary import later on (memory overflow error).

Kind regards,
Sebastian Uber
MSc Student Oncoray Dresden

**Comment by wahln** [comment]
Pull request #288 should fix this issue now by only trying an export of cube and cubeHU after checking if they are actually available
