### ISSUE TITLE
Initial sigma of double Gauss

### ISSUE THREAD

**Issue by Phoebegit** [e0404/matRad#286]
Hi,
   In matRad_calcParticleDoseBixel.m, When computing lateral sigmas of **double Gauss**,Is it ok to use the **same** sigmaIni_sq?
In our MC data,Sigma2 is about twice that of sigma1 and the Initial sigmas are different obviously.

`if ~isfield(baseData,'sigma')`
 
    % interpolate depth dose, sigmas, and weights    
    X = matRad_interp1(depths,[conversionFactor*baseData.Z baseData.sigma1 baseData.weight baseData.sigma2],radDepths);`

    
    % set dose for query > tabulated depth dose values to zero
    X(radDepths > max(depths),1) = 0;
        
    % compute lateral sigmas
    sigmaSq_Narr = X(:,2).^2 + sigmaIni_sq;
    sigmaSq_Bro  = X(:,4).^2 + sigmaIni_sq;`

**Comment by markbangert** [comment]
Hi Phoebegit,

we use the same initial sigma. We assume that we can describe the broadening in air with the initial sigma only and therefore we only use one compenent. When we go into the patient, we then use two components. In order for this approach to make sense you will need to separate scattering within the patient from scattering in air within the base data. I.e., X(:,2) will be zero for a radiological depth z_rad=0!

cheers / Mark

**Comment by markbangert** [comment]
I am not sure if I am following....

Basically we assume a perfect delta peak of fluence for sigma1 and sigma2, i.e. at depth=0 we have sigma1=sigma2=0. to compute the effective sigma1 and sigma2 also considering broadening in air we add this in quadrature

sigma1/2_eff = sqrt(sigma1/2^2 + sigma_ini^2)

that way we completely decouple broadening in air from the broadening in the patient.

does this help elucidate your confusion?

**Comment by Phoebegit** [comment]
So , If I want to establish base data about our own machine, I have to compute sigma1/2;
We get sigma1/sigma2 by fitting MC data or measurement data,Is this the effective sigma1/2 you mentioned? 
if Yes ,sigma1/2^2=sigma1/2_eff^2-sigma_ini^2=sigma1/2_MC^2-sigma_ini^2?

**Comment by markbangert** [comment]
yes that is the way we do it! let me know if I can close this issue!
