### ISSUE TITLE
Problem at "Open 3D-View" when ct has difference x and y cube dimensions.

### ISSUE THREAD

**Issue by robustedu** [e0404/matRad#302]
Hello,

Current ct examples all have the same numbers in the first two elements of ct.cubeDim.

When
1. load cst and ct with the difference numbers in the first two elements of ct.cubeDim, 
2. run matRadGUI and click "Open 3D-View"

It shows

Error using isosurface (line 75)
The size of X must match the size of V or the number of columns of V.

Error in matRad_computeAllVoiSurfaces (line 27)
`        isoSurface = isosurface(xMesh,yMesh,zMesh,v,0.5);`

Error in matRadGUI>Update3DView (line 1305)
`    cst = matRad_computeAllVoiSurfaces(ct,cst);`

Error in matRadGUI>UpdatePlot (line 1257)
`Update3DView(handles);`

Thank you very much!
Best,

**Comment by markbangert** [comment]
Thanks for reporting this bug. Could you please check the fix I just submittted via this pull request --> https://github.com/e0404/matRad/pull/303

**Comment by markbangert** [comment]
@robustedu , I just pushed another commit to the pull request that hopefully resolves all issues related to the 3dviwer. please could you also check with your data, before I merge?

Cou can find all changes here https://github.com/e0404/matRad/pull/303/commits/8d8396c839e9e382495cb1773782d611d978aeb2

Cheers / Mark

**Comment by markbangert** [comment]
Has been solved with https://github.com/e0404/matRad/commit/8d8396c839e9e382495cb1773782d611d978aeb2.
