### ISSUE TITLE
DICOM Import Example

### ISSUE THREAD

**Issue by nour-ramadan** [e0404/matRad#304]
Hello,

I'd like to try out the DICOM import but I couldn't follow what the DICOM information has to be in order to be imported, I tried several DICOM files and it failed (they didn't have structure files though, only CT slices), I tried to go through the code to determine what exactly a DICOM file should look like, but it's too overwhelming.
I'd appreciate it if you could provide some DICOM files examples.
Thanks,

**Comment by markbangert** [comment]
Hi, we usually do not run an import without structures as these are required to do any planning in matRad. You could eg use CERR to view the CT only in Matlab I think.

matRad works with the data present at http://www.daten.strahlentherapie.uni-wuerzburg.de/quasimodo.html - I just double checked with the structures for OTP/Masterplan Pinnacle.

If you do not manage to translate the page you can use the following direct links:

CT http://www.daten.strahlentherapie.uni-wuerzburg.de/Daten/Quasimodo/Quasimodo.zip
RTSS http://www.daten.strahlentherapie.uni-wuerzburg.de/Daten/Quasimodo/RS1.3.6.1.4.1.2452.6.120060512.20736.311.101211283.dcm

Please let me know if I can close this issue!

**Comment by nour-ramadan** [comment]
That worked well.
You may close the issue though.
Thank you so much.
