### ISSUE TITLE
prescription dose & calculation dose

### ISSUE THREAD

**Issue by Phoebegit** [e0404/matRad#307]
hello,
    Recently, I try to figure out the influence of the beam quality on dose distribution,and I intend to using the DVH as the criteria. But I find it is hard to let the dose distribution   meet the prescription dose,for example,if I set the  >95% volume ,> 2Gy for target objective function,the calculated dose distribution will not reach this . there is a picture shows this.
![image](https://user-images.githubusercontent.com/31639780/48948472-8ebd9e80-ef6f-11e8-87fc-b9c24d729e07.png)

 According to the data,the prescription of D_95 target should be 2Gy,but the calculated D_95 is 1.9791Gy

I thought this is because the value of objective function will never be zero?

So should I increase the value of objective function to make the calculated dose meet prescription, such as to let the calculated dose distribution meet >95% volume,>2Gy for target , We set the objective function of target to >95% volume ,>2.2Gy .  By the way ,there is a enlarge for dose during changing the dose to machine MU after the fluence optimization in pinnacle,I don't whether it is related to this?

Or is this only because I don't give enough objective function?

Thanks very much!
phoebe

**Comment by Phoebegit** [comment]
Hi，
  I try the min DVH constraint function,It works !   D_95=2Gy.
  re-normalization is anthor good approach.
Thanks very much! It's very useful!

Thanks for you patience again.

Phoebe

**Comment by markbangert** [comment]
Always good to hear when the optimization constraints work, hehe...

Will close this issue now!
