### ISSUE TITLE
problem with relative paths

### ISSUE THREAD

**Issue by wahln** [e0404/matRad#332]
At some points there are issues with relative paths to matRad files which are annoying (e.g. within the unit testing).
The problems occur when you run certain matRad functionality and are currently not in the matRad root directory.
To avoid this, we should make sure, that

- all references to files should be absolute paths, which are created at runtime through locating the file that is executing the code (e.g. via `mfilename('fullpath')`). Alternatively `which` could be used.
- if something needs to be executed within a directory, also use the absolute bath to `cd` into the directory. But before, use `pwd` to get the users directory and after the execution `cd` back into it

**Comment by markbangert** [comment]
This is a good point. I suggest such information, which is related to a matRad specific programming style centrally in a matRad guide on programming style. For the time being I put it at https://github.com/e0404/matRad/wiki/matRad-addInfo - please feel free to add more information here but only after consultation with @wahln , @becker89 , or me (@markbangert ).
