### ISSUE TITLE
Hickup in X and Y dimensions in DICOM import

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#339]
I just came across some funny permutation of the X and Y dimensions within the DICOM import that I cannot make sense of right now. This issue might be looking into at some point with some debug data: In https://github.com/e0404/matRad/blob/master/dicomImport/matRad_interpDicomDoseCube.m and in https://github.com/e0404/matRad/blob/master/dicomImport/matRad_interpDicomCtCube.m there is an interpolation using matlab's interp3 function in combination with a meshgrid happening, i.e.

```
[ Y,  X,  Z] = meshgrid(x,y,z);
[Yq, Xq, Zq] = meshgrid(ct.x,ct.y,ct.z);

dose.cube = interp3(Y,X,Z,dose.cube,Yq,Xq,Zq,'linear',0);
```

This might be wrong but it will be hard to figure that out because usually x and y coordinates are identical in DICOM. Nevertheless at some point we should think this through...

**Comment by becker89** [comment]
I think we can safely close this issue :-)
