### ISSUE TITLE
Possible bug in matRad_addMargin

### ISSUE THREAD

**Issue by mkomel** [e0404/matRad#347]
I believe there is a bug on line 61 of matRad_addMargin.m :
`[xCoord, yCoord, zCoord] = ind2sub(size(mVOIEnlarged),NewIdx);`

It should instead be:
`[yCoord, xCoord, zCoord] = ind2sub(size(mVOIEnlarged),NewIdx);`
since ind2sub returns [y,x,z]. This is also how ind2sub is used elsewhere in matRad code.

**Comment by markbangert** [comment]
Hi @mkomel ,

thanks for reporting this issue. Just had a quick look and it seems like you might be on to something there. I will need some more time to figure this out. Will get back to you asap and ask for your review.

Cheers!

**Comment by markbangert** [comment]
Please check out https://github.com/e0404/matRad/pull/348 and let me know what you think. I figure the code has been doing the right thing but labels were wrong because I messed up things at two different points in the code that ended up compensating each other!

**Comment by mkomel** [comment]
Hi @markbangert,

your changes make sense to me, the code is clear now. Thanks!

**Comment by markbangert** [comment]
Thanks once more @mkomel for reporting this inconsistency!

Will merge https://github.com/e0404/matRad/pull/348 and close this issue.
