### ISSUE TITLE
Set bounds on optimization variables

### ISSUE THREAD

**Issue by Phoebegit** [e0404/matRad#349]
Hi,
I want to calculate dose result with the limitation of minimum MU, but I found the postprocessing method is not very good sometime. I know the conversion relationship between the particle number and MU ,is it OK to change the `options.lb              = zeros(1,dij.totalNumOfBixels); ` to `options.lb              = templb_w;` in matRad_fluenceOptimization.m ? the matrix templb_w is the particle number corresponding to minimum MU.

Is this method similar to method of the commercial TPS in the limitation of minimum MU?

Thanks very much

**Comment by wahln** [comment]
Hi,
yes, you should directly be able to just change the lower bounds in options.lb (templb_w should be a vector as in the standard setting).
I can't say if this method is similar to the ones used in commercial TPS, though.
Let us know if something doesn't work out.
Cheers!

**Comment by Phoebegit** [comment]
Thanks ! I will close it!
