### ISSUE TITLE
LET validation

### ISSUE THREAD

**Issue by wenbogu1992** [e0404/matRad#352]
Hi,

I am planning to use matRad to calculate LET for my own proton optimization. I am wondering if there are any publications indicating the LET calculation has been validated and compared to other calculation engine, like MC. In the paper on Med Phys. 2017, I only find the validation of doses. Thank you.

Best,
Wenbo

**Comment by becker89** [comment]
Hi Wenbogu1992,

as of now we haven't validated or compared analytical LET calculations from matRad to Monte Carlo engines. In that regard, please be aware that the LET profiles as part of the generic proton base data (=protons_Generic.mat) originate from an analytical calculation. However, in the dev branch https://github.com/e0404/matRad/tree/dev you can find an interface to the Monte Carlo engine MCSquare for protons, which might be of interest for you. best HP
