### ISSUE TITLE
3D Conformal

### ISSUE THREAD

**Issue by ta80** [e0404/matRad#353]
I wonder if the 3D Conformal option is equivalent to the 3DCRT calculation method? If not, is there any script can support the 3DCRT calculation?

Thx

**Comment by markbangert** [comment]
I dont really get what you are referring to. We do have a button in the GUI that ind of disables intensity-modulation for photons by invoking the collapseDij function before optimization (cf https://github.com/e0404/matRad/blob/master/matRadGUI.m#L1527). This is by no means a proper implementation of 3d conformal planning, it is more of an educational tool. If you want to experiment with 3d conformal planning in matRad then the collapseDij function (https://github.com/e0404/matRad/blob/master/optimization/matRad_collapseDij.m) will certainly be a good starting point. Let me know if you need more directions or if I can close this issue for the time being...

**Comment by ta80** [comment]
Yes please, I need more directions in this regard. Your feedback is highly appreciated.

**Comment by markbangert** [comment]
Then please ask a specififc question. I cannot write an essay...

**Comment by ta80** [comment]
To my understanding, the dose calculation for 3D conformal planning should be much faster than the IMRT one, so is there any way in Matrad to disable intensity-modulation before dij calculation?

**Comment by markbangert** [comment]
No, that is not easily possible. You would have to modify the dose
calculation algorithm accordingly. In principle the functionality is there.
If we have a DICOM pln then we import the openings and do a field based
calculation. When we start planning from scratch within matrad, hower, the
corresponding fields are not set. You may want to check the flag '
isFieldBasedDoseCalc'
within https://github.com/e0404/matRad/blob/master/matRad_calcPhotonDose.m to
figure out how you could approach the issue.

**Comment by ta80** [comment]
I tried this exercise before, loading DICOM plan, and do field based calculation, but I got an exception because there is no shape in the stf.ray as  shown in the code:

% overwrite field opening if necessary
            if isFieldBasedDoseCalc
                F = stf(i).ray(j).shape;
            end

I went through the matRad_generateStf file and there is nothing related to shape struct.

**Comment by markbangert** [comment]
exactly. you would have to write this yourself :)
