### ISSUE TITLE
Manual Calculation

### ISSUE THREAD

**Issue by JackWondeson** [e0404/matRad#370]
Can you please tell me how to setup beams with different energies and geometries at 100 ssd and also 90 ssd, so I can compare the pdd's and profiles to the actual chamber measurement

Thank you

**Comment by markbangert** [comment]
I can post a script here for quadratic shapes. That is really
straightforward. More complex shapes are more tricky but can also be done.
Would you be able to start working with quadratic fields? Also our related
repo https://github.com/e0404/photonPencilBeamKernelCalc might be
interesting for you as it allows you to set up your own machine in matrad.
Note that this is work in progress though...



JackWondeson <notifications@github.com> schrieb am Mo., 2. Sep. 2019, 07:48:

**Comment by JackWondeson** [comment]
Thank you for your reply, I'll check the repo you mentioned by today, but I have a specific case and need your help:
How do I verify my machine data like depth dose and profiles of open field of different field sizes then how can I put on an open field like 8 by 20 cm and calculate normalization to the maximum depth or a different depth?

Regards.

**Comment by markbangert** [comment]
I will check about rectangular fields and let you know. Please send me a
reminder if you do not hear from me within the next two days...

JackWondeson <notifications@github.com> schrieb am Mo., 2. Sep. 2019, 09:47:

**Comment by JackWondeson** [comment]
Thanks a lot.

Sure, I will.

**Comment by JackWondeson** [comment]
Gentle reminder

**Comment by markbangert** [comment]
:)

For quandratic fields you can use the following code where bixel width corresponds to the side length of the square at the iso center. I will try to put together some code for custom openings later...

`
matRad_rc

% load patient data, i.e. ct, voi, cst
load BOXPHANTOM.mat

% meta information for treatment plan
pln.radiationMode   = 'photons';     % either photons / protons / carbon
pln.machine         = 'Generic';

pln.numOfFractions  = 30;

% beam geometry settings
pln.propStf.bixelWidth      = 100; % [mm] / also corresponds to lateral spot spacing for particles
pln.propStf.gantryAngles    = 0; % [°]
pln.propStf.couchAngles     = 0; % [°]
pln.propStf.numOfBeams      = numel(pln.propStf.gantryAngles);
pln.propStf.isoCenter       = ones(pln.propStf.numOfBeams,1) * matRad_getIsoCenter(cst,ct,0);

% dose calculation settings
pln.propDoseCalc.doseGrid.resolution.x = ct.resolution.x; % [mm]
pln.propDoseCalc.doseGrid.resolution.y = ct.resolution.y; % [mm]
pln.propDoseCalc.doseGrid.resolution.z = ct.resolution.z; % [mm]

% optimization settings
pln.propOpt.optimizer       = 'IPOPT';
pln.propOpt.bioOptimization = 'none'; % none: physical optimization;             const_RBExD; constant RBE of 1.1;
                                      % LEMIV_effect: effect-based optimization; LEMIV_RBExD: optimization of RBE-weighted dose
pln.propOpt.runDAO          = false;  % 1/true: run DAO, 0/false: don't / will be ignored for particles
pln.propOpt.runSequencing   = false;  % 1/true: run sequencing, 0/false: don't / will be ignored for particles and also triggered by runDAO below

%% define steering file by hand

SSD = 800;
 
if pln.propStf.gantryAngles == 0 && pln.propStf.gantryAngles == 0
    stf.gantryAngle       = pln.propStf.gantryAngles;
    stf.couchAngle        = pln.propStf.couchAngles;
    stf.bixelWidth        = pln.propStf.bixelWidth;
    stf.radiationMode     = 'photons';
    stf.SAD               = 1000;
    stf.isoCenter         = [240 240+878-SSD 240];
    stf.numOfRays         = 1; 
    stf.sourcePoint_bev   = [0 -stf.SAD 0];
    stf.sourcePoint       = [0 -stf.SAD 0];
    stf.numOfBixelsPerRay = 1;
    stf.totalNumOfBixels  = 1;

    stf.ray.rayPos_bev = [0 0 0];
    stf.ray.targetPoint_bev = [0 stf.SAD 0];
    stf.ray.rayPos = [0 0 0];
    stf.ray.targetPoint = [0 stf.SAD 0];
    stf.ray.beamletCornersAtIso = nan; % not needed for pencil beam dose calc
    stf.ray.rayCorners_SCD = nan; % not needed for pencil beam dose calc
    stf.ray.energy = 6;
else
    error('not implemented');
end

%% dose calculation
resultGUI = matRad_calcDoseDirect(ct,stf,pln,cst,1);

%% start gui for visualization of result
matRadGUI

`

**Comment by markbangert** [comment]
Different energies is not possible with matRad. You would have to generate your own kernels for that. Just out of curiosity: What project are you working on with this... and where?! ;)

**Comment by markbangert** [comment]
Here comes a script for arbitrary shapes that are parameterized by a 2D matrix:

```
matRad_rc

% load patient data, i.e. ct, voi, cst
load BOXPHANTOM.mat

% meta information for treatment plan
pln.radiationMode   = 'photons';     % either photons / protons / carbon
pln.machine         = 'Generic';

pln.numOfFractions  = 30;

% beam geometry settings
pln.propStf.bixelWidth      = 'field'; % [mm] / also corresponds to lateral spot spacing for particles
pln.propStf.collimation.convResolution = .5; % [mm]
pln.propStf.collimation.fieldWidth = 100;

pln.propStf.gantryAngles    = 0; % [°]
pln.propStf.couchAngles     = 0; % [°]
pln.propStf.numOfBeams      = numel(pln.propStf.gantryAngles);
pln.propStf.isoCenter       = ones(pln.propStf.numOfBeams,1) * matRad_getIsoCenter(cst,ct,0);

% dose calculation settings
pln.propDoseCalc.doseGrid.resolution.x = ct.resolution.x; % [mm]
pln.propDoseCalc.doseGrid.resolution.y = ct.resolution.y; % [mm]
pln.propDoseCalc.doseGrid.resolution.z = ct.resolution.z; % [mm]

% optimization settings
pln.propOpt.optimizer       = 'IPOPT';
pln.propOpt.bioOptimization = 'none'; % none: physical optimization;             const_RBExD; constant RBE of 1.1;
                                      % LEMIV_effect: effect-based optimization; LEMIV_RBExD: optimization of RBE-weighted dose
pln.propOpt.runDAO          = false;  % 1/true: run DAO, 0/false: don't / will be ignored for particles
pln.propOpt.runSequencing   = false;  % 1/true: run sequencing, 0/false: don't / will be ignored for particles and also triggered by runDAO below

%% define steering file by hand

SSD = 800;
 
if pln.propStf.gantryAngles == 0 && pln.propStf.gantryAngles == 0
    stf.gantryAngle       = pln.propStf.gantryAngles;
    stf.couchAngle        = pln.propStf.couchAngles;
    stf.bixelWidth        = pln.propStf.bixelWidth;
    stf.radiationMode     = 'photons';
    stf.SAD               = 1000;
    stf.isoCenter         = [240 240+878-SSD 240];
    stf.numOfRays         = 1; 
    stf.sourcePoint_bev   = [0 -stf.SAD 0];
    stf.sourcePoint       = [0 -stf.SAD 0];
    stf.numOfBixelsPerRay = 1;
    stf.totalNumOfBixels  = 1;

    stf.ray.rayPos_bev = [0 0 0];
    stf.ray.targetPoint_bev = [0 stf.SAD 0];
    stf.ray.rayPos = [0 0 0];
    stf.ray.targetPoint = [0 stf.SAD 0];
    stf.ray.beamletCornersAtIso = nan; % not needed for pencil beam dose calc
    stf.ray.rayCorners_SCD = nan; % not needed for pencil beam dose calc
    stf.ray.energy = 6;
    
    % define a simple cross as primary fluence
    stf.ray.shape = zeros(2*pln.propStf.collimation.fieldWidth);
    stf.ray.shape(50:150,85:115) = 1;
    stf.ray.shape(85:115,50:150) = 1;
    
    imagesc(stf.ray.shape)
    title('primary fluence')
    axis equal tight
else
    error('not implemented');
end

%% dose calculation
resultGUI = matRad_calcDoseDirect(ct,stf,pln,cst,1);

%% start gui for visualization of result
matRadGUI
```

Please observe that the shape is specified with the binary matrix `stf.ray.shape` that is visualized in a matRad figure. If you want to see the cross in the dose make sure to switch to coronal view in the GUI.

Let me know if you need more help or if I can close this issue for the time being.

**Comment by markbangert** [comment]
Hi @JackWonderson! Here is a gentle reminder that I asked for feedback ;)
