### ISSUE TITLE
TG #23

### ISSUE THREAD

**Issue by JackWondeson** [e0404/matRad#371]
Hello,

Is it possible to perform TG23 in Matrad, if so please advise.

Thanks

**Comment by markbangert** [comment]
What is TG23?

JackWondeson <notifications@github.com> schrieb am Mo., 2. Sep. 2019, 08:33:

**Comment by wahln** [comment]
I guess TG23 refers to the dosimetry verification report by AAPM? Which provides measurement data for various photon geometries and energies? I am not familiar with the data package, so I can't really give a general advice there...
