### ISSUE TITLE
Error in optimization

### ISSUE THREAD

**Issue by P705** [e0404/matRad#380]
Hi
I wanna work with matRad but when i click on optimize button in GUI, some error happens.
The PROSTATE data load and influence dose calculation correctly done but i can't optimize the plan.  
Please guide me to solve this error.
Best regard.
![image](https://user-images.githubusercontent.com/57658660/68768749-5a3b6a80-0638-11ea-8a49-2a18eca5c0f4.png)

**Comment by wahln** [comment]
Hi,
what version/which branch of the code are you using?
I just tried to reproduce the error on the master branch with the prostate case, but it ran through smoothly.

**Comment by P705** [comment]
I download last version (3.0.0) from below address in zip file :
matRad by e0404

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
matRad by e0404


 |

 |

 |




    On Wednesday, November 13, 2019, 05:27:56 PM GMT+3:30, wahln <notifications@github.com> wrote:  
 
 
Hi,
what version/which branch of the code are you using?
I just tried to reproduce the error on the master branch with the prostate case, but it ran through smoothly.

**Comment by wahln** [comment]
OK, thanks for the info... The error seems to come from the axes(...) function which is MATLAB-internal, making the error even more strange... What Matlab-version are you using?

**Comment by P705** [comment]
MATLAB R2015b    On Wednesday, November 13, 2019, 05:32:08 PM GMT+3:30, wahln <notifications@github.com> wrote:  
 
 
OK, thanks for the info... The error seems to come from the axes(...) function which is MATLAB-internal, making the error even more strange... What Matlab-version are you using?

**Comment by wahln** [comment]
I am sorry, I can't produce the error. Do you have any custom modification to the "axes" command? Can you tell me the exact steps you use in the GUI / your script?

However, I have a workaround that should let you optimize anyway:
In the file matRad_OptimizerIPOPT.m within the optimization/optimizer folder just remove or comment out the line `funcs.iterfunc          = @(iter,objective,paramter) obj.iterFunc(iter,objective,paramter,ipoptStruct.ipopt.max_iter);`

**Comment by P705** [comment]
Hi againI only load Prostate file in the gui and press calc in fluence button an then press optimize button but, the error appear for me. I didn’t do any change in the structure of .m files


Sent from Yahoo Mail for iPhone


On Wednesday, November 13, 2019, 18:21, wahln <notifications@github.com> wrote:


I am sorry, I can't produce the error. Do you have any custom modification to the "axes" command? Can you tell me the exact steps you use in the GUI / your script?

However, I have a workaround that should let you optimize anyway:
In the file matRad_OptimizerIPOPT.m within the optimization/optimizer folder just remove or comment out the line funcs.iterfunc = @(iter,objective,paramter) obj.iterFunc(iter,objective,paramter,ipoptStruct.ipopt.max_iter);

**Comment by wahln** [comment]
Alright, I think it may be a incompatibility issue with Matlab 2015b. I will try to fix it.
For the time being, I would suggest for you to use my proposed workaround from my last comment.

**Comment by P705** [comment]
Thanks so much and your last comment helps me. I can do plan without error. 
    On Wednesday, November 13, 2019, 07:39:26 PM GMT+2, wahln <notifications@github.com> wrote:  
 
 
Alright, I think it may be a incompatibility issue with Matlab 2015b. I will try to fix it.
For the time being, I would suggest for you to use my proposed workaround from my last comment.
