### ISSUE TITLE
beam orientation optimization

### ISSUE THREAD

**Issue by fishdda** [e0404/matRad#385]
Do we have any beam orientation optimization parts for this TPS matlab package?

**Comment by becker89** [comment]
Hi,
as of now there is no functionality in matRad implemented to optimise beam angles.

**Comment by pmc-datasci** [comment]
Hi,
I'm trying to implement a beam angle optimization method using matRad. I'd like to reuse the stf and dij structures, when optimizing a new beam ensemble, subset of an initial set of beams. I tried  to set the beamlet weights corresponding to non used beamlets to zero, but in the end of the optimization, process, all that beamlet weights are given a small (equal) positive value. I wonder to know if there Is a better way to implement stf and dij reutilization, aiming at improving algorithm efficiency.
