### ISSUE TITLE
Plane selection

### ISSUE THREAD

**Issue by P705** [e0404/matRad#388]
I need to see axial, coronal and sagital plane at the same time.
How can add other plane to matRad ?
How can i change the plotting code ?

**Comment by wahln** [comment]
The GUI only displays one slice in one plane at the time. You can however manually plot whatever slice and plane you want in a separate figure window using the [matRad_plotSliceWrapper](https://github.com/e0404/matRad/blob/master/tools/matRad_plotSliceWrapper.m) (which calls the plotting functions which you can find in the folder [plotting](https://github.com/e0404/matRad/tree/master/plotting)) with the variables in your workspace. 
You can also check the 3D view from the GUI, but that's probably not what you want and quite slow at the same time.
