### ISSUE TITLE
RT plan structure

### ISSUE THREAD

**Issue by P705** [e0404/matRad#391]
Hi
How can i use RT plan in matrad ?
When i import RT plan to matRad this message appear. 
How can i handle this message ?
![1](https://user-images.githubusercontent.com/57658660/70991952-dadd0300-20dd-11ea-9d61-bd78bd620532.JPG)

**Comment by markbangert** [comment]
Dear @P705, thank you for your continued interest in matRad ;)

The error message itself pretty much sums it up. You have selected an RT plan object in our DICOM browser and apparently it was not possible for for matRad to directly link the RT plan to a dose distribution. You can just click OK and proceed with the import of the entities you selected.

And: I encourage you to dig more in the code yourself in the future. It may be very helpful for your to get familiar with matlab's debugger https://www.mathworks.com/videos/using-debugger-to-walk-through-code-97232.html to develop a deeper understanding of matRad.

matRad is a community project and we cannot attend to every basic question here on github.

Kind regards, Mark
