### ISSUE TITLE
questions about radiation source of MatRad

### ISSUE THREAD

**Issue by P705** [e0404/matRad#392]
Hi
It was very nice of you to quickly read my email. I really appreciate your clear and accurate guidance as well as your helpful comments on MatRad.

We've question about source definition (Generic machine) on MatRad.

We want to evaluate accuracy dose calculation algorithm comparing  with Monte Carlo values. so, we simulated cubic water phantom and monotheistic point source in SSD 100 cm. then, we calculated depth dose in central axis of water phantom.

On the other hand, we calculated depth dose of water phantom (CT data) with MatRad.

We observed some differences in the results of that comparison. (values of MC and matRad attached). What caused these differences?

َAlso, what's geometry of source on MatRad? Is point geometry? or volume geometry?
![1](https://user-images.githubusercontent.com/57658660/71346161-73f79800-257c-11ea-8c3b-e321a72ac551.JPG)

**Comment by markbangert** [comment]
matRad models the beamline of a Siemens Artiste Linac, i.e. it includes a finite source size as well as collimator scattering as well as a realistic energy spectrum. If you want to reach better agreement you would have to retrieve information about the complete phase space of a linac and model both in MC and in the pencil beam algorithm!

**Comment by P705** [comment]
Thank you for your consideration

I want to use our linear accelerator spectrum (which phase space files is available) to apply MatRad and then compare with MC simulation in water phantom (or patient CT data). How to do it? In fact, how to apply out spectrum and our fluence to machine?

**Comment by markbangert** [comment]
You can check out the code at https://github.com/e0404/photonPencilBeamKernelCalc which provides everything to generate a custom base data set based on measurement data
