### ISSUE TITLE
Error in loading data

### ISSUE THREAD

**Issue by straightline-spec** [e0404/matRad#393]
Hi,

I recently installed the standalone version but I get this error when I try to open any example CT data:
        LoadMatFileFcn: Could not load selected data

Thanks in advance for the help!

**Comment by wahln** [comment]
Hi,
sorry for the late answer due to the Christmas / New Year break.
to better assess the problem and since we have multiple standalone versions online at the moment, I would need to know:
- Which version did you download exactly?
- Did you try all patients?
- Which patient files did you exactly download?

**Comment by Vincent0892** [comment]
Hi,
I also face the same problem
I followed your guide here:
https://github.com/e0404/matRad/wiki/Setting-up-matRad
https://github.com/e0404/matRad/wiki/Practical-treatment-planning
When I tried to load mat file, I got message "LoadMatFileFnc: Could not load selected file"

OS: windows7 without MATLAB preinstalled
matRad version: I executed "matRad_installerWin64.exe" to install, then I have MATLAB compiler v8.3, MatRad v2.2
matfile: I tried TG119.mat, HEAD_AND_NECK.mat, and LIVER.mat from Here:
https://github.com/e0404/matRad/blob/master/TG119.mat
https://github.com/e0404/matRad/blob/master/HEAD_AND_NECK.mat
https://github.com/e0404/matRad/blob/master/LIVER.mat

Can you help me?
Thanks!

**Comment by wahln** [comment]
I did a little checking, if you downloaded the current standalone (from the master branch) there seems to be a version conflict with the mat files which are too new. I will try to fix that by uploading a new standalone within the next days. So far, try to download the *.mat files from exactly this commit:
https://github.com/e0404/matRad/tree/51987803dfddf069de82609b464486b840d6f3f0
Let me know if this works for you.

**Comment by Vincent0892** [comment]
Hi Wahln:
It works for me, thank you very much.
