### ISSUE TITLE
Manual Calculation

### ISSUE THREAD

**Issue by Gheffar** [e0404/matRad#394]
Hello

I'm doing my thesis for my master degree and need to implement the manual dose calculation, I proposed matRad to work on, and went through the code below
https://github.com/e0404/matRad/issues/370#issuecomment-529012085

I need your help in order to complete the part where the beam has non-zero pln.propStf.gantryAngles, your sooner feedback is highly appreciated.

Thanks

**Comment by markbangert** [comment]
I do not have ay clue where your problem is?! can you be more explicit?

**Comment by Gheffar** [comment]
As shown in the code below, there is no code when the gantry angle is 0;

% load patient data, i.e. ct, voi, cst
% meta information for treatment plan
% beam geometry settings
% dose calculation settings
% optimization settings
%% define steering file by hand

if pln.propStf.gantryAngles == 0 && pln.propStf.gantryAngles == 0
    %% this part is already done
else
    error('not implemented'); %% I need your help to develop this part
end

%% dose calculation
%% start gui for visualization of result

**Comment by markbangert** [comment]
You can basically use the same building blocks and provide information for non-zero gantry/couch angles aswell. You just need to fill the structures (pln, stf... ) accordingly. I figure that this might be the integral part of your thesis so good luck with programming. I am not going to solve this exercise for you!

**Comment by Gheffar** [comment]
Kindly send me the reference for this type of calculation so I can work on the programming part.

**Comment by markbangert** [comment]
There is no reference. My advise is to work with the source code directly to figure it out.

**Comment by Gheffar** [comment]
Can I use the matrad_generateStf function instead of generating stf by hand?

**Comment by wahln** [comment]
I also don't really understand what you want to do. matRad_generateStf is useful to set up the geometry for our dose calculation algorithms, when you know which modality, machine, geometry, etc. you want to use and have set the respective parameters.  I suggest to work through the examples and check our [wiki](https://github.com/e0404/matRad/wiki).
