### ISSUE TITLE
A question about optimization function

### ISSUE THREAD

**Issue by P705** [e0404/matRad#398]
Hi
I saw the ipopt optimization function but don't understand how these functions work and optimize the planning.
The eclipse treatment planning system use optimization functions like DVO or PO.
Please describe, why to choose ipopt for optimization and how this function works. 
Thanks

**Comment by wahln** [comment]
1. matRad is open source and independent of any other treatment planning system or vendor. I don't see how we could or would want to incorporate proprietary optimization algorithms by eclipse.
2. IPOPT is an open-source interior-point quasi-newton optimizer and therefore a very suitable choice for optimization of standard radiotherapy treatment planning problems and especially for matRad. 
3. This is not the right forum for explaining numerical optimizers. I can suggest some reading material on numerical optimization https://link.springer.com/book/10.1007/978-0-387-40065-5 and for IPOPT specifically I suggest https://link.springer.com/article/10.1007/s10107-004-0559-y and their web page https://github.com/coin-or/Ipopt 
4. Please also browse through our wiki for technical questions: https://github.com/e0404/matRad/wiki/Fluence-optimization
