### ISSUE TITLE
can matRad be run in a matlab session without display?

### ISSUE THREAD

**Issue by regproj** [e0404/matRad#399]
Hello, I'm having an issue running matRad in a -nodisplay session. I've included what I did in order to reproduce the error below (simply run matlab with the -nodisplay option and run matRad to reproduce). It seems like something is going wrong in the fluenceOptimization, but I'm not familiar enough with the code yet to debug things, and I was wondering if I could get some help.

>>/usr/local/MATLAB/R2018b/bin/matlab -nodisplay

                            < M A T L A B (R) >
                  Copyright 1984-2018 The MathWorks, Inc.
                   R2018b (9.5.0.944444) 64-bit (glnxa64)
                              August 28, 2018

 
To get started, type doc.
For product information, visit www.mathworks.com.
 
>> matRad                          

matRad: Generating stf struct... Warning: Could not find HLUT GE MEDICAL SYSTEMS-LightSpeed
RT-ConvolutionKernel-STANDARD_photons.hlut in hlutLibrary folder. matRad
default HLUT loaded 
Progress: 100.00 %
Warning: Could not find HLUT GE MEDICAL SYSTEMS-LightSpeed
RT-ConvolutionKernel-STANDARD_photons.hlut in hlutLibrary folder. matRad
default HLUT loaded 
matRad: Photon dose calculation...
Beam 1 of 5: 
matRad: calculate radiological depth cube...done.
                   SSD = 937mm                 
matRad: Uniform primary photon fluence -> pre-compute kernel convolution for SSD = 937 mm ...
Progress: 100.00 %
Beam 2 of 5: 
matRad: calculate radiological depth cube...done.
                   SSD = 845mm                 
matRad: Uniform primary photon fluence -> pre-compute kernel convolution for SSD = 845 mm ...
Progress: 100.00 %
Beam 3 of 5: 
matRad: calculate radiological depth cube...done.
                   SSD = 889mm                 
matRad: Uniform primary photon fluence -> pre-compute kernel convolution for SSD = 889 mm ...
Progress: 100.00 %
Beam 4 of 5: 
matRad: calculate radiological depth cube...done.
                   SSD = 889mm                 
matRad: Uniform primary photon fluence -> pre-compute kernel convolution for SSD = 889 mm ...
Progress: 100.00 %
Beam 5 of 5: 
matRad: calculate radiological depth cube...done.
                   SSD = 842mm                 
matRad: Uniform primary photon fluence -> pre-compute kernel convolution for SSD = 842 mm ...
Progress: 100.00 %

Optimzation initiating...
Press q to terminate the optimization...
Dot indexing is not supported for variables of this type.

Error in matRad_OptimizerIPOPT/optimize (line 132)
                        xCmdWndView =
                        cw.getComponent(0).getViewport.getComponent(0);

Error in matRad_fluenceOptimization (line 217)
optimizer = optimizer.optimize(wInit,optiProb,dij,cst);

Error in matRad (line 67)
resultGUI = matRad_fluenceOptimization(dij,cst,pln);

**Comment by becker89** [comment]
The error is caused in a callback definition that allows to stop the optimization at any time. In detail, pressing the button q will stop the optimisation later on. However, when you run matlab from the command line, the code can't access Matlab's command window handle from the IDE to define this callback. What we would need here https://github.com/e0404/matRad/blob/7e1ad4a8f5faa0eae034b0e2f2d4c168238e671b/optimization/optimizer/matRad_OptimizerIPOPT.m#L126 an additional inquiry if Matlab is running from the command line or from the Matlab IDE. A quick solution is also to comment out these lines since you probably won't interact with the optimization when executing a script from the command line. You might face the same issue when the objective function value is going to displayed in each iteration.

**Comment by wahln** [comment]
We already have a fix for this, quite similar to what @becker89 proposed. I will make a PR.

**Comment by wahln** [comment]
#400 should fix this. @becker89 I assigned you to review. Will also integrate this into the dev branch. 
@regproj let me know if the fix works for you!

**Comment by becker89** [comment]
@regproj maybe also consider executing a script with the additional parameter -nodesktop

**Comment by regproj** [comment]
Fixed! Thanks so much
