### ISSUE TITLE
Single field uniform dose optimization

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#40]
Lets implement this!

**Comment by Baozhou** [comment]
Do you plan to implement SFUD?

**Comment by markbangert** [comment]
I have a dirty function that does this for protons. In principle it is very easy to implement: Just solve numOfbeams optimization processes and then it's done. The bigger question is: How do we implement this in the overall workflow... This will probably takes some time to figure out.

**Comment by markbangert** [comment]
This has been implemented by Jona.
