### ISSUE TITLE
ipopt error in new MATLAB version 2020a

### ISSUE THREAD

**Issue by pamede** [e0404/matRad#408]
I get an error when I try to use the ipopt in my matRad scripts:
`Invalid MEX-file '..\matRad\optimization\optimizer\ipopt.mexw64': Eine DLL-Initialisierungsroutine ist fehlgeschlagen.`
The script did work fine with the older MATLAB version 2019b and now produces the above error, when I call ipopt in the following way, using the MATLAB version 2020a:
`[result, ~] = ipopt (start, funcs, options);`

**Comment by wahln** [comment]
I guess there has been some change in MATLAB 2020 concerning their dll-libraries to which the ipopt mex links. Could be difficult to find out. Can someone reproduce / confirm?

**Comment by js1tr3** [comment]
Confirmed with GPOPSII version in matlab 2020a

**Comment by wahln** [comment]
Hi js1tr3. 
Some more insight from our side: Apparently this is only an issue in Windows (tests on mac and linux were successful).
I have compiled a new mex binary using MSVC 2017 (interfacing to the solver libmwma57) shipped with Matlab that seems to work now in 2020 (and also in some older versions down to 2015). So recompiling and mexing with a newer version seems to help.
You can find it here, maybe it's suitable for your projects, too: https://github.com/e0404/matRad/blob/prepareBlaise/optimization/optimizer/ipopt.mexw64
Best, Niklas

**Comment by js1tr3** [comment]
Thankyou Niklas, that worked like a charm!

-J

**Comment by hadismoazamig** [comment]
> Hi js1tr3.
> Some more insight from our side: Apparently this is only an issue in Windows (tests on mac and linux were successful).
> I have compiled a new mex binary using MSVC 2017 (interfacing to the solver libmwma57) shipped with Matlab that seems to work now in 2020 (and also in some older versions down to 2015). So recompiling and mexing with a newer version seems to help.
> You can find it here, maybe it's suitable for your projects, too: https://github.com/e0404/matRad/blob/prepareBlaise/optimization/optimizer/ipopt.mexw64
> Best, Niklas

Hi, 
The above link does not exist. How can I see a newer version?

**Comment by wahln** [comment]
It's now on the master branch:
https://github.com/e0404/matRad/blob/master/optimization/optimizer/ipopt.mexw64

**Comment by schtap** [comment]
Thanks @wahln for this precious support !
Can you help with the procedure to recompile the mexw64 files ?

**Comment by bmmddzgj** [comment]
> Hi js1tr3. Some more insight from our side: Apparently this is only an issue in Windows (tests on mac and linux were successful). I have compiled a new mex binary using MSVC 2017 (interfacing to the solver libmwma57) shipped with Matlab that seems to work now in 2020 (and also in some older versions down to 2015). So recompiling and mexing with a newer version seems to help. You can find it here, maybe it's suitable for your projects, too: https://github.com/e0404/matRad/blob/prepareBlaise/optimization/optimizer/ipopt.mexw64 Best, Niklas

Hello, could you tell me how to compile a new 'ipopt' mex binary that could work with matlab2021a?

**Comment by wahln** [comment]
I think the binary here https://github.com/e0404/matRad/blob/3d29b765a9a0a02a593890726102a7d9db907af7/optimization/optimizer/ipopt.mexw64
should work for Matlab 2021a on Windows, or do you need to compile from scratch on Windows?
You can also check out this GitHub-Repo https://github.com/ebertolazzi/mexIPOPT for creating new IPOPT mex files.

**Comment by bmmddzgj** [comment]
> I think the binary here https://github.com/e0404/matRad/blob/3d29b765a9a0a02a593890726102a7d9db907af7/optimization/optimizer/ipopt.mexw64 should work for Matlab 2021a on Windows, or do you need to compile from scratch on Windows? You can also check out this GitHub-Repo https://github.com/ebertolazzi/mexIPOPT for creating new IPOPT mex files.

I've successfully run code with ipopt. What I do is replace "ipopt.mexw64" in https://www.coin-or.org/download/binary/Ipopt/Ipopt-3.11.1-win64-intel13.1.zip with the file you mentioned https://github.com/e0404/matRad/blob/3d29b765a9a0a02a593890726102a7d9db907af7/optimization/optimizer/ipopt.mexw64
