### ISSUE TITLE
DICOM import error

### ISSUE THREAD

**Issue by adrianamaria** [e0404/matRad#41]
Hi,

I am having some troubles importing DICOM data and converting them to .mat

It almost always stops at this point:

"""""finished!
creating cube for REF volume...
creating cube for ISO volume...
creating cube for OpticNerv_R volume...
Error using  <= 
Matrix dimensions must agree.

Error in matRad_convRtssContours2Indices (line 65)
        slicesInMatradCt = find(dicomCtSlicePos+dicomCtSliceThickness/2 > ct.z & dicomCtSlicePos-dicomCtSliceThickness/2
        <= ct.z);

Error in matRad_importDicom (line 70)
    structures(i).indices = matRad_convRtssContours2Indices(structures(i),ct);

Error in matRad_importDicomGUI>import_button_Callback (line 308)
matRad_importDicom(files);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRad_importDicomGUI (line 66)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)matRad_importDicomGUI('import_button_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating UIControl Callback""""""

Do you know any tricks to overcome this error?

Many thanks,
Adriana

**Comment by markbangert** [comment]
Hi Adriana,

Thanks for your bug Report. Do you see the possibility to share the dicom
data with us? Maybe in annonymized form, maybe an example based on Phantom
data? I do have an idea but it would really be super helpful if we could
reproduce the error with some data. If you want you can use my email
m.bangert@dkfz.de for private communication.

Thanks mark


Am 28.12.2015 11:46 schrieb "adrianamaria" <notifications@github.com>:
>
> Hi,
>
> I am having some troubles importing DICOM data and converting them to mat
>
> It almost always stops at this point:
>
> """""finished!
> creating cube for REF volume
> creating cube for ISO volume
> creating cube for OpticNerv_R volume
> Error using <=
> Matrix dimensions must agree
>
> Error in matRad_convRtssContours2Indices (line 65)
> slicesInMatradCt = find(dicomCtSlicePos+dicomCtSliceThickness/2 > ctz &
dicomCtSlicePos-dicomCtSliceThickness/2
> <= ctz);
>
> Error in matRad_importDicom (line 70)
> structures(i)indices = matRad_convRtssContours2Indices(structures(i),ct);
>
> Error in matRad_importDicomGUI>import_button_Callback (line 308)
> matRad_importDicom(files);
>
> Error in gui_mainfcn (line 95)
> feval(varargin{:});
>
> Error in matRad_importDicomGUI (line 66)
> gui_mainfcn(gui_State, varargin{:});
>
> Error in
@(hObject,eventdata)matRad_importDicomGUI('import_button_Callback',hObject,eventdata,guidata(hObject))

**Comment by adrianamaria** [comment]
Hello Mark,

Thank you for your prompt reply.
I've sent you the file on your e-mail address, since it's too big to post it here.

Many thanks for your help,
Adriana

**Comment by markbangert** [comment]
Thanks for sharing the files. I will look into this issue tomorrow night at
the very latest and get back to you.
Am 28.12.2015 12:29 schrieb "adrianamaria" <notifications@github.com>:

**Comment by markbangert** [comment]
Hi Adriana,

I was able to repsoduce your error and fix this issue. Please check the modifications I just pushed to the dev branch... I only changed the following file -> https://github.com/e0404/matRad/blob/dev/dicomImport/matRad_convRtssContours2Indices.m to have a higher tolerance if the RT structure set is defined not exatly at the location of the corresponding CT slice. For your data, matRad was looking for a CT slice @ -28.001mm but there was only one defined directly at -28mm. I changed the rounding operation to two digits after the point and I that will do for the very patient data you sent me. I know that this is a common issue with importing DICOM so maybe some time in the future you might want to adjust that even further.

Mark

**Comment by adrianamaria** [comment]
Thank you, Mark! It works now!
Before I post any more errors, can you please inform me on the issue-opening policy?
I am working on a 3D Slicer+RT module- PlanUNC and matRad- Pinnacle synergy (but not on source code level, more like clinical-relevance output performance comparison).
I have knowledge of Matlab, but i am just starting out with matRad. I wouldn't like to post anything that you guys would find too easy, whose bug has already been fixed or simply too easy and not worth it:)
Therefore, if you'd please let me know the ethics around here that would guide me whether to post or not the next time i get stuck.

Many thanks,
Adriana

**Comment by markbangert** [comment]
Well matrad is still a pretty young project so we did not come up with abinding policy yet. I suggest we'll try to find out together! So I encourage you and everybody else to keep opening new issues. We are looking forward to any external input. If you feel that filing an issue might be inappropriate eg for a simple question you always welcome to email us.
