### ISSUE TITLE
DICOM import does not set visibleColor

### ISSUE THREAD

**Issue by better0123** [e0404/matRad#412]
Refers to the nonexistent field 'visibleColor'

**Comment by markbangert** [comment]
Hi @better0123 you want share with us what was the problem?

**Comment by better0123** [comment]
Thank your attention!After I import my  own DICOM data,there is no visibleColor in the CST variable.So an error will be reported while ploting contour. I wonder why there is no visibleColor after my data transformation.

**Comment by wahln** [comment]
This is a current bug on the master branch. It is fixed in the dev branch and will be fixed in the next release. Will keep this opened until the next version is out.

**Comment by better0123** [comment]
Thank you very much!

**Comment by wahln** [comment]
For all others experiencing the problem. Here is a temporary solution to set the color manually if it is missing after dicom import:
```
for i = 1:size(cst,1)
  cst{i,5}.visibleColor = [1 1 1];
end
```
This sets the display color for all structures to white (given by the rgb-array [1 1 1]).

**Comment by better0123** [comment]
Thank you. That's settled
