### ISSUE TITLE
Question about EUD objectives/constraints

### ISSUE THREAD

**Issue by regproj** [e0404/matRad#415]
For EUD objectives/constraints, EUD = (sum(d^a))^(1/a).
I was trying to figure out how to adjust the exponent (a) value and was wondering how this relates to the K value that can be adjusted in matRad.

**Comment by regproj** [comment]
On a separate note, I noticed that if you scale the CT voxel size from 1 -> 5 mm or greater, the beams can potentially originate from inside the patient's body. Is there a way to have beams originate from a fixed distance away from the body even if the CT is resampled to a different voxel size?

**Comment by wahln** [comment]
To your first question: just look e.g. at the files themselves: https://github.com/e0404/matRad/blob/master/optimization/%2BDoseObjectives/matRad_EUD.m 
our k is the same as a in your equation

To your second question, I don't really understand what you mean. If you just scale and blow up a human ct to 5 time its size, of course it won't fit into our LINAC machine anymore and you will be getting weird results. If you just want to calculate dose on a different resolution, just add the following variables to the pln struct like in the matRad.m script:
```
pln.propDoseCalc.doseGrid.resolution.x = 5; % [mm]
pln.propDoseCalc.doseGrid.resolution.y = 5; % [mm]
pln.propDoseCalc.doseGrid.resolution.z = 5; % [mm]
```
If you want to downsample your ct to another resolution but keep its size, you need to create the lower resolution grid and interpolate on it. You can look at matRad_calcDoseInit where we do the resampling for the dose grid.

**Comment by regproj** [comment]
Regarding resizing the ct, I guess I was mainly wondering whether the beam locations shown in the GUI were for visualization only. If I load in a ct with it's default voxel size (~1mm, ~1mm, ~1.25mm), there's still an issue of beams potentially starting from inside the couch/body. Mainly, I'm wondering if this is for visualization purposes or if this is how it is actually being simulated. I've attached the visualization for a ct with it's default voxel size:
![default_matrad](https://user-images.githubusercontent.com/53584374/80869284-71a4f900-8c54-11ea-85fa-11242d9a5a30.png)

**Comment by markbangert** [comment]
Why don't you just calculate a plan. Then you'll see where the beams
start...

regproj <notifications@github.com> schrieb am Sa., 2. Mai 2020, 18:09:
