### ISSUE TITLE
Photon dose calculation

### ISSUE THREAD

**Issue by P705** [e0404/matRad#419]
Hi
I have some questions about photon dose calculations.
The accelerator head has different parts like collimator, wedge and etc.
These parts affect on primary fluence incident on the body or water phantom.
Without considering these affects how algorithm Calculate photon dose?
Or where these effects on primary fluence consider in the dose calculation algorithm?
And how can do dose calculations for different fields size?

**Comment by P705** [comment]
Hi
I have some questions about photon dose calculations.
The accelerator head has different parts like collimator, wedge and etc. 
These parts affect on primary fluence incident on the body or water phantom.
Without considering these affects how algorithm Calculate photon dose?
Or where these effects on primary fluence consider in the dose calculation algorithm?

**Comment by markbangert** [comment]
- We do not support wedges in our dose calculation.
- Effects of Collimator Scatter are modeled indirectly via the measurement of base data for kernel calculation.
- We do support the incorporation of a custom primary fluence.
For details please have a look at the original paper by Bortfeld et al. 1993. The reference is in the code.
