### ISSUE TITLE
Here comes a script for arbitrary shapes that are parameterized by a 2D matrix:

### ISSUE THREAD

**Issue by P705** [e0404/matRad#420]
Here comes a script for arbitrary shapes that are parameterized by a 2D matrix:

```
matRad_rc

% load patient data, i.e. ct, voi, cst
load BOXPHANTOM.mat

% meta information for treatment plan
pln.radiationMode   = 'photons';     % either photons / protons / carbon
pln.machine         = 'Generic';

pln.numOfFractions  = 30;

% beam geometry settings
pln.propStf.bixelWidth      = 'field'; % [mm] / also corresponds to lateral spot spacing for particles
pln.propStf.collimation.convResolution = .5; % [mm]
pln.propStf.collimation.fieldWidth = 100;

pln.propStf.gantryAngles    = 0; % [°]
pln.propStf.couchAngles     = 0; % [°]
pln.propStf.numOfBeams      = numel(pln.propStf.gantryAngles);
pln.propStf.isoCenter       = ones(pln.propStf.numOfBeams,1) * matRad_getIsoCenter(cst,ct,0);

% dose calculation settings
pln.propDoseCalc.doseGrid.resolution.x = ct.resolution.x; % [mm]
pln.propDoseCalc.doseGrid.resolution.y = ct.resolution.y; % [mm]
pln.propDoseCalc.doseGrid.resolution.z = ct.resolution.z; % [mm]

% optimization settings
pln.propOpt.optimizer       = 'IPOPT';
pln.propOpt.bioOptimization = 'none'; % none: physical optimization;             const_RBExD; constant RBE of 1.1;
                                      % LEMIV_effect: effect-based optimization; LEMIV_RBExD: optimization of RBE-weighted dose
pln.propOpt.runDAO          = false;  % 1/true: run DAO, 0/false: don't / will be ignored for particles
pln.propOpt.runSequencing   = false;  % 1/true: run sequencing, 0/false: don't / will be ignored for particles and also triggered by runDAO below

%% define steering file by hand

SSD = 800;
 
if pln.propStf.gantryAngles == 0 && pln.propStf.gantryAngles == 0
    stf.gantryAngle       = pln.propStf.gantryAngles;
    stf.couchAngle        = pln.propStf.couchAngles;
    stf.bixelWidth        = pln.propStf.bixelWidth;
    stf.radiationMode     = 'photons';
    stf.SAD               = 1000;
    stf.isoCenter         = [240 240+878-SSD 240];
    stf.numOfRays         = 1; 
    stf.sourcePoint_bev   = [0 -stf.SAD 0];
    stf.sourcePoint       = [0 -stf.SAD 0];
    stf.numOfBixelsPerRay = 1;
    stf.totalNumOfBixels  = 1;

    stf.ray.rayPos_bev = [0 0 0];
    stf.ray.targetPoint_bev = [0 stf.SAD 0];
    stf.ray.rayPos = [0 0 0];
    stf.ray.targetPoint = [0 stf.SAD 0];
    stf.ray.beamletCornersAtIso = nan; % not needed for pencil beam dose calc
    stf.ray.rayCorners_SCD = nan; % not needed for pencil beam dose calc
    stf.ray.energy = 6;
    
    % define a simple cross as primary fluence
    stf.ray.shape = zeros(2*pln.propStf.collimation.fieldWidth);
    stf.ray.shape(50:150,85:115) = 1;
    stf.ray.shape(85:115,50:150) = 1;
    
    imagesc(stf.ray.shape)
    title('primary fluence')
    axis equal tight
else
    error('not implemented');
end

%% dose calculation
resultGUI = matRad_calcDoseDirect(ct,stf,pln,cst,1);

%% start gui for visualization of result
matRadGUI
```

Hi Mark
You use this code for 20 * 20 field size.
The number of bixel per ray is 1. But when set the bixel in matRadGUI 5 mm, the num of bixel per ray is more than 1.
The basic question :
What is the different between the field base and bixel base dose calculation?
Which one of these method is more precise?

**Comment by markbangert** [comment]
Both bixel-based and field based dose calculation use the same algorithm as introduced by Bortfeld et al. 1993. For the field-based algorithm you can specify any shape based on a discrete matrix (cf. stf.ray.shape), for the bixel-based algorithm you only have square fields (where you can control the size with the paramter bixel.width). Does this solve your confusion?

**Comment by P705** [comment]
Hi againDo you mean for 10 * 10 cm2 field have considered 100 mm for biexl width ?And dose calculation will be done for this field size.
    On Saturday, May 23, 2020, 04:44:35 PM GMT+4:30, Mark Bangert <notifications@github.com> wrote:  
 
 


Both bixel-based and field based dose calculation use the same algorithm as introduced by Bortfeld et al. 1993. For the field-based algorithm you can specify any shape based on a discrete matrix (cf. stf.ray.shape), for the bixel-based algorithm you only have square fields (where you can control the size with the paramter bixel.width). Does this solve your confusion?

**Comment by markbangert** [comment]
Yes. If you construct a treatment plan that has a single bixel only, e.g.
because the target volume is so small then you'll get a 100*100mm^2 field
if you chose bixel width 100 (mm). Alternatively you can use field-based
dose calc and specify the opening accordingly in the fluence matrix.

P705 <notifications@github.com> schrieb am So., 24. Mai 2020, 09:10:

> Hi againDo you mean for 10 * 10 cm2 field have considered 100 mm for biexl
> width ?And dose calculation will be done for this field size.
> On Saturday, May 23, 2020, 04:44:35 PM GMT+4:30, Mark Bangert <

**Comment by P705** [comment]
You consider other treatment planning software. Compare matRad with other TPS. In other TPS software for dose calculations, the field size and MLF will be set, and based on this setting primary fluence impact on the body and finally dose will be calculated.But in the matRad we have to set bixel? How the primary fluence will be calculated?

    On Sunday, May 24, 2020, 11:53:15 AM GMT+4:30, Mark Bangert <notifications@github.com> wrote:  
 
 

Yes. If you construct a treatment plan that has a single bixel only, e.g.
because the target volume is so small then you'll get a 100*100mm^2 field
if you chose bixel width 100 (mm). Alternatively you can use field-based
dose calc and specify the opening accordingly in the fluence matrix.

P705 <notifications@github.com> schrieb am So., 24. Mai 2020, 09:10:

> Hi againDo you mean for 10 * 10 cm2 field have considered 100 mm for biexl
> width ?And dose calculation will be done for this field size.
> On Saturday, May 23, 2020, 04:44:35 PM GMT+4:30, Mark Bangert <

**Comment by markbangert** [comment]
matRad focusses on inverse planning. as such the fluence will be found during optimization. If you want to specify the fluence up front you have to take some extra truns as I tried to lay out above. If you have problems getting behind the bixel concept you may want to have a a look at our matRad medical Physics Paper.
