### ISSUE TITLE
Equation 12 of Siddon's radiological path paper in matRad_siddonRayTracer.m

### ISSUE THREAD

**Issue by weilidays** [e0404/matRad#428]
Hi, 
Currently the code for eq 12 is:
% Calculate the voxel indices: first convert to physical coords
i_mm = sourcePoint(1) + alphas_mid*(targetPoint(1) - sourcePoint(1));
j_mm = sourcePoint(2) + alphas_mid*(targetPoint(2) - sourcePoint(2));
k_mm = sourcePoint(3) + alphas_mid*(targetPoint(3) - sourcePoint(3));
% then convert to voxel index
i = round(i_mm/resolution.x);
j = round(j_mm/resolution.y);
k = round(k_mm/resolution.z);
(cited as opt 1. )

I am trying to understand why not directly follow eq. 12: 
% Calculate the voxel indices: first convert to physical coords
i_mm = sourcePoint(1) + alphas_mid*(targetPoint(1) - sourcePoint(1)) - xPlane_1;
j_mm = sourcePoint(2) + alphas_mid*(targetPoint(2) - sourcePoint(2)) - yPlane_1;
k_mm = sourcePoint(3) + alphas_mid*(targetPoint(3) - sourcePoint(3)) - zPlane_1;
% then convert to voxel index
i = 1 + round(i_mm/resolution.x);
j = 1 + round(j_mm/resolution.y);
k = 1 + round(k_mm/resolution.z);
(cited as opt. 2)
 
The consideration behind opt. 1 is because of the 'round' function? The 'i, j, k' values from opt. 1 may be smaller by 1 than those from opt 2 due to the 'round' function. If the coordinates of Plane_1 are 1*resolution, not 0.5*resolution, opt. 1 is easier to understand. Are the 'numerical instabilities at the borders' of 'i, j,k' being less than 0 or larger than the cube dimension caused by the rounding? 

I am also confused about the rounding for i_min, i_max; j_min, j_max; k_min, k_max:
i_min = ceil(1/1000*(round(1000*i_min)));
i_max = floor(1/1000*(round(1000*i_max)));
Why they are multiplied by 1000 before round and divided by 1000 before ceil/floor?  The results seem same as those of without 1000 and 1/1000.

I have another naive question... Why the Y-axis(and downward), instead of Z-axis(and upward) is the vertical axis in the patient treatment or LPS coordinate system? Is it because of the indexing of 3D matrix elements in matlab?  

Thanks,
Weili

**Comment by markbangert** [comment]
Hi Weili and thank you for your contribution!

- The factor 1000 has been included for numerical stability in order to perform rounding to three digits. Otherwise we would see invalid indices every once in a while (consider something like ceil(4.0000000001) -> 5)
- The choice of matRad coordinate system may be somewhat unfortunate but it is due Matlab's internal workings. See https://github.com/e0404/matRad/wiki/The-matRad-coordinate-system for more information.
- We chose x_plan_1 = 0.5 in order to have a direct relation between voxel indices and coordinates that have been normalized for their resoltion.

**Comment by weilidays** [comment]
Hi Mark,

Thanks a lot for your reply. 
>     * The factor 1000 has been included for numerical stability in order to perform rounding to three digits. Otherwise we would see invalid indices every once in a while (consider something like ceil(4.0000000001) -> 5)
It has to be 3 digits for removing invalid indices? 

>     * The choice of matRad coordinate system may be somewhat unfortunate but it is due Matlab's internal workings. See https://github.com/e0404/matRad/wiki/The-matRad-coordinate-system for more information.
>     * We chose x_plan_1 = 0.5 in order to have a direct relation between voxel indices and coordinates that have been normalized for their resoltion.
Thanks.

Weili

**Comment by markbangert** [comment]
We did not exactly check what precision would suffice. The three digits is
merely a shoot from the hip.

**Comment by wahln** [comment]
The issue seems to be resolved, will close.
