### ISSUE TITLE
error in 3d conformal calculation

### ISSUE THREAD

**Issue by P705** [e0404/matRad#430]
when I enable 3d conformal button in the GUI, the dose calculation was done correctly but, in the optimization below error will appear. How can handle this error?
![Capture](https://user-images.githubusercontent.com/57658660/86584293-eddff380-bf99-11ea-8717-8ffdfba1cb11.JPG)

**Comment by wahln** [comment]
I can't reproduce the error with a normal photon dose calculation on the TG119 phantom. Again: Please provide a script / workflow how to trigger this error....

**Comment by wahln** [comment]
Since I can't reproduce the bug and there's no further activity, I am closing this issue.
