### ISSUE TITLE
error in fmincon optimizer

### ISSUE THREAD

**Issue by P705** [e0404/matRad#433]
Hi
Guys when changing optimizer to fmincon, the error like below image appeared.
How can handle this error?
![error](https://user-images.githubusercontent.com/57658660/87660253-03140980-c774-11ea-95d3-45e31acff043.JPG)

**Comment by wahln** [comment]
Please provide a script that triggers that error so that we can reproduce...

**Comment by wahln** [comment]
Since I cannot reproduce the bug and there's no further activity, I am closing this issue.
