### ISSUE TITLE
DICOM input error

### ISSUE THREAD

**Issue by RicardLee9808** [e0404/matRad#437]
Recently I want to do dose calculation for my own Dicom file. As a beginner of matRad.Even though I 've read the wiki document. There is still some question for me cause it seems that not every Dicom file can be input in marRad.I want to know if there any requirements for input Dicom files? If all Dicom images can be induced in matRad?
The problem is as the figure shows.
Thanks for your help!

<img width="936" alt="563d5efde6b2fbb14e22d6838b32810" src="https://user-images.githubusercontent.com/67378287/90084524-19e45680-dd48-11ea-8d3c-f2518905a11b.png">
<img width="532" alt="fec53cbaed8d053cb2510b507b7e0ea" src="https://user-images.githubusercontent.com/67378287/90084533-21a3fb00-dd48-11ea-82d7-abc88b227d1a.png">
<img width="618" alt="d59b468f319d1ca3f92bd81caccc0f7" src="https://user-images.githubusercontent.com/67378287/90084538-24065500-dd48-11ea-8371-1129c5447689.png">

**Comment by markbangert** [comment]
Just to clarify: Do you have a series of *dcm files all belonging to one CT series? You are showing us a *.png graphics which is _not_ a dicom file.

**Comment by wahln** [comment]
Since there's no further activity I am closing this issue.
