### ISSUE TITLE
Early termination for infeasible plans (IPOPT)

### ISSUE THREAD

**Issue by regproj** [e0404/matRad#440]
I had a question about trying to reduce computation time for feasibility problems. Currently, I've been determining whether a problem is infeasible by checking if the primal/dual infeasibilities have dropped beneath a certain threshold after running IPOPT for a few hundred iterations.

I was wondering if it was possible to terminate optimization early if the infeasibility reaches too large a value (dual inf>1e9). To do so, I'm assuming you need access to the primal/dual infeasibility values from IPOPT, as well as a way to terminate optimization through script. What would be the best way to access those values from MATLAB while IPOPT is running and terminate IPOPT through  MATLAB?

**Comment by wahln** [comment]
There is a possibility in IPOPT to request certain variables during optimization. The Matlab interface realizes this with a so called "iterfunc" (check out [matRad_OptimizerIPOPT.m](https://github.com/e0404/matRad/blob/master/optimization/optimizer/matRad_OptimizerIPOPT.m) in line 134). The iterfunc is implemented in the same class (l. 239) and will be called in every iteration. Currently we only use this function and the provided objective function values for plotting, but the fourth (atm unused) parameter to the iterfunc should hold more information about internal values. Unfortunately, I am not sure if primal/dual infeasibility is accessible there, but for me that would be the first place to look at. Further the IPOPT documentation might shed some light.

**Comment by chh105** [comment]
Starting with line 239 I added the following block to [matRad_Optimizer.IPOPT.m](https://github.com/e0404/matRad/blob/master/optimization/optimizer/matRad_OptimizerIPOPT.m). Currently I just have it set to terminate early if the dual infeasibility >= 1e9, but I was wondering if you knew of any smarter ways to trigger early termination. Thanks for your help!
```
function flag = iterFunc(obj,iter,objective,extra_info,~)
            
            if extra_info.inf_du >= 1e9
                disp('Dual infeasibility too large... triggering early termination!')
                obj.abortRequested = true;
            end
            
```

**Comment by wahln** [comment]
Nice, the piece of code is exactly what I suggested. To be honest, I do not know other straightforward ways to detect infeasibility. Fast feasibility detection in non-linear, constrained optimization is afaik quite a complex problem itself (also quite actively researched). For the radiotherapy problem, one might be able to use some heuristics / structure of the dose influence matrix / dij for some particular constraints, but this would also not be trivial.

**Comment by wahln** [comment]
Will close this issue due to inactivity
