### ISSUE TITLE
difference between "ompMC" and "MCsquare"

### ISSUE THREAD

**Issue by JAMKARAN** [e0404/matRad#444]
Dear developer

What's the difference between "ompMC" and "MCsquare"? Which is better for validation of dose calculation?

**Comment by wahln** [comment]
ompMC is an open source photon Monte Carlo dose calculation and MCsquare is for proton MC dose calculation. If they are suited for "validation" depends on what you want to do. If you want to validate dose calculation for your specific machine, none are suited out of the box. @edoerner developed and validated ompMC against EGSnrc, meaning the transport is correct, but atm no dedicated machine or collimator is modeled (it uses a point source). It is more suited for educational purposes and visualizing elementary differences in analytical and MC dose calculation. MCsquare for protons allows more advanced machine modeling, but still - your specific machine is not in there by default, so beam optics etc. would be wrong, etc., and you need to put some effort into modelling your machine correctly.

**Comment by JAMKARAN** [comment]
Very thanks for concise and useful answer.
