### ISSUE TITLE
Empty Contour Error

### ISSUE THREAD

**Issue by danielkswong** [e0404/matRad#45]
Hello,

When reading RS dicom files with empty contours using the Dicom Import, it gives the following error:

Reference to non-existent field 'ContourSequence'.

Error in matRad_importDicomRtss (line 78)
    listOfSlices = fieldnames(structInfo.ROIContourSequence.(...

Error in matRad_importDicom (line 59)
structures = matRad_importDicomRtss(files.rtss{1},ct.dicomInfo);

Error in matRad_importDicomGUI>import_button_Callback (line 308)
matRad_importDicom(files);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRad_importDicomGUI (line 66)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRad_importDicomGUI('import_button_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback

It seems as though empty contours don't have the 'Contour Sequence' in the Dicom metadata, which causes the code to hang. Deleting the empty contours seemed to fix the problem. Perhaps adding some code to delete empty contours would be beneficial.

**Comment by markbangert** [comment]
Thanks for sharing this error!

Could you please have a look at our dev branch at https://github.com/e0404/matRad/blob/dev/dicomImport/matRad_importDicomRtss.m

I figure the changes we made there directly relate to your error!

I am afraid we have to get somewhat more efficient in updating our master branch on github. Seems like the community is way faster than we are at DKFZ ;)

**Comment by markbangert** [comment]
As the changes of the dev branch have been merged into the master and I did not hear any further comments regarding our bug fix I am going to close this issue.
