### ISSUE TITLE
Possible display bug in matRad_calcPhotonDose.m

### ISSUE THREAD

**Issue by lc82111** [e0404/matRad#451]
num2str() is not necessary, because '%g' requires a number.
[Line 140] (https://github.com/e0404/matRad/blob/master/matRad_calcPhotonDose.m#L140)

**Comment by wahln** [comment]
Hi,
thank you very much for spotting this. I quickly fixed it in on the `dev` branch in commit 70f3a949521c91cb04cedd317dcf8c9ba7a35a1c .
Will be included in the next patch release 2.10.1.
Closing the issue and thanks again!
