### ISSUE TITLE
Running MatRad on Linux

### ISSUE THREAD

**Issue by hadismoazamig** [e0404/matRad#452]

**Comment by hadismoazamig** [comment]
Hello, I want to run MatRad on a Linux cluster named Sabine. When running my codes, I realized that the optimization part is not working and I would not obtain objective value(FMO) which is stored in resultGUI.usedOptimizer.resultInfo.objective. I guess the problem is related to the "IPOPT" solver but I am not sure. When I look at the optimizer folder, I can see ipopt.mexa64,  ipopt.mexmaci64, ipopt.mexocta64, ipopt.mexoctmac64, ipopt.mexoctw64, ipopt.mexw32, ipopt.mexw64 files beside other .m files. Can you say which of the above .MEX files are related to Linux systems?

**Comment by wahln** [comment]
https://mathworks.com/help/matlab/ref/mexext.html

Please state any respective error messages or provide a short script that shows what you are trying to do, otherwise it is near impossible to debug remotely...

**Comment by wahln** [comment]
Closed due to inactivity...
