### ISSUE TITLE
dose calibration

### ISSUE THREAD

**Issue by P705** [e0404/matRad#453]
Hi
I read technical documentation about the base data. You mentioned, "matRad's photon dose engine is calibrated such that a bixel intensity of all ones, i.e., w = ones(stf.totalNumOfBixels,1), yields a dose of roughly 1Gy in 5cm depth for a 5cm by 5cm field at SSD = 900mm.". I don't understand this 1 Gy in 5 * 5 field were obtained in experimental conditions or in SVD algorithm. 
If obtained in algorithm how can repeat this process in matrad?  
I use boxphantom.mat and in 80 mm depth, the max dose was obtained 4 Gy as showed in the below figure.
![111](https://user-images.githubusercontent.com/57658660/95948815-2ba4b180-0dfe-11eb-9fa8-40f1c64ac5aa.JPG)

**Comment by wahln** [comment]
Please provide a script or a minimal exakt workflow description how you ended up with the above dose. Otherwise its near impossible to infer what you were doing exactly....
Also check out #445 wich contains a script that performs the workflow (it is written to validate the MC computations, but can similarly be used to reproduce the described behavior)

**Comment by P705** [comment]
Hi Wahln
What's this 1 Gy dose at field 5 * 5 in SSD = 900?
and how you consider the above value in matrad?

**Comment by wahln** [comment]
It is a reference calibration value, which means that the machine data was generated in a way that the above conditions are fulfilled when creating a single open field. 
To reproduce this, the issue i already linked above (#445) provides a script that creates that exact geometry, i.e. it has a single beamlet/bixel with `pln.propStf.bixelWidth = 50;`, corresponding to a field width of 50mm = 5cm. The reference dose (i.e., the "1 Gy" are reported at the end of the script). It is obtained by positioning a single-voxel volume-of-interest at the exact depth (5cm) in the water box. It nearly exactly produces a dose of 1Gy in this situation...

**Comment by wahln** [comment]
Closed due to inactivity.
