### ISSUE TITLE
Is there documentation or a tutorial for vmat planning in matRad?

### ISSUE THREAD

**Issue by chh105** [e0404/matRad#454]
I was hoping to perform vmat inverse planning as an extension of a research project I've been working on, and I was wondering if there was a tutorial for vmat in matRad. In particular, I'm not sure which version of the code to use and whether there is an equivalent file to the "matRad.m" imrt script that could be used to perform vmat planning. 

Also, as an unrelated question, would it be possible to set up beams that are non-coplanar but have the same isocenter 
![non_coplanar_beams](https://user-images.githubusercontent.com/56953865/96357335-64b77d00-10af-11eb-9100-cdb6f6b52445.png)
(as shown by pink circles in the drawing) and perform inverse planning? In other words, I'm hoping to perform inverse planning separately for each of the 3 pink circles.

**Comment by wahln** [comment]
The release versions of matRad cannot do VMAT planning out of the box.
However, @eric11210 has developed a 4D VMAT-module for matRad which he maintains here: https://github.com/eric11210/matRad/tree/dev_4DVMAT
Maybe he can help you out a little?
There is also a development VMAT branch in the Matlab main repository, which is, however, not working fully yet (see #376).
Also none of this is really documented, but I think that the respective matRad.m scripts include VMAT settings. It could be a starting point... 
Last but not least: I think such arcs could be possible in the mentioned branches, by defining appropriate sequences in gantry & couch angles.

**Comment by eric11210** [comment]
Hi @chh105,

The branch at https://github.com/eric11210/matRad/tree/dev_4DVMAT that @wahln linked is indeed the one which is most up-to-date. The branch is meant for 4D-VMAT, as the name suggests, but 3D (i.e., regular) VMAT is possible by just turning off the run4D option in pln.propOpt. The matRad.m script should have this option, and many more, described. The implementation follows my paper, https://doi.org/10.1088/1361-6560/aae65e. I also have a paper coming out soon which will describe my 4D-VMAT method, if you're interested in that.

The arcs you mention should be possible, by varying couch angle etc., but you'll have to verify this on your own - I think it should work, but I didn't program explicit support for this. Also, each arc would have to be optimized separately, and not as a collection. I did not implement multiple arc optimization, only single arc.

Let me know if you have further questions.

**Comment by chh105** [comment]
Sorry for the delayed reply and thanks for the advice so far. I had a question about defining gantry and couch angles in the vmat version of the matRad.m script. It seems that the script defines gantry angles as follows:
`pln.propOpt.VMAToptions.startingAngle = -180;`
`pln.propOpt.VMAToptions.finishingAngle = 180;`
However, I don't see a place to define the corresponding couch angles. Where would be the proper place to define them?

**Comment by chh105** [comment]
I've also been trying to test the functionality of using various couch and gantry angles in planning. I'm not sure if this issue is just a visual bug, but it seems like the render of beams at different gantry and couch angles is inconsistent. In the first image, the gantry angle is set to [90 180 270 0] and the couch is set to [0 0 0 0]. As you can see in the 3D render, the beams don't seem to be following those angles.
![matrad_possible_bug_with_angles](https://user-images.githubusercontent.com/56953865/97628769-6277eb80-19ea-11eb-801c-2dc53b39e8b4.png)

I'm wondering if this is an issue extends beyond just the 3D render. In the second image, I've plotted the number of OAR voxels intersected by rays generated using various couch/gantry setups.
![matrad_possible_bug_with_angles_2](https://user-images.githubusercontent.com/56953865/97629075-ca2e3680-19ea-11eb-812f-311c4a19fbf9.png)

From an initial inspection, this image doesn't appear consistent with what is observed by others in literature (3rd image, [paper link](https://pubmed.ncbi.nlm.nih.gov/24200876/) ), so I was wondering if @wahln or @eric11210 had any ideas why.

![image](https://user-images.githubusercontent.com/56953865/97629188-f944a800-19ea-11eb-9892-dd3d91fa7392.png)

**Comment by wahln** [comment]
This now happens on which branch / version exactly?

regarding the intersection-image: 
1) values of the heatmap: It hink it depends which OARs are selected?
2) white regions: depend on how potential collisions are handled?

**Comment by chh105** [comment]
Sorry I keep relying on you guys for research help, but I had another unrelated question I was hoping you could answer. I have a plan that was created in eclipse with dicoms for the CT, RT structures, RT dose, and RT plan. After importing the dicoms with matRad, I think the relevant information is now stored in the ct, cst, pln, doseGrid, and doseInfo variables (?). I would like to compute the paddick conformity index (the way it's computed in the file matRad_calcQualityIndicators.m), and I was wondering if you could point me in the right direction for getting the inputs to the function.

**Comment by wahln** [comment]
Hi @chh105,

regarding the matRad variables I would suggest to go through this: https://github.com/e0404/matRad/wiki/matRad-variables

Basically this means:
- Dicom CT -> `ct`
- RTStruct -> `cst`
- RTPlan -> `pln` & `stf`
- RTDose -> 3D dose cubes in `resultGUI`

The doseGrid and Info sub-structures within pln contain meta information (like resolution etc.).

So an example call would be 
`qi = matRad_calcQualityIndicators(cst,pln,resultGUI.phyiscalDose)`

There's also a function to get a quick display of DVH & QIs:
`[dvh,qi] = matRad_indicatorWrapper(cst,pln,resultGUI)`
But the above one gives you more control at which cube to look at.

**Comment by chh105** [comment]
Great, thanks again. I guess I was looking for the doseCube in the wrong places (doseGrid and doseInfo).
