### ISSUE TITLE
How to generate MEX file of ompMC

### ISSUE THREAD

**Issue by JAMKARAN** [e0404/matRad#463]
Hi Niklas @wahln
My question is about MC calculation of ompMC. After realizing the imperfection of ompMC for complex/real phantoms or patients, I want to change source type of Monte Carlo particle transports by adding standard phase-space or IAEA phase-space. So, I want to know how the new MEX file generated (in windows).

**Comment by wahln** [comment]
There is a function that tries to automatically generate the mex file from the ompMC code in the submodules folder:
https://github.com/e0404/matRad/blob/master/ompMC/matRad_compileOmpMCInterface.m

Secondly, you should read this:
https://www.mathworks.com/help/matlab/ref/mex.html

**Comment by JAMKARAN** [comment]
Thanks alot. Is that matlab fuction sufficient? without any addetional files/scripts?
In fact, I want to use a standard phase-space file (or IAEA phase-apace) resulting from BEAMnrc or other user codes of the EGSnrc MC package. Similarly you added a virtual source instead of a simple point source of photons and generated a new mex file, I want to produce a new mex file for new parameters.

**Comment by JAMKARAN** [comment]
Excuse me, when I want to use matRad_compileOmpMCInterface.m faced following error:
```
>> matRad_compileOmpMCInterface
Insufficient number of outputs from right hand side of equal sign to satisfy assignment.
Error in matRad_compileOmpMCInterface (line 58)
    ccName = myCCompiler.ShortName;

```

**Comment by wahln** [comment]
I don't really get the issue, it may seem that you are a few steps ahead of yourself.
1) The script _usually_ works, but depending on your compiler or your modifications to the C source code of ompMC to implement your phsp-reader it might not. Please do not expect that this stuff runs out-of-the-box, it is just a starting point.
2) Apparently you don't have a C compiler working with Matlab. Please understand that I won't assist with basic programming issues like installing C compilers or compiling, that's just too time consuming and there's enough info on that in the web.

**Comment by JAMKARAN** [comment]
Thanks Niklas . I don't C compiler on system. I have to install it.
