### ISSUE TITLE
Changing GUI plot axes labels

### ISSUE THREAD

**Issue by dan-hargreaves** [e0404/matRad#475]
I have been using MatRad to create new plots (e.g. dose distributions with variable RBE models for proton beam therapy).  I have been adding these plots to resultGUI so that MatRad automatically allows visualisation in the GUI.  When doing so, the plots are automatically assigned units [a.u]; I wish to change this to [Gy].  Does anybody know how to / where the information about units is stored?

Thank you.

**Comment by wahln** [comment]
The management of units / types of result cubes in the GUI is not completely thought through at the moment. Basically, in matRadGUI.m, there is a giant UpdatePlot(...) function that in the beginning checks for the name of the cube in the resultGUI and assigns units based on these names (Link for v2.10.1: https://github.com/e0404/matRad/blob/v2.10.1/matRadGUI.m#L950-L990)

Here, physicalDose gets "Gy", RBExD gets "GyRBE", etc.

It is somewhere on our list to refactor the management of result cubes and units, but if you have something in mind we are happy to hear suggestions.

By the way:
Have you seen our development branch dev_varRBErobOpt? The branch manages multiple biological models within the new matRad_bioModel class. It also has some variable RBE proton models pre-configured.  https://github.com/e0404/matRad/blob/dev_varRBErobOpt/matRad_bioModel.m
