### ISSUE TITLE
About the dose calculation for KV photon beam with matRad. 

### ISSUE THREAD

**Issue by YeseulKima** [e0404/matRad#476]
Hi! I'm a noob for this field and trying to get used to this program for my research.
My questions are about the dose calculation of the photon beam (~ 250 keV). I've read the reference papers and have a few questions to ask.

Reference: [1] http://www.ncbi.nlm.nih.gov/pubmed/8497215 & [2] diploma thesis of Martin Siggel "Entwicklung einer schnellen Dosisberechnung auf Basis eines Pencil-Kernel Algorithmus für die Strahlentherapie mit Photonen"

### 1. About the primary fluence
````
% prepare primary fluence array
primaryFluence = machine.data.primaryFluence;
r     = sqrt( (F_X-stf(i).ray(j).rayPos(1)).^2 + (F_Z-stf(i).ray(j).rayPos(3)).^2 );
Psi   = interp1(primaryFluence(:,1)',primaryFluence(:,2)',r,'linear',0);
    
% apply the primary fluence to the field
Fx = F .* Psi;
````
(^ "matRad_calcPhotonDose.m" , line 188~194)

![image](https://user-images.githubusercontent.com/74634747/103752068-8f7cf600-504c-11eb-9cff-9a19038e869f.png)
(^ Eq 19 of the first reference paper)

** Q1. Does the value Psi (line 191) indicate the Ψ'(x,y) on the reference paper? **
     (And then the value Fx (line 194) indicate Ψ'(x,y)*F(x,y) within the eq 19?)

![image](https://user-images.githubusercontent.com/74634747/103752962-bc7dd880-504d-11eb-9eb4-c307bad1cf17.png)

** Q2. ^ Which MC simulation did you use to get this primary fluence data?  **
     I'm wondering if I can ever replicate this part with some commercialized MC simulations such as TOPAS or Geant4.

### 2. Kernel calculation method
![image](https://user-images.githubusercontent.com/74634747/103754610-eafcb300-504f-11eb-9775-0e5cc803f4ea.png)
![image](https://user-images.githubusercontent.com/74634747/103754579-dfa98780-504f-11eb-9755-48869e82a02c.png)
(^ p.23 of the second reference paper)

**Q3. As long as I know the source file "init_kernel.cpp" is open-source. If so, where can I find it? **
And to solve equation 3.15, D_r(d) and D_i(d) should be obtained from MC simulation or experiment, right..?

I'd greatly appreciate any help you can offer.

Best regard, 
Yeseul Kim.

**Comment by wahln** [comment]
Here are some answers:
1)
The primary fluence is assumed to be rotation symmetric in its center, thus it is given depending on the radius r. The piece of code computes the radius r on the discretized field coordinates and computes the respective fluence for every point. Your comparison of code & paper veriables is therefore correct.
I am quite sure that the primary fluence is taken from measurements from an accelerator. In principle, you could also get this from let's say phsp files or your own simulation. For that you would need to model the bremsstrahlungs-target or some form of virtual source and score the fluence in the collimator plane, and extract the radial distribution. If you would like to have some form of asymmetric primary fluence, some code adaptations would be necessary.
2)
The C++ kernel computation code referenced in the thesis is not available. However, among our repos here there's also a repository that re-implements this kernel computation in Matlab given the respective quantities from measurements or MC simulations (TPRs, PDDs, prim. fluence, etc.): https://github.com/e0404/photonPencilBeamKernelCalc @markbangert and @mingersming may be able to further comment on this.

**Comment by YeseulKima** [comment]
Dear wahln, 
Thank you indeed for your answer! And I'm sorry for my late reply..

I've checked the link you attached above. That project files and paper of professor Thomas Bortfeld helped me understand the ballpark process to obtain the pencil beam kernel. With the question no 2, I should try and pay more time.. I really appreciate your help though. 

I hope all is well with you in this difficult time. 

Best regards, 
Yeseul Kim.
