### ISSUE TITLE
 matRad_OptimizerIPOPT error for matlab 2017b

### ISSUE THREAD

**Issue by naninano1** [e0404/matRad#481]
Hi,
The exe standalone matRad installation works properly on my computer. I can calculate the influence matrix and then optimize. ( I installed corresponding Matlab runtime 2019b separately).

In contrast, when I run matRad.m on Matlab (2017b), it passes the fluence matrix calculation step but terminates the Optimization with the following errors: 
![s](https://user-images.githubusercontent.com/77858420/105640943-6eaf0000-5e96-11eb-874d-69ff98c8237e.jpg)
_Error using matRad_OptimizerIPOPT/optimize (line 173)
Invalid MEX-file 'C:

Error in matRad_fluenceOptimization (line 219)

Error in matRad (line 67)_

I tried both GitHub default cloning and zip file extraction. No impact.

**Comment by wahln** [comment]
Unfortunately, there seemed to be some changes to Matlab's MEX-interface in Windows that broke compatibility for IPOPT. I could not figure out a way to compile ipopt to work with matlab versions older than 2018. 

You could try the following: 
 - If you have Matlab's optimization toolbox, use 'fmincon' by setting ´pln.propOpt.optimizer = 'fmincon';´ via script
 - Use an ipopt.mexw64 from an older release: https://github.com/e0404/matRad/blob/2.1.0/optimization/ipopt.mexw64
 - Compile the interface again from original source: https://github.com/ebertolazzi/mexIPOPT
