### ISSUE TITLE
How does matRad compute HI Index?

### ISSUE THREAD

**Issue by guillermoCabrera** [e0404/matRad#497]
Hi Guys,

I'm wondering how do you compute the HI index. When running the DAO algorithm, I've got HI Index values around 5~6, but I'm not really sure how do you obtain these values. 

Cheers
Guillermo

**Comment by markbangert** [comment]
What exactly do you mean with HI index?

guillermoCabrera ***@***.***> schrieb am Sa., 27. März 2021,
15:19:

**Comment by wahln** [comment]
The HI (Homogeneity Index) is computed in matRad_calcQualityIndicators in line 130:
https://github.com/e0404/matRad/blob/6fad1b8c07ea4d680e5c17615c5552659897e149/matRad_calcQualityIndicators.m#L130

It's the difference between D5 and D95 divided by a reference dose (which is obtained from the optimization objective) * 100.

**Comment by guillermoCabrera** [comment]
great! Thanks for the quick reply!

Cheers
Guillermo
