### ISSUE TITLE
A minor mistake in the liver.mat file 

### ISSUE THREAD

**Issue by naninano1** [e0404/matRad#501]
In the liver.mat case, I found that the liver minus CTV (LIVER-CTV) is defined as Target, while this structure is for evaluating the delivered dose to the healthy liver tissue not treatment. So it is better to replace its tag with OAR. Otherwise, the computation time will be very long. Because matRad considers fluence matrix and dose cube for the whole liver that is larger than needed. 

Thanks

**Comment by wahln** [comment]
This should now be resolved in #509. It has been merged into the dev branch and will then become part of the next release.
Thanks @naninano1 !
