### ISSUE TITLE
Generating SVD kernel 

### ISSUE THREAD

**Issue by JAMKARAN** [e0404/matRad#508]
I want to generate the singular-value-decomposed pencil beam kernels for the matRad using Monte Carlo. Do you have an idea? 
I searched in the [e0404/matRad](https://github.com/e0404/matRad) repository, I did not find anything about generating kernels using Monte Carlo according to [Bortfeld (1993)](https://aapm.onlinelibrary.wiley.com/doi/abs/10.1118/1.597070). 
 of course, I find Set of Matlab functions computing the convolution kernels for a singular-value-decomposed pencil beam dose calculation algorithm ([photonPencilBeamKernelCalc](https://github.com/e0404/photonPencilBeamKernelCalc)), but that use measured parameters such as primary fluence, OFs, and TPRs. What should we do if we do not have primary fluence? 
Thanks

**Comment by wahln** [comment]
I don't really understand what you want to look at exactly. You want to generate a base data set for a completely artificial set-up computed with MC? Or do you have your own machine set-up in your MC code that you are simulating?

**Comment by JAMKARAN** [comment]
Thanks for your response.

No, I think your approach to generate kernels may not be very accurate.

I want to generate PB kernels according to Bortfeld (1993). because I think primary fluence resulting from the decomposition of dose and kernels. So, I want to generate PB kernels using MC and then produce primary fluence.

**Comment by wahln** [comment]
I still don't fully get what you mean. The whole point of the Bortfeld 1993 algorithm is that you do not need to explicitly perform the kernel convolution at every spatial point based on fluence, but decompose the kernel and do some convolutions upfront for efficient computations. You can improve the accuracy of the kernels by using MC simulations of kernels which you then decompose, but I don't see what your issue with primary fluence is. The primary photon fluence is stored in the machine file (photons_Generic) for example in the data field. The photon dose calculation can assume a homogeneous primary fluence (default) or take the primary fluence from the machine file (in the new version: `pln.propDoseCalc.useCustomPrimaryPhotonFluence = true`, in older versions you need to manually switch in the `matRad_calcPhotonDose` function. The primary fluence is then convolved with the gaussian modeling the penumbra and the pre-computed kernel data....

**Comment by markbangert** [comment]
I am not familiar with the paper of Ahnesjo and Trepp and we do not have the time to look into this work. While matrad's pencil beam algorithm uses a superposition of three 2D convolutions to compute absorbed dose within the patient, most of the work I know from Ahnesjo that I know performs a full 3D convolution. Consequently, matRad uses pencil kernels and not point kernels which naturally involves a number of approximations in the dose calculation process. So in my opinion, any meaningful improvement regarding dose calculation accuracy over the existing algorithm should aim at a change of the overall dose calculation paradigm and not on an adjustment of the 2D kernels.

That being said: The kernels we supply with the  [photons_Generic.mat](https://github.com/e0404/matRad/blob/master/basedata/photons_Generic.mat) base data file have been computed with https://github.com/e0404/photonPencilBeamKernelCalc based on measured data.

**Comment by JAMKARAN** [comment]
Thanks to @wahln and @markbangert, sorry for the delay. 

On the third page of Bortfeld's article, it is stated that acquisition of the lateral distribution of the energy fluence has described by  Treuer et al. (1991), and Ahnesjo et al (1991).

A screenshot of this page/paragraph is provided below :
![image](https://user-images.githubusercontent.com/25560098/117528249-77ab8380-afe6-11eb-8072-df79fe87be75.png)

By reading this article ([Ahnesjo, 1991](https://iopscience.iop.org/article/10.1088/0031-9155/36/7/006)), we can understand that the kernels used are pencil beam kernels, not point kernels. 

![image](https://user-images.githubusercontent.com/25560098/117528733-f5708e80-afe8-11eb-8a69-4ad863f3e9e5.png)

I think it might be better to generate the PB kernels with Monte Carlo, then use deconvolution to get the primary fluence. Given your invaluable experience on the SVD method, do you have an idea for this? How much is the dose calculation affected by the primary fluence?

**Comment by markbangert** [comment]
What exactly do you mean when you talk about the primary fluence? In matrad
we denote the lateral fluence coming from the linear accelerator as primary
fluence, not the particle fluence inside the patient.

Jam karan ***@***.***> schrieb am Sa., 8. Mai 2021, 08:12:

**Comment by markbangert** [comment]
If you feel that you need to involve other people in a discussion we
encourage you to do so yourself.

We have to admit that our own research interest in photon pencil beam
algorithms is limited. Consequently, we cannot provide in depth support for
your idea. matRad is a community project and our team of postdocs and PhD
students has only somewhat limited time for support because all people
attend separate research projects.

Am Sa., 8. Mai 2021 um 13:57 Uhr schrieb Jam karan ***@***.***

**Comment by JAMKARAN** [comment]
Ok. Thank you for answering me honestly.

**Comment by JAMKARAN** [comment]
On the third page of Bortfeld's article, he stated "The kernel is derived from a database of monoenergetic, precalculate Monte Carlo kernel, using weights from effective spectrum". What do you think about this? 
I am currently working on generating the kernel using Monte Carlo. How do I generate the PB kernel of matRad using Monte Carlo?

**Comment by wahln** [comment]
I guess(!) they did simulations of monoenergetic photon beams in water and then pieced them together with weights according to the energey spectrum. Generating this kernels is not something you would do in matRad with the interfaced MC code. You would use a flexible, raw MC code like EGSnrc or PENELOPE. So I don't see how we can be of any assistance with this...

**Comment by JAMKARAN** [comment]
Thank you for sharing your wisdom with me.

Yes, my intention was not to generate PB kernel using matRad. I want to generate PB kernels using Monte Carlo and then implemete to matRad to improve accuracy of dose calculation.
