### ISSUE TITLE
Question about target point position？

### ISSUE THREAD

**Issue by wangwei19980727** [e0404/matRad#512]
Dear all:
     I have a question about target point position in stf. In proton optimization, what is the target point position, and why is this value twice than ray position?

**Comment by wahln** [comment]
I just adapted the Wiki to explain this:
https://github.com/e0404/matRad/wiki/The-stf-struct#stfray-substructure

The targetPoint(_bev) extends the ray from source to rayPos(_bev), which gives you the respective point of the ray in the isocenter plane, to behind the patient (at double the distance). It is used for raytracing to make sure the ray casts _fully through_ the patient.

**Comment by wangwei19980727** [comment]
OK, Thanks! I have known it. But i have some question about this software, Do you have discussion group or forum? 
Thank you again!

**Comment by wahln** [comment]
We are currently trying to realize such a forum using GitHub-Discussions:
https://github.com/e0404/matRad/discussions
Feel Free to start some topics there!

**Comment by wangwei19980727** [comment]
Thank you ！ Do you have some IMPT examples which have a more practical objective and constraint?
