### ISSUE TITLE
Could not find the following machine file: protons_matRadBDLold

### ISSUE THREAD

**Issue by wangwei19980727** [e0404/matRad#518]
Dear all:

      I am studying the example fitAnayticalParticleBaseData.m. And I found I haven't the file protons_matradbdload. so if you know where can download the file, please tell me.

**Comment by wahln** [comment]
could you quickly point me to the script fitAnalyticalParticleBaseData with a link?

**Comment by wangwei19980727** [comment]
https://github.com/e0404/matRad/blob/dev_varRBErobOpt/examples/matRad_example13_fitAnalyticalParticleBaseData.m
Thanks!

**Comment by wahln** [comment]
Ah I don't think that this example is "production ready" yet, sorry.

- It does not make sense to require a base data file when you want to fit MC data for which you do not have a base data file. 
- The matRadBDLold should not be in there. You can try to use MCsquare_generic instead, maybe this works
I think we need to ask @pamede what is going on here.

Any comments on this @pamede?

**Comment by wangwei19980727** [comment]
> could you quickly point me to the script fitAnalyticalParticleBaseData with a link?



> Ah I don't think that this example is "production ready" yet, sorry.
> 
> * It does not make sense to require a base data file when you want to fit MC data for which you do not have a base data file.
> * The matRadBDLold should not be in there. You can try to use MCsquare_generic instead, maybe this works
>   I think we need to ask @pamede what is going on here.
> 
> Any comments on this @pamede?

I try the mcsquare instead, but find a new bug in  line 166    resultGUI = matRad_calcDoseDirectMC(ct,stf,pln,cst,ones(sum(stf(:).totalNumOfBixels),1),1000000);.

**Comment by pamede** [comment]
I just tried it and found errors in the fitBaseData example. As mentioned by Niklas, it does not make sense to require any base data file to fit a new one. The problem is that the generateStf function requires a machine file to "prepare structures necessary for particles". I will look into it and try to fix it, when I find the time.

**Comment by wahln** [comment]
Yes - I think the workflow for fitting your own base-data-set should be something like this
- create a "dummy" basedata-file that only contains the required metadata and phase space information (i.e., energy levels, approximate peak positions, etc.) but obviously no tabulated data yet. In the example you read the BDL from MCsquare (which I guess would be one way to set up your initial information)
- set up the individual stf's within the computation & fitting loop directly. I don't know if using the standard matRad_generateStf is too effective here. I think some dedicated function like matRad_generateStfSinglePencilBeam would be more suited. This could also work withour requiring a dummy BDL file

**Comment by pamede** [comment]
I worked on the erros in the fitting process. The problem that the scripts need one to have the file protons_matRadBDLold and more, should be fixed (see. pull request [524](https://github.com/e0404/matRad/pull/524))
