### ISSUE TITLE
could not optimize: error using IPOPT Matlab interface [first timer]

### ISSUE THREAD

**Issue by facrinadi** [e0404/matRad#520]
after calculating influence mix, i was trying to optimize the treatment plan for 3DCRT but this error pop-up shows.
![image](https://user-images.githubusercontent.com/70350351/129384469-2fe0e3cf-d9cd-41bc-9cf7-e65b1da46d91.png)
it's my first time using matRad, and i dont know what to do. tia!

**Comment by wahln** [comment]
Please tell us the exact workflow, i.e. what options you enabled and what objectives/constraints you chose. Otherwise I can not reproduce the problem and then it's hard to figure out what's causing the error...

**Comment by TBurlacu-tud** [comment]
Hi all, 

I also see this on a Windows machine. The workflow is creating a photon plan with a couple of beams. 

The error
![MicrosoftTeams-image](https://user-images.githubusercontent.com/74507979/155106231-2339a568-0838-473f-ad9b-f18c6d2d64f7.png)

And the inputs

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/74507979/155107240-4703c167-45e6-43f1-a275-880c34fb41cb.png)

**Comment by wahln** [comment]
Thanks for the question. I don't have so much time this week to look into it, but my first guess that the `NaN` value in the PTV Min/Max dose constraints is the culprit. Try to replace it with `Inf`.
Apart from this, I want to point out that currently your setup seems to contain (only) hard constraints. In matRad, we strictly differentiate between "constraints" and objectives (this important distinction from an optimization perspective is usually not that present in the med phys literature). Currently, you basically pass a set of boundary conditions to the optimizer for which there is no feasible solution. Try to start with less constraints and use Squared Overdosing / Underdosing objectives. They represent minimizers to which you can assign a penalty value to define their importance.
