### ISSUE TITLE
matRad does not recognize DICOM files [BUG]

### ISSUE THREAD

**Issue by ybicke** [e0404/matRad#543]
**Describe the bug**
matRad does not recognize the DICOM files in the folder. When loading the folder, the following error message occures:
No DICOM files found in patient directory!

**To Reproduce**
1. Go to the Dicom folder
2. Choose the Folder (which is empty)
3. See error (obviously)

**Expected behavior**
I expected matRad to recognize the DICOM Files. 

**Screenshots**
![image](https://user-images.githubusercontent.com/80389002/150099878-32d32cc8-d4a5-433f-bf1a-e7e45fd0f04d.png)
![image](https://user-images.githubusercontent.com/80389002/150101758-fc522a54-7041-4cfd-b554-eda4048562dd.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Environment & Version [Matlab 2021a]
 - matRad 'Blaise' [2.10. 0]

**Additional context**
I have no idea, why matRad is not recognizing the dicom files. It works for other person in our group. Might it be, that they use an older matRad version? I think the file type should be appropriate. Would be glad to get help with this. Maybe the problem is known? 

Best Yves

**Comment by wahln** [comment]
Hi,
thanks for using the issue template.

A few things I notice:
- If you are using matRad 2.10.0, try maybe updating your code to 2.10.1 - there is some fixes to the DICOM parsing in this patch (I don't think it is relevant for you case, but it doesn't hurt)
- Your path is quite long, sometimes windows might have issues with too long filepaths. Maybe try to copy the files into a temporary folder with a very simple file path without special characters (e.g. C:\tmpDicom\ or something similar)

After that, if it doesn't help, we can also do some checks/debugging from the Matlab Command Window:

1. Go to your matRad folder and initialize the path by typing `matRad_rc`
2. Type `size(matRad_listAllFiles('path\to\your\dicom\folder'))` (replace the path\to\your\dicom\folder with your folder path), and  check if the size matches the number of files in your dicom folder. 
3. If the previous step gives sensible output, manually scan the dicom files with `test = matRad_scanDicomImportFolder('F:\dicom\TG119\');` Check for any errors there and analyze the output stored in `test` (in the workspace / variable editor of matlab). `test` should be a cell array containing information about the individual dcm files in each row.

Let me know if you identify anything weird in the steps above or if one of the two suggestions above worked.

**Comment by ybicke** [comment]
Hey! :) 

Many thanks for your support!!

I did the first two steps you suggested and it did not help. After that I continued with steps 1 and 2, and step 2 did not give any sensibel output. When I apply the size function in the Mathlab command line to the DICOM folder, I get 201 entries, while in Windows Explorer I get 200 entries. This seems already weird to me. 

Do you think that could be an issue? 

kind regards

**Comment by wahln** [comment]
Okay, it does not seem to be something system-specific. The 200 v. 201 issue might not be a problem, there's multiple things that could induce such an offset by 1. Im curious what step 3 does. Is the result empty then?

Also, could you run the Matlab-functions `dicomdisp` and/or `dicominfo` on one of the *.dcm files in the folder in question? E.g. `dicomdisp('path\to\your\dicom\folder\dicomFile.dcm')`? 
Just to check if Matlab itself recognizes the files as DICOM.

**Comment by ybicke** [comment]
Niklas Wahl ***@***.***> schrieb am 19. Jan. 2022 um 21:57:Okay, it does not seem to be something system-specific. The 200 v. 201 issue might not be a problem, there's multiple things that could induce such an offset by 1. Im curious what step 3 does. Is the result empty then?Also, could you run the Matlab-functions dicomdisp and/or dicominfo on one of the *.dcm files in the folder in question? E.g. dicomdisp('path\to\your\dicom\folder\dicomFile.dcm')? Just to check if Matlab itself recognizes the files as DICOM.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ybicke** [comment]
Step 3 sems to recognize the content. I get the following output in the cell array:
![image](https://user-images.githubusercontent.com/80389002/150218702-be98b552-a1e0-4fa8-84cc-d68bf07780ad.png)

Yesss, it finally worked!!!  ^^

It's funny the first step 3 didn't work initally and gave me the same output as matRad GUI. Now after trying to run your last suggestion with dicomdisp, I realized that I don't have the Image Processing Toolbox for Matlab installed. That seems to be the reason. x) 

It's always the little things that fail. I was not aware that I needed this toolbox for doing matRad stuff.  

Thanks a lot for your support
All the best

Translated with www.DeepL.com/Translator (free version)

**Comment by ybicke** [comment]
Yesss, it finally worked!!!  

It's funny the first step 3 didn't work initally and gave me the same output as matRad GUI. Now after trying to run your last suggestion with dicomdisp, I realized that I don't have the Image Processing Toolbox for Matlab installed. That seems to be the reason. x) 

It's always the little things that fail. I was not aware that I needed this toolbox for doing matRad stuff.  

Thanks a lot for your support
All the best

**Comment by wahln** [comment]
Ah yes, I could have thought of that, too. I expected a different error message (we really need to work on reporting errors in the GUIs better).
FYI: matRad only needs the image processing toolbox for DICOM import/export (and nothing else so far). Other toolboxes are not needed, but the Optimization Toolbox allows you to use the fmincon-optimizer instead of IPOPT, and some development branches allow use of features of the parallel computing toolbox. But they are both not necessary.
I will close the issue now - have fun with matRad!
