### ISSUE TITLE
About RTplan files

### ISSUE THREAD

**Issue by LGDi** [e0404/matRad#549]
Dear all,
When importing Dicom images, there are only CT images and no other structures.
![屏幕截图 2022-03-14 152951](https://user-images.githubusercontent.com/96415745/158126123-84654b80-9bcf-4a68-9c68-1f2f644ff3c4.png)
Actually，I just want to get RTplan and RTdose files, can I get these through matrad?
Thanks.

**Comment by wahln** [comment]
Okay, I don't fully understand the question:
Do you have your own RTStruct, RTPlan and RTDose or do you want to use matRad to create RTStruct, RTPlan, RTDose?

**Comment by LGDi** [comment]
Yes, as you can see, now there is no RTstruct, RTplan and RTdose, just a series of ct images,
But after reading your previous post, you mentioned slicer RT, I think I can get RTstruct through this.
About RTdose and RTplan available through matrad? Or can only export RTplan from TPS.

**Comment by wahln** [comment]
Okay, good. First of all, matrad has a dicom exporter. It can export CT series (from matRad's `ct` variable), RTStruct (from matRad's `cst` variable) and RTDose from matRad's `resultGUI´ variable). The first example demonstrates its use: https://github.com/e0404/matRad/blob/3d29b765a9a0a02a593890726102a7d9db907af7/examples/matRad_example1_phantom.m#L239-L246

Now to your question in more detail:
- There is no built-in way in matRad to draw / create contours. RTStruct may be exported from matRad, if contours are present within a cst. As you said, RTSlicer or MITK are good for segmenting/contouring CTs, and you can either export RTStruct from there directly or write binary masks that you then import in matRad
- We don't publish an RTPlan export so far. This is mainly to discourage people from plugging their matRad-plans into their TPS for treatments, which they absolutely must not do.

**Comment by LGDi** [comment]
Thank you very much for your prompt reply.
Yes, I can understand.It's a pity I don't have TPS by my side now.Other than that, is there any other way to get RTplan files?Other software or programs?Actually,I want some RTplan files and then do a simulation verification.

**Comment by wahln** [comment]
Not really, you need to write your own export to RTPlan or whatever format you need. If you don't have a TPS, what do you want the RTPlan feed into? A Monte Carlo engine or something like that?

**Comment by wahln** [comment]
Okay, which is the Monte Carlo program?
We have different exports available, I am currently checking, and might be able to send you some code via e-mail.

**Comment by LGDi** [comment]
TOPAS
I want to import my RTplan into TOPAS for simulation.But I can't implement this right now.

**Comment by wahln** [comment]
On the matRad-branch dev_varRBErobOpt (representing quite an extensive update planned for matRad) there is a prototype for forwarding simulations to topas (it does not export an RTPlan, but directly creates parameter files). The branch is under heavy development, but maybe it works for your purposes.

**Comment by LGDi** [comment]
Thank you very much for your prompt reply.I'll try this method.

**Comment by wahln** [comment]
Start with this script in the dev_varRBErobOpt branch to get MC running:
https://github.com/e0404/matRad/blob/dev_varRBErobOpt/examples/matRad_example12_simpleParticleMonteCarlo.m
In line 66 you can switch the engine to topas.
You need to specify in https://github.com/e0404/matRad/blob/dev_varRBErobOpt/topas/MatRad_TopasConfig.m how to call topas from the command line (l111-119 for the different operating systems).
Alternatively, you can just let the call fail and get all the parameter and input files from the standard directory they are generated in (topas/MCrun)

**Comment by LGDi** [comment]
When i run the example12_simpleParticleMontrCarlo.m,it came up with such an error.
![image](https://user-images.githubusercontent.com/96415745/174602271-ad46d2b5-2483-43aa-b7b8-24f287863e56.png)

**Comment by wahln** [comment]
I don't know what you are doing, but it seems like you are mixing to versions of matRad.
The development version on the dev_varRBErobOpt branch is quite different from the standard matRad version (Blaise, like your top line shows), and not fully downwards compatible.

Check out / download the full branch dev_varRBErobOpt, start a clean matRad instance in the respective folder, and the script should run. The script alone won't do it with a different version of matRad...

**Comment by LGDi** [comment]
I'm sorry for the late reply.After a few days of debugging I was able to run the example12_simpleParticleMontrCarlo. After that I got some txt files and ran them in topas to get a dose distribution map, I tried adding a uniform magnetic field to "World", but I found no change compared to before. I opened the visualization interface and found that only the first beam was deflected, and the others were the same as without the magnetic field. Do you know what is the reason for this?The image below shows the code for adding a magnetic field.
![image](https://user-images.githubusercontent.com/96415745/176080604-84e2d577-0a1f-4e3b-8e98-39d0b5bcf7a9.png)
