### ISSUE TITLE
patient position

### ISSUE THREAD

**Issue by myy-imp** [e0404/matRad#551]
Can the matRad treatment planning system be able to deal with patients in a  'HFP' (Head First-Prone) position?

**Comment by wahln** [comment]
We haven't tried it out yet. Our code in the dicom importer is somewhat indifferent about it:
https://github.com/e0404/matRad/blob/3d29b765a9a0a02a593890726102a7d9db907af7/dicom/matRad_importDicomCt.m#L119-L139

It says in the comments that HFP is not supported, but the code below does allow it. My assumption is that it will import it normally, but either the patient is upside down in the viewer (which would be easy to fix manually by flipping the imported CT image) or it will be just imported somewhat correctly.
So I would just try it out with a DICOM import and see if it works. If you know some publicly available dataset with a patient in HFP position, let us know - then we can also investigate further.
