### ISSUE TITLE
Is there a code to initialize double gaussian model?

### ISSUE THREAD

**Issue by Erhushenshou** [e0404/matRad#556]
Thanks for previous codes provided. I see there is a testing code to calculate sigma by inspiration from the paper. However, double gaussian model is more popular. Do you have such code?

**Comment by wahln** [comment]
There is a reason we have issue templates for questions / bugs / feature reqeusts. I know its more work for you to follow them, but following them would clarify to us direclty what files you are on about and what exactly you want to achieve...
> I see there is a testing code to calculate sigma by inspiration from the paper
Which paper? Which part of the code (provide maybe a github-link to the lines of code)?

So here's my counter-questions before I can think about an answer:
- Do you mean the double gaussian kernel model for the analytical computation or a double gaussian source emittance model for MC calculations?
- What do you mean by initialize now? For what purpose? Fitting base data or dose calculation itself?
- The protons_Generic_MCsquare analytical base data has a double-Gaussian description of the kernel width, so check this out if you want to know the correct base data format.

**Comment by Erhushenshou** [comment]
Sorry for the inconvenience. This is the paper about double gaussian model in Eclipse. https://pubmed.ncbi.nlm.nih.gov/27908162/. The testing code Mark provided is here https://de.mathworks.com/matlabcentral/fileexchange/70416-multiple-coulomb-scattering.
I mean double gaussian kernel model for analytical computation. But MC calculations with gaussian is also likely explored. We are trying to fitting our measured data into matrad model. Or splitting the model from Eclipse to matrad proton. The protons_Generic_MCsquare analytical base data needs to input the double gaussian kernel width. But how is this modeled?

**Comment by wahln** [comment]
> The protons_Generic_MCsquare analytical base data needs to input the double gaussian kernel width. But how is this modeled?

I don't exactly understand what you want to know. The base data file _already has_ a double Gaussian parameterization, meaning it has stored `sigma1` and `sigma2`, with a `weight`. The exact computation during dose calculation is here: https://github.com/e0404/matRad/blob/master/matRad_calcParticleDoseBixel.m#L39-L56. `sigma1` (weighted with `1-weight`) describes the narrow component, and `sigma2` weighted with `weight` describes the broad component. 

If you want to generate such data, you need to **fit** to measurements. We do not analytically compute double gaussian models, thus we don't have a formula / code for that. The protons_Generic_MCsquare has been fitted to simulations with MCsquare. Mark's MCS code does represent the single Gaussian Highland-Approximation and does not transfer to double-gaussian models. It has been used to analytically compute the protons_Generic dataset.

**Comment by markbangert** [comment]
No. As @wahln already pointed out, \sigma_1 and \sigma_2 are determined via *fitting*. If you want to model your machine in matRad with a custom double Gaussian, this means you would have to perform fits yourself. A viable alternative could be to adjust only the initial beamwidth and SAD according to your beamline and assume that your protons behave similar to the matRad double Gaussian in the patient. This will of cource neglect some details like angular confusion in the beam but could work.

**Comment by wahln** [comment]
And I still don't understand what you mean by "you don't model this" when you explicitly want to base your data on measurements. 
1. We "model" it in the proton_Generic_MCsquare, i.e., the dose calculation can compute it. 
2. The code I gave you in #554 explicity fits a double gaussian model, which is exactly what you seem to want to do. The function might not work out of the box, but it should be enough to start with.

**Comment by Erhushenshou** [comment]
The situation is now we want to model double gaussian in Eclipse, I wanna find some inspiration from matrad. Thanks anyway.

**Comment by wahln** [comment]
Perfect! I will close this issue.
