### ISSUE TITLE
specific proton machine commissioning 

### ISSUE THREAD

**Issue by ancewer** [e0404/matRad#562]
Hello developers

you are doing a great job for radiation therapy community.
matRad has generic proton machine data, I have some experience on MCsquare and TOPAS proton beam commissioning, but I did not find any document with matRad. how can I commission a specific proton machine for matRad, is there any ideas or code to convert MCsquare BDL to matRad machine data? thank you very much.

Best,
Mark

**Comment by wahln** [comment]
Hi Mark,

we are currently working on providing an example script/template of how to create a tabulated base data set using matRad or TOPAS. There is no documentation on exactly how to do it, however there is a Wiki page describing the contents of a "machine" file.
https://github.com/e0404/matRad/wiki/Particle-Base-Data-File

If you have an MCsquare BDL, you can simulate the dose distribution in a high-resolution water phantom for the energies you need, and then fit the lateral distribution with a single or double gaussian in depth and extract integrated depth dose curve (you may add LET as well if you like). Then you need to provide the beam optics, i.e. the widening of the beam in air, as a focus table (width of the beam in air at certain distances from the isocenter), which can be computed using the depth-dependence of the Courant–Snyder parameters.

There exists an example script on the branch dev_varRBErobOpt that somehow introduces a fitting process based on MCsquare. But it's not working out of the box yet, and there is still an open pull request in #524 that we need to finalize. If you want to check this out and give us feedback, that would be greatly appreciated, we would be happy to assist in the base data fitting / commissioning procedure.

If you want to use TOPAS for reference simulations, you can be more efficient by tuning your geometry and scorers (i.e. variable binning in depth for IDD) for the task. This is not included in the example script, however.
