### ISSUE TITLE
Meaning of Precomputed Contours in cst

### ISSUE THREAD

**Issue by LGDi** [e0404/matRad#564]
Dear developers：
The target area and OAR are stored in cst.I would like to know the meaning of the data in the seventh column (Precomputed Contours).Inside are some two-dimensional arrays, and then some columns of data like the following, what do they mean? Are the coordinates representing specific structures (but they don't look alike)?
![image](https://user-images.githubusercontent.com/96415745/173583696-66f2938b-c3a4-4c1a-83a3-055142664770.png)
![image](https://user-images.githubusercontent.com/96415745/173583751-f91b16a5-12ae-422f-9367-3618d29425dc.png)
Best，
Li

**Comment by wahln** [comment]
Check out the function `matRad_computeVoiContours`
The countours are in the format returned by [Matlab's `contourc` function](https://de.mathworks.com/help/matlab/ref/contourc.html).

**Comment by wahln** [comment]
You can check out discussion #563 on this topic, it is possible but not that trivial, unfortunately.
