### ISSUE TITLE
When using Topas authentication, the following problem occurs.

### ISSUE THREAD

**Issue by LGDi** [e0404/matRad#567]
Dear developers：
When running matRad_example12_simpleParticleMonteCarlo, some txt files don't seem to be exported.
![image](https://user-images.githubusercontent.com/96415745/177793681-70bffc35-0198-4dc7-a215-0264e58fbf5b.png)

**Comment by HomolkaN** [comment]
Hi, 

Sorry for the late reply. I can't seem to reproduce your Error. Did you make any changes to the example other than switching to TOPAS? Could you provide me with additional details on how to reproduce this error?

Best, Noa

**Comment by LGDi** [comment]
I set the ‘pln.propStf.gantryAngles’ to 0 and 90 degrees.When there are two field angles, output the running file of topas.Then it gives the above error.
But now I have a new question.When I did this again, there were other errors.
![image](https://user-images.githubusercontent.com/96415745/180203960-6ccc91f5-4020-4f30-87c3-7bb120495400.png)

**Comment by wahln** [comment]
You didn't set just two gantry angles 0 and 90, you set the gantryAngles to `0:90`, which in Maltab syntax translates to having 0,1,2, ..., 90 as angles... Note that you can always check contents of the fields from the command line or the workspace / variable editor widget...

**Comment by LGDi** [comment]
I adjusted the gantryAngles and I still have the same problem.
![屏幕截图 2022-07-25 145244](https://user-images.githubusercontent.com/96415745/180716545-054741b1-7eba-467e-8627-c5524bc54f40.png)
![屏幕截图 2022-07-25 145346](https://user-images.githubusercontent.com/96415745/180716565-49520940-7e55-4e60-b28f-293a7d49bbc9.png)

**Comment by HomolkaN** [comment]
Hi, a fix for this problem will be implemented in the next patch. Sorry for the inconvenience.
