### ISSUE TITLE
From matRad to MCsquare for simulation

### ISSUE THREAD

**Issue by LGDi** [e0404/matRad#581]
When converting data from matrad to MCsquare's input file, I encountered the following problem:
![image](https://user-images.githubusercontent.com/96415745/199961656-0e79c1b5-2a58-46f3-8582-ec6ceeef7803.png)
It says "reference to non-existent field 'energyLayer'",I really didn't find this "energyLayer" parameter in the "stf" structure, I looked up the wiki for "stf" and it doesn't mention this parameter either, I wonder what it is. How should the output of imported parameters from matrad to MCsquare be implemented.

**Comment by wahln** [comment]
You can not call matRad_writeMCsquareinputAllFiles from scratch. If you want to calculate dose with MCsquare, you need to call matRad_calcParticleDoseMC (to compute full dose influence matrix) or matRad_calcDoseDirectMC (for forward dose calculation). Within these functions, which call the respective Monte Carlo interface (in your case matRad_calcParticleDoseMCsquare), the stf will be reordered to sort spots in energy layers.

As a side note: I see, you are also already working on the dev_varRBErobOpt branch. There will soon be an update to the branch that gives more options when working with Monte Carlo dose calculation. Among others, it will give you the option to store beam optics & Gaussian energy spectrum directly in the matRad base data. Most of this will be merged with #536 within November.

**Comment by LGDi** [comment]
Thank you very much for your quick reply.This solved my problem.Also, about the input parameter 'filename' in matRad_writeMCsquareinputAllFiles, is it the name of a blank file?

**Comment by wahln** [comment]
Check the Code of [matRad_calcParticleDoseMCsquare](https://github.com/e0404/matRad/blob/05db32a31303bb78c9f2cc70feab9ea0f1af31e3/matRad_calcParticleDoseMCsquare.m)

The file name is, in the current branch state, hardcoded here:
https://github.com/e0404/matRad/blob/05db32a31303bb78c9f2cc70feab9ea0f1af31e3/matRad_calcParticleDoseMCsquare.m#L254
and then fed into the function call here:
https://github.com/e0404/matRad/blob/05db32a31303bb78c9f2cc70feab9ea0f1af31e3/matRad_calcParticleDoseMCsquare.m#L404
Then it is passed to the MCsquare call here:
https://github.com/e0404/matRad/blob/05db32a31303bb78c9f2cc70feab9ea0f1af31e3/matRad_calcParticleDoseMCsquare.m#L406-L409

So it is the name of the configuration file that you would pass to MCsquare when you'd call it from the command line.

**Comment by LGDi** [comment]
![image](https://user-images.githubusercontent.com/96415745/201301286-459e95b2-588f-448b-8a40-bd2e5c46ffd4.png)
When I run 'dij = matRad_calcParticleDoseMCtopas', it shows 'TOPAS simulation exited with error code 1'.
