### ISSUE TITLE
[BUG] matRad_rc fails in Octave 7.3.0

### ISSUE THREAD

**Issue by ranmalmendis** [e0404/matRad#595]
**Describe the bug**
I am getting an error when running MatRad with Octave's latest version on windows
error: 'matRad_getEnvironment' undefined near line 27, column 16
error: called from
    matRad_rc at line 27 column 14
>>

Kindly advice us on how to fix that.

**To Reproduce**
1. Open matRad on GNU Octave 7.3.0
2. Run the command 'matRad_rc'
4. You'll get an error "error: 'matRad_getEnvironment' undefined near line 27, column 16
error: called from
    matRad_rc at line 27 column 14
>>"
**Expected behavior**
This should start matRad normally in the way it works with the latest version of MatLab

**Screenshots**
![Screenshot 2023-01-15 at 18 38 33](https://user-images.githubusercontent.com/30996087/212542604-389d0c6f-7a7b-4875-97b5-2fcf55e8cb10.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Environment & Version: GNU Octave 7.3.0
 - matRad Version: Latest version

**Additional context**
Kindly let me know an Octave version that's compatible with matRad Latest version in the Github default branch.

Thanks

**Comment by PamodiRanmal** [comment]
I even tried to fix that with 'addpath(pwd)'. But still, I get this error. I look forward to hearing from you soon.

**Comment by wahln** [comment]
Dear @PamodiRanmal 
Thanks for reporting this (and trying out the fix), we will look into it. What you could check is if using `addpath(genpath(pwd))` works (this adds the folder and all subfolders). However, still other errors might come up in this octave version. You will also probably need to compile the optimizer. 
Octave is not our primary focus (its notably slower), but our Tests run through on 5.2 without error. We may check out compatibility with Octave 7.3. just before the next release, potentially.

**Comment by PamodiRanmal** [comment]
Dear @wahln,
Thank you very much for the quick reply. I tried the command addpath(genpath(pwd)) . Now the command 'matRad_rc' works without giving the previous errors. Thanks again. I'll check other functions etc also and try to switch back to the octave version you mentioned(5.2) if I get further errors. 
![Screenshot 2023-01-18 at 13 36 01](https://user-images.githubusercontent.com/30996087/213117291-e02ccd2b-917b-45a6-a831-45d9a474af83.png)

**Comment by lukevoss** [comment]
This issue will be resolved in upcoming releases as it no longer occurs on the newer development branches!

**Comment by wahln** [comment]
Thanks @lukevoss for investigating this further. The issue seems to be that the matRad folder is not correctly identified in Octave 6 & 7 when  setting the filepath as a constant property in our configuration class. We don't do this on our main current development branches dev & dev_varRBErobOpt any more.
Will leave this open until the new release is out.

**Comment by wahln** [comment]
When PR #519 is merged, Octave testing will be shifted to v6.4 and together with this the fix for the above problem will be merged. No plans for testing on Octave 7.X for now. 

We should update https://github.com/e0404/matRad/wiki/How-to-run-matRad-with-Octave then accordingly.
