### ISSUE TITLE
Question about proton dose calculation (related to spot spacing)

### ISSUE THREAD

**Issue by justingm** [e0404/matRad#603]
Hello,

I am doing some proton dose calculation test in water for the beam model that I made.
This is more for preclinical use so the water volume is just 10x10x12mm3 and the target is 2x2x2mm3 at a depth of 6 mm.
I set the bixel width to 0.2 mm and the longitudinal spot spacing to 0.2 mm. From what I understood the bixel width is the lateral spot spacing while the longitudinal spot spacing will control the energy layers chosen for the SOBP. 
Given this, I expect that I would have around 100 spots in 1 layer and ~10 energy layers. Looking at the sft struct, numOfRays is 121, numOfBixelsPerRay is 12 and totalNumOfBixels is 1452. If I understood correctly, numOfRays is the number of spots in an energy layer, numOfBixelsPerRay is the number of spots in the beam direction for a single ray and totalNumOfBixels is the total number of spots. This close to what I expected. However, when I looked at the dose distributions, it seems like I only have 9 spots in each energy layer (see figure below). As can be seen from the transverse profile, you can also see 3 prominent peaks and in between those, the dose seems to be lower. I am not exactly sure whether there are really 121 spots in each layer and the weights of the spots are just not optimized properly or there are only 9 spots for each energy layer. Is there some way to confirm this? Thanks!

![image](https://user-images.githubusercontent.com/72226803/222193152-fd8208d0-80e0-4efd-ab82-a3a75a2bba15.png)
![image](https://user-images.githubusercontent.com/72226803/222193215-25450423-fbae-4ea0-8743-75e916771724.png)
![image](https://user-images.githubusercontent.com/72226803/222193452-a4ec1e4f-994b-4aa3-8898-8841c88eaa5e.png)

Best,
Justin

**Comment by justingm** [comment]
I checked the resultGUI.w weight vector and there are indeed 1452 entries. I guess the problem is that for some spots, the weight is very low compared to others. I tried your suggestion to set a lower value for the acceptable_obj_change_tol but that did not make much difference.

I was playing around with it and when I have one beam coming from each direction x, y and z (3 beams orthogonal to each other), then I get this flat distribution in the target.

**Comment by wahln** [comment]
Seems a little fishy to me.
have you checked the ray positions in the stf? Are the beamlets correctly set-up in the 0.2 mm grid?

You could also try to throw spots with small weights of a first optimization out of the dij and do a reoptimization with the reduced spot set.

**Comment by justingm** [comment]
I also find it weird that I needed 3 beams in each direction to get a homogeneous dose distribution in the target.
Here's the summary of the parameters that I used and some plots of the dose distribution and DVH for single, two and three beam case (for better visualization).
[matRad_water_test_preclinical.pdf](https://github.com/e0404/matRad/files/10910291/matRad_water_test_preclinical.pdf)

Yes I checked the ray positions and they are indeed in placed in a 0.2 mm grid.

As for your suggestion of throwing away spots, isn't this just the same as choosing a different spot spacing? Because the spots with low weights are in between the spots with high weights and they seem to be evenly spaced.

I also tried to remove the dose objective on the "OAR" but that didn't also do much.

**Comment by wahln** [comment]
I'm equally confused about this. The three beams could help to mitigate a hidden geometrical issue (e.g. if the energy levels are correct, but the lateral spacing gets somewhere messed up in the dose calculation). What happens with two opposing beams? Do you see the lateral spacing at the same location?

Some more things to validate:
- are you confident that the dose calculation recognizes the 0.1mm voxel grid as well? Check that dij.doseGrid really contains the respective information. 
- what is the final objective function value (and the other optimization indicators, the console should print it at the end and during each iteration)? What is the message of the optimizer finishing? 
- have you computed example spot doses of the "in-between" spots with matRad_calcCubes after optimization? Just to see visually that the dose distributions appear also at the correct locations? It's a little annoying to get the indexing right here, but the helper variables in dij.rayNum, which tells you to which ray the bixel with index i belongs, might help here

**Comment by justingm** [comment]
What happens with two opposing beams? Do you see the lateral spacing at the same location?

> - With two opposing beams at 90 and 270 deg, the behavior remains the same. You see that there are regions with higher dose and then it dips and then goes back up again.

![dose_isocenter](https://user-images.githubusercontent.com/72226803/223654380-c94d7cf7-6da5-4017-b9b0-3aa8a0b8a316.png)

Some more things to validate:

Are you confident that the dose calculation recognizes the 0.1mm voxel grid as well? Check that dij.doseGrid really contains the respective information.

> I've checked that too. It is indeed 0.1 mm.

What is the final objective function value (and the other optimization indicators, the console should print it at the end and during each iteration)? What is the message of the optimizer finishing?

> The final objective function value is 1.85e+01 (scaled). It does say it was solved to acceptable level. Here's the complete log file.
[matRad_log_single_beam.txt](https://github.com/e0404/matRad/files/10919083/matRad_log_single_beam.txt)

Have you computed example spot doses of the "in-between" spots with matRad_calcCubes after optimization? Just to see visually that the dose distributions appear also at the correct locations? It's a little annoying to get the indexing right here, but the helper variables in dij.rayNum, which tells you to which ray the bixel with index i belongs, might help here

> Yes. I've tried this when I was checking what was wrong. Everything seems to be in the right place.

I've tried a different plan wherein I created another structure. This structure is just a 0.5 mm margin on each side of the target. I've done this because I've noticed that the slices towards the end of target (whichever direction) gets a lower dose. I guess it is because the spot placing starts and ends at the border of the target. If I set the same dose objectives for this structure as the target, I get a flat dose distribution in the target and I don't see this wiggle behavior in between spots.

![image](https://user-images.githubusercontent.com/72226803/223675510-dfae5389-27bd-48d9-9e6f-59de126727aa.png)

**Comment by justingm** [comment]
Actually, that's not entirely true. You can still see some alternating structure which is also evident in the profile but the wells are already at >=59Gy so I guess that's fine.

![image](https://user-images.githubusercontent.com/72226803/223678207-da3ed5f1-7fb5-4274-818b-5a99d1e9aa41.png)

![image](https://user-images.githubusercontent.com/72226803/223678661-764f91ac-aeda-445b-9783-0595f26b5d41.png)

**Comment by wahln** [comment]
ah damn I should have also considered this earlier. 
In the matRad_generateStf function, we use a margin around the target to try to compensate for this behavior by putting spots outside of the target as well. Usually this should suffice to get sufficient coverage, but sometimes (depends on the interplay of "bixel width"  and resolution) you might end up with a set-up that is not able to cover the target in full. 

I think we need to update the rationale we use this to both consider resolution and bixel-width (currently, only resolution is considered and one voxel is added). I think we do this for robust optimization on our development branch, but not on the standard branch. 

If it is hardly possible to achieve smooth coverage due to having no spots outside, then the optimizer will overcompensate particularly at the lateral penumbra and you might get these wiggles. This will become worse when you have a strong outside / OAR objective pulling dose down, because the sharpest penumbra is achieved by a single spot, so the optimizer will try to shape the whole lateral penumbra by a single spot producing these lateral horns.

**Comment by justingm** [comment]
In the matRad_generateStf function, we use a margin around the target to try to compensate for this behavior by putting spots outside of the target as well. Usually this should suffice to get sufficient coverage, but sometimes (depends on the interplay of "bixel width" and resolution) you might end up with a set-up that is not able to cover the target in full.

> I have tried to do this manually (only in 2D) to find the optimal spacing between the spots and I saw that you'd have to have a few spots outside the target to achieve a flat coverage. However, upon inspection, the spots starts at -1 and ends at +1 (for a 2 mm target). I figured that might be causing the problem. It is also a bit trickier when dealing with smaller volumes.

I think we need to update the rationale we use this to both consider resolution and bixel-width (currently, only resolution is considered and one voxel is added). I think we do this for robust optimization on our development branch, but not on the standard branch.

> I would think that the bixel width would have a greater effect in this. I've tried adding different number of voxels as margin but w/ 1 or 2 voxels, the wiggle is still very much pronounced.

If it is hardly possible to achieve smooth coverage due to having no spots outside, then the optimizer will overcompensate particularly at the lateral penumbra and you might get these wiggles. This will become worse when you have a strong outside / OAR objective pulling dose down, because the sharpest penumbra is achieved by a single spot, so the optimizer will try to shape the whole lateral penumbra by a single spot producing these lateral horns.

> I agree that the OAR dose objective/constraints also affects how the optimization goes. Maybe I could also play around with this but this part largely depends on what the biologists want as well. Not much I can do here. 

> The overcompensation is indeed a problem since these horns fall on the margin that I created w/c is technically a part of the OAR. But then again you can only do so much with an animal. Structures are so small that you also have targeting accuracy issues.

**Comment by justingm** [comment]
If it is hardly possible to achieve smooth coverage due to having no spots outside, then the optimizer will overcompensate particularly at the lateral penumbra and you might get these wiggles. This will become worse when you have a strong outside / OAR objective pulling dose down, because the sharpest penumbra is achieved by a single spot, so the optimizer will try to shape the whole lateral penumbra by a single spot producing these lateral horns.

> I have one question about this though. It makes sense to me that the optimizer will overcompensate on the last few spots w/c results to the horns near the border of the target. For the first plan that I did (i.e., one which seemed to have only 3 spots in a row) I would expect that I have horns but in between these horns, it would be more or less flat. However, what you see is the horn, dip, another peak, dip and horn. Why is it that the spots in the middle get higher weights?
