### ISSUE TITLE
Questions about proton dose display

### ISSUE THREAD

**Issue by LGDi** [e0404/matRad#604]
Dear Developers,
I completed the dosage calculation in Topas, displayed the result in the GUI interface, and found that it showed a complete proton beam trajectory, including the section in the air. Is there any way to display only the proton beam in the body .
In addition, there is another question, is there a way to import the file in ASCII format into the dose distribution of the GUI?

**Comment by wahln** [comment]
First question: You can set all voxels outside the contour to zero. The dose should be stored in resultGUI.physicalDose, for example, and the index list of the outer contour will be stored in the 4th column of the respective row in the cst, e.g., `cst{i,4}{1}`

So, short script (not guaranteed to work):
```
tmp = zeros(size(resultGUI.physicalDose));
tmp(cst{i,4}{1}) = resultGUI.physicalDose(cst{i,4}{1});
resultGUI.physicalDoseClean = tmp;
```
After executing this code, where i should be the number of the row of the body / skin / external structure in the cst, you should have a cleaned dose distribution selectable in the GUI as physicalDoseClean after refreshing.

I don't understand the second question. For importing ASCII into Matlab arrays, refer to the Matlab documentation. In matRad, you can put any dose cube as an array in resultGUI, e.g., resultGUI.physicalDoseImported, and then select it from the GUI. Just needs the same dimensions.
