### ISSUE TITLE
[BUG] Warning and error messages in matRad_readNRRD fail, string concatenation is wrong when lineContent is an empty cell

### ISSUE THREAD

**Issue by zperko** [e0404/matRad#605]
**Describe the bug**
When reading NRRD files and seeing empty lines or other content for which a warning/error is raised, the warning/error messages themselves are wrong, the string concatenation doesn't work with lineContent being an empty cell.

**To Reproduce**
Read and NRRD file that would raise a warning/error according to the lineConcent in matRad_readNRRD.m

**Expected behavior**
Error/warning line just executes properly, raising the error/warning. 

**Solution**
The strings in the warning/error messages should be properly formatted, an exception for empty cell should work. Might be an issue in several other functions too.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Environment & Version [e.g. Matlab 2020b]
 - matRad Version [e.g. 2.10.0] If developing with git, state the branch and commit ID, if possible

**Additional context**

**Comment by zperko** [comment]
For lines 63 and 71 lineContent should probably be currentLine

**Comment by wahln** [comment]
Yeah, this block:
https://github.com/e0404/matRad/blob/cb6b04a603533a5906617d489eb36e4a054eaa3a/IO/matRad_readNRRD.m#L61-L71
We should replace the formatting like we do in other functions using the printf-like syntax and, as you said, in line 63 and 71, use currentLine.
