### ISSUE TITLE
matRad_PlotVoiContourSlice tries to access ct as cell [BUG]

### ISSUE THREAD

**Issue by zperko** [e0404/matRad#606]
**Describe the bug**
matRad_PlotVoiContourSlice can try to access the ct structure as a cell, causing crash.

**To Reproduce**
When a cst structure doesn't have pre-calculated contours the function tries to do this, but fails, ct is not a cell but a structure.

**Expected behavior**
Should not fail and correctly calculate contours. 

**Potential solution**
Line 83 should probably be
mask = zeros(size(ct.cube{ctIndex})); OR
mask = zeros(size(ct.cubeHU{ctIndex}));

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Environment & Version: Matlab 2021b
 - matRad Version [e.g. 2.10.0] If developing with git, state the branch and commit ID, if possible

**Additional context**

**Comment by amitantony** [comment]
If this is in the context of using matRad_plotSliceWrapper, issue may be that in calling matRad_plotVoiContourSlice currently we only pass ct.HU and not the whole ct struct. will fix this in the bug fix
