### ISSUE TITLE
[BUG] No error on missing Image Processing Toolbox installation

### ISSUE THREAD

**Issue by SakuMyl** [e0404/matRad#616]
**Describe the bug**
I had a license for image toolbox but it was not installed. Matrad gave no error.

**Expected behavior**
I expect to see a clear error message stating that I have a license for Image Processing Toolbox but it is not installed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Matlab 2023a
 - matRad Version: git commit [b2ce690](https://github.com/e0404/matRad/commit/b2ce6901f18ad11f198f2919138e2e65d5feec6d)

**Additional context**
The file matRad_scanDicomImportFolder.m does a check on whether a license for the toolbox exists. My version passed this test as the license exists. Later in the code calling the function 'dicominfo' fails because I do not have the toolbox installed. However, this prints no error, as the failure to call this function is simply handled in a catch block without an error message.

**Comment by wahln** [comment]
Thanks for the report. Fixing such "nice to have" error messages has, however, a low priority for us. We will eventually work on it, but we would also welcome a pull request if you have the time, since you already looked at it.

**Comment by SakuMyl** [comment]
I have left a pull request @wahln
