### ISSUE TITLE
Attempts to grow an array along an ambiguous dimension

### ISSUE THREAD

**Issue by LGDi** [e0404/matRad#632]
Dear developers,
When I try to use matRad-dev_varRBErobOpt to generate the running file in Topas, "Attempts to grow an array along an ambiguous dimension" appears. But the last time I used it, I didn't encounter this problem.
![image](https://github.com/e0404/matRad/assets/96415745/f824e5a3-91e2-4b0d-be67-b395fe4470c1)

**Comment by LGDi** [comment]
I have tried several other models and found that this error only occurs in the topas file output when using two shot fields in the head and neck model.

**Comment by wahln** [comment]
Thanks, can you provide a script file of your workflow that enables us to reproduce this problem?

**Comment by LGDi** [comment]
First, I imported the 'HEAD_AND_NECK' model in matRadGUI, set the gantry and couch angles, and then calculated the dose effect matrix.
![image](https://github.com/e0404/matRad/assets/96415745/c20e0975-c00b-461e-8944-8ae02af19c9d)
Next I executed 'resultGUI = matRad_calcDoseDirectMC(ct,stf,pln,cst,w)', 
![image](https://github.com/e0404/matRad/assets/96415745/4f5b5931-0b82-44e2-b94f-6a0211e27a8a)
and then encountered the following error.
![image](https://github.com/e0404/matRad/assets/96415745/08ae6277-56b5-4a62-9fdd-4f8116b92d4c)

**Comment by wahln** [comment]
This error sometimes happen when there's leftover data from a previous run. I haven't figured it out yet why exactly it happens.
