### ISSUE TITLE
RBE model

### ISSUE THREAD

**Issue by hliu-opt-5143** [e0404/matRad#697]
Could I ask what type of variable RBE model is currently implemented in the corresponding branch? Is there a reference or paper that I can learn more math background about the models?

Thank you much!

**Comment by wahln** [comment]
The master & dev currently has, for protons, only constant RBE and for carbon ions LEM IV. The dev_varRBErobOpt has multiple proton LET dependent models (at least McNamara [MCN] & Wedenberg [WED] should working). It has helium ions with the model by Mairani et al. and carbon ions with LEM IV. 
Note that the carbon ion's LEM model bases on precomputed alpha and beta kernels in the carbon machine data for the pencil-beam algorithm - in principle, new machine data can be generated with other models used.
The dev_varRBErobOpt branch also has an interface to TOPAS with which, in principle, also models relying on tabulated alpha/beta vs energy vs ion type can be run by modifying the precomputed files.

We are currently in a bigger effort to rewrite the biological modeling and simulate some new machine data such that these model types become clearer and matRad becomes more flexible in biological modeling.

**Comment by hliu-opt-5143** [comment]
Thank you very much! This is very helpful!
