### ISSUE TITLE
Lateral cutoff

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#7]
Consider implementing a voxel dsampling strategy for DIJ computation

comp http://www.ncbi.nlm.nih.gov/pubmed/12033562

**Comment by rcorredorj** [comment]
Hi again,

I take advantage of this post to ask you something about the lateral cutoff. In the wiki you say that "[Currently this variable is already set to 20mm which is quite tight so we do not recommend this](https://github.com/e0404/matRad/wiki/Dose-influence-matrix-calculation#computational-bottlenecks)". However, doing some tests with 20 mm and 30 mm, the results are practically the same. Is there any recommendation for choosing this parameter or any special consideration?

Thank you !

**Comment by rcorredorj** [comment]
Hi again,

I take advantage of this post to ask you something about the lateral cutoff. In the wiki you say that "[Currently this variable is already set to 20mm which is quite tight so we do not recommend this](https://github.com/e0404/matRad/wiki/Dose-influence-matrix-calculation#computational-bottlenecks)". However, doing some tests with 20 mm and 30 mm, the results are practically the same. Is there any recommendation for choosing this parameter or any special consideration?
 
Thank you !

**Comment by markbangert** [comment]
Well basically the answer is given in the paper above. I would like to have sampling included and then compute maybe up to a sampling radius of 80mm and keep the inner radius at 20mm if that is feasible with regard to computation time and memory consumption. I mean there is always a trade off between that: time/memory on the one side and precision on the other side. I figure if you compare 80mm versus 20mm you might see a difference..

**Comment by becker89** [comment]
I think we can close this issue now.
