### ISSUE TITLE
RT Plan Export to Commercial TPS (Eclipse)

### ISSUE THREAD

**Issue by edwardwang1** [e0404/matRad#703]
Hello,

Apologies if I have used the wrong tags for this issue. 

**I want to implement and contribute the following feature to matRad:**
For research (NOT CLINICAL) purposes, I am interested in exporting the result of my matRad treatment planning (either via an RTPlan or raw control points) so that I can import it into the testing environment of Eclipse. I believe that other researchers may also find such functionality useful.

**Current state of the contribution:**
I have not yet started building an RTPlan export module in matRad.

**I have the following issues:**
From this issue https://github.com/e0404/matRad/issues/549 it seems that such an export is discouraged. Is this still the stance of the development team?

**Further questions:**
If there is any code floating around that could give me a head start on this, I would appreciate it!

Thanks,
Edward

**Comment by wahln** [comment]
Currently we still refrain from providing an RTPlan export in the public repository. 
If you write an e-mail to our contact e-mail, I can provide you with a prototype for an RTPlan export (photon IMRT, doesn't work on particles yet). But also note that working with an RTPlan export only really makes sense if corresponding machine data is used in recalculations.

**Comment by edwardwang1** [comment]
Excellent, that would be great! I have just sent you an email. We are working with photon VMAT, but the IMRT code will help us get started.
