### ISSUE TITLE
matRad_calcDoseDirectMC(ct,stf,pln,cst,dij.bixelNum)  

### ISSUE THREAD

**Issue by 12echi** [e0404/matRad#742]
>> resultGUI = matRad_calcDoseDirectMC(ct,stf,pln,cst,dij.bixelNum)
Class matRad_MCsquareConfig has been loaded to pln.propMC!
81  switch pln.propMC.engine
文件: matRad_calcParticleDoseMCtopas.m 行: 149 列: 69
运算符的使用无效。

出错 matRad_calcDoseDirectMC (第 85 行)
        dij = matRad_calcParticleDoseMCtopas(ct,stf,pln,cst,calcDoseDirect);
        
This problem occurs in the matRad_calcDoseDirectMC function after the breakpoint is switched from "pln.propMC.engine" to topas before selecting topas and MCsquare. Is it a topas path problem or other problems? How to solve it? Thank you very much

**Comment by wahln** [comment]
Which branch are you using exactly (i.e., what is the output of matRad_rc)?

The current version on dev / dev_varRBErobOpt introduces a new interface. To unify dose calculation under one call, you now use the functions` dij = matRad_calcDoseInfluence(...)` or `resultGUI = matRad_calcDoseForward(...) `. 
Before calling these functions, you can set the dose engine by changing `pln.propDoseCalc.engine`, e.g., `pln.propDoseCalc.engine = 'TOPAS'`. Further, you can set parameters used for this engines in `pln.propDoseCalc`, e.g., to change the histories for forward calculation you say `pln.propDoseCalc.numHistoriesDirect = 1e7`.

You can check for the available dose calculation engines with:
`DoseEngines.matRad_DoseEngineBase.getAvailableEngines().shortName`
If you already have a pln with a radiationMode and a machine set, you can also pass this to the function
`DoseEngines.matRad_DoseEngineBase.getAvailableEngines(pln).shortName`
to only show engines available for this modality-machine combination.

The older functions like calcDoseDirect(MC) are still supported, but default to the implementations they called before. calcDoseDirectMC will always try to use MCsquare (as this is default behavior in the previous release), while calcDoseDirect will always use the pencil-beam implementations (SVD for photons, HongPB for particles).

**Comment by wahln** [comment]
Nothing happening here, will close
