### ISSUE TITLE
compile application error

### ISSUE THREAD

**Issue by gleesoi** [e0404/matRad#745]
H, i am writing some custom code to use along with the gui. when i go to compile to stand alone exe, i get error below. any ideas or help much appreciated!thanks

![image](https://github.com/e0404/matRad/assets/75881142/0d3bf27e-58b5-41e2-89e0-41d97ea9db77)

**Comment by wahln** [comment]
In MatRad_Config.m, there is path modification going on (addpath / genpath). We haven't checked the build process for this with late code changes. Probably needs some isdeployed if/else statments. We will look into the build process over the next weeks anyways, then we can figure it out.

**Comment by wahln** [comment]
Perfect. I also pushed a fix to the [dev](https://github.com/e0404/matRad/tree/dev) branch regarding the compilation in https://github.com/e0404/matRad/commit/767b35312a4765125fa85d247931570299625fa1. Will close this issue now.
