### ISSUE TITLE
6x photon calibration data not given in wiki

### ISSUE THREAD

**Issue by spitzbubchen** [e0404/matRad#79]
I am wondering under what calibration conditions was your photons_Generic.mat calculated at? Is it dose/MU? In our clinic we use 0.85 cGy/MU for a 10x10 field at 100 SAD at 10 cm depth.

**Comment by markbangert** [comment]
In our clinic we also set a reference point at 1 cGy/MU for a 10x10cm^2 field at 100cm SAD and 100cm SSD at 5cm or 10cm depth. For the data given, however, this normalization does not hold (yet). Compared to the original publication http://www.ncbi.nlm.nih.gov/pubmed/8497215 we still have a couple of simplifications (SSD dependce of kernels, incorporation of primary fluence) in the code. At the moment, however, we are working with high pressure on a validation of our photon dose calculation algorithm that we plan to release over the summer.

If you want to use matRad to also obtain MUs of treatments you also have to bear in mind that the implemented sequencers do not yield clinically applicable segments. Usually they are very rugged and disconnected. However, you can still do a manual normalization of our treatment plans if you want. You just have to simulate an open 10x10cm^2 field and make the normalization yourself for a specific point in the irradiated phantom.
