### ISSUE TITLE
How to get xyz coordinates for specific voxel in Dij?

### ISSUE THREAD

**Issue by stoyhris** [e0404/matRad#796]
**What is the question? Which file(s) does it concern?**
I would like to write a function such that, when passed a set of indices in the Dij, it returns the (x,y,z) coordinates for the associated voxels. The data included in the CT and Dij variables (after loading DICOMs into matRad and computing the Dij matrix) is three separate vectors of x coordinates, y coordinates, and z coordinates, but I am having trouble determining the correct way to enumerate them such that they are associated with the correct rows in the Dij. 

**I have checked the following matRad Wiki pages and references:**
Here is a snippet of my current code, which follows the description detailed in the following wiki. This generates a table by enumerating over each dimension's vector, but I am not convinced it associates correctly with the Dij. 
https://github.com/e0404/matRad/wiki/The-matRad-coordinate-system

I haven't had any luck finding documentation on this. Could this community offer any thoughts?

```matlab
%% First, map the cst to the space of the Dij 

vXgridOld = dij.ctGrid.x;  
vYgridOld = dij.ctGrid.y;  
vZgridOld = dij.ctGrid.z;  

vXgridNew = dij.doseGrid.x; 
vYgridNew = dij.doseGrid.y;  
vZgridNew = dij.doseGrid.z;  

cst_mapped = matRad_resizeCstToGrid(cst, vXgridOld, vYgridOld, vZgridOld, vXgridNew, vYgridNew, vZgridNew);

%% Now, find the appropriate indices for each structure (manually select one target structure)

targetRow = find(strcmp(cst_mapped(:,2),'CTV_BREL'));
targetIndices = targetData{1};

%% Generate voxel coordinates 

% Extract x, y, z coordinates from dij.doseGrid
x_coords = dij.doseGrid.x;
y_coords = dij.doseGrid.y;
z_coords = dij.doseGrid.z;

% Generate all combinations of x, y, z coordinates
[Z, Y, X] = ndgrid(z_coords, y_coords, x_coords);

% Flatten the grids into column vectors
x_values = X(:);
y_values = Y(:);
z_values = Z(:);

% Create an index array for sorting based on the LPS system
combData = [(1:numel(x_values))', x_values, y_values, z_values];

% Sort according to the specified order: x decreases, y decreases, z increases
[~, sortOrder] = sortrows(combData(:, 2:4), {'descend', 'descend', 'ascend'});
combData = combData(sortOrder, :);

% Extract coordinates for target and OAR as n-by-3 double arrays
targetTable = combData(targetIndices, 2:4);

**Comment by wahln** [comment]
Are you using the most recent release v3.1.0? It has functions to relate indices to coordinates (but interprets isocenter coordinates differently, so handle with care ;-)). Even if you don't use it, it shows how grids relate to indices:
https://github.com/e0404/matRad/blob/98ba2fb8b07f727a3963cf2572c82a548444580b/matRad/geometry/matRad_cubeIndex2worldCoords.m

Regarding your code, not sure if ndgrid is the right call at that point, and I also don't think the order is correct. I also don't exactly understand the code after that.

Here's what I would do: 
1. Get the subscripts (3D indices) of the linear index you pass to the dij: `[targetIndex_i,targetIndex_j,targetIndex_k] = ind2sub(dij.doseGrid.dimensions,targetIndices);`
2. Get the coordinate from the dose grid: 
    ```matlab
    targetCoords_x = dij.doseGrid.x(targetIndex_j);
    targetCoords_y = dij.doseGrid.y(targetIndex_i);
    targetCoords_z = dij.doseGrid.z(targetIndex_k);
    ```
In the newest version, you can just call the `matRad_cubeIndex2worldCoords.m` function like:
`targetCoords = matRad_cubeIndex2worldCoords(targetIndex,dij.doseGrid);`
This will return the coordinates in a matrix with the columns representing (x,y,z).

**Comment by stoyhris** [comment]
I see! Updated to the newest version and the index-to-coordinate function worked perfectly. Thank you very much!
