### ISSUE TITLE
Unable to Set Window Range for dose distribution 

### ISSUE THREAD

**Issue by MP1234567899** [e0404/matRad#803]
Hi,

With the latest update of matRad for robust optimization, I am planning a treatment plan using the proton therapy mode with the HongPB algorithm. After completing the optimization, I need to check the dose distribution and identify where the hot dose areas are located. However, I am unable to use the function to set the window range. I used matRad in V3.1.0 MATLAB 24.1 2024a

Thank you

**Comment by wahln** [comment]
Tests Running at the moment, will merge then. After #805 is merged, you can check out the dev branch and it should have the fix for choosing the display window in there.

**Comment by wahln** [comment]
Merged!
