### ISSUE TITLE
Convenient/fast figure to image export from GUI

### ISSUE THREAD

**Issue by wahln** [e0404/matRad#99]
A fast figure export from the current dose view to the gui would be nice.
Something like that: 

```
%guiHandle = matRadGUI;
data = guidata(guiHandle);
colorbar = findall(guiHandle,'Type','colorbar');
figure; 
new_handle = copyobj([data.axesFig colorbar],gcf);
set(new_handle(1),'units','normalized', 'OuterPosition',[0 0 1 1]);
saveas(gcf,'export.png');
```

I may incorporate something like that into the gui in near future.

**Comment by markbangert** [comment]
Oh that would really be a supercool feature! 100% support from my side.

**Comment by becker89** [comment]
Yes - it would be nice having a "Screenshot" button as part of the toolbar on the upper left side of the GUI

**Comment by wahln** [comment]
done
